---
named_interfaces::config:
  mgmt:
    - br0
  trp:
    - br1
  transport:
    - br1
  service:
    - br1

# Turn off bird on controller until we use cumulus
profile::openstack::network::calico::manage_bird: false

profile::bootstrap::himlar::libvirt:
  '%{location}-admin-01':
    domain:          "%{hiera('domain_mgmt')}"
    libvirt_pool:    'dirpool'
    libvirt_network: 'directnet'
    install_ip:      "%{hiera('netcfg_mgmt_netpart')}.11"
    install_netmask: "%{hiera('netcfg_mgmt_netmask')}"
    install_gateway: "%{hiera('netcfg_mgmt_gateway')}"
    vm_vcpus:        2
    vm_memory:       4096
    vm_console:      false
    use_dhcp:        false

sensu__disk__warning:     80

# Create and enable more swap
profile::base::common::extraswap:         true
profile::base::common::extraswap_sizegb:  10
profile::base::common::extraswap_fileloc: '/var/lib/libvirt/images/swapfile'
