---
api_ssl_pem:      "api.uh-iaas.no.pem"
status_ssl_pem:   "status.uh-iaas.no.pem"
#console_ssl_pem:  "console.uh-iaas.no.pem"
#access_ssl_pem:   "access.uh-iaas.no.pem"

profile::highavailability::loadbalancing::haproxy::haproxy_balancermembers:
  network:
    server_names:
      - '%{::location}-network-02'
      - '%{::location}-network-03'
    ipaddresses:
      - "%{hiera('netcfg_trp_netpart')}.72"
      - "%{hiera('netcfg_trp_netpart')}.73"
  compute:
    server_names:
      - '%{::location}-novactrl-02'
      - '%{::location}-novactrl-03'
    ipaddresses:
      - "%{hiera('netcfg_trp_netpart')}.67"
      - "%{hiera('netcfg_trp_netpart')}.68"
  placement:
    server_names:
      - '%{::location}-novactrl-02'
      - '%{::location}-novactrl-03'
    ipaddresses:
      - "%{hiera('netcfg_trp_netpart')}.67"
      - "%{hiera('netcfg_trp_netpart')}.68"
