---
profile::storage::ceph_crushbucket::buckets:
  'storage':
    bucket_type:   'pod'
    bucket_parent: 'default'
  'huawei': # FIXME
    bucket_type:   'pod'
    bucket_parent: 'default'

named_interfaces::config:
  mgmt:
    - em3
  trp:
    - team1

profile::base::network::network_auto_opts:
  mgmt:
    'defroute': 'yes'
  trp:
    'defroute': 'no'
    'ipv6init': 'no'
    'mtu':      '1500'
    'devicetype': 'Team'
    'team_config': >-
                   { "runner" : {  "name" : "lacp",  "active": true, "fast_rate" : true,
                   "tx_hash": ["eth", "ipv4", "ipv6"], "tx_balancer": { "name": "basic" } },
                   "link_watch" : {  "name" : "ethtool" } }

profile::base::network::network_auto_bonding:
  trp:
    em1:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '1500'
    em2:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '1500'

profile::base::common::manage_lvm: true
profile::base::lvm::physical_volume:
  '/dev/sda4':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_ceph':
    physical_volumes:
      - /dev/sda4
profile::base::lvm::logical_volume:
  'lv_ceph':
    volume_group: 'vg_ceph'
    fs_type:      "xfs"
    mountpath:    "/var/lib/ceph"
