---
named_interfaces::config:
  mgmt:
  - eth2
  trp:
  - team1
  live:
  - team1.120

profile::base::network::network_auto_bonding:
  trp:
    eth0:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'
    eth1:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'

# Turn off nested virtualization
profile::virtualization::nested::manage: false

profile::base::common::packages:
  'numactl': {}

# Enable hugepages to prevent OOM-killer when using NUMA
profile::base::physical::enable_hugepages: true
# Number and size of hugepages, based on 512GB - 32 GB (4GB free pr node)
profile::base::physical::hugepagesz:       '2M'
profile::base::physical::hugepages:        '245760'


# Nova overrides
nova::compute::libvirt::cpu_models: ['EPYC']
nova::cpu_allocation_ratio:         '1'
nova::disk_allocation_ratio:        '1'
nova::ram_allocation_ratio:         '1'

# Create and enable more swap
profile::base::common::extraswap:        true
profile::base::common::extraswap_sizegb: 10

profile::base::lvm::physical_volume:
  '/dev/sda4':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_ext':
    physical_volumes:
      - /dev/sda4
profile::base::lvm::logical_volume:
  'lv_instances':
    volume_group: 'vg_ext'
    fs_type:      "xfs"
    mountpath:    "/var/lib/nova/instances"

# This compute host uses local storage for instances
nova::compute::rbd::ephemeral_storage:  false
nova::compute::libvirt::images_type: 'default'

# Configuration items not explicitly supported by the Puppet module
nova::config::nova_config:
  DEFAULT/metadata_workers:
    value: '2'

# Sensu
sensu::agent::annotations:
  'disk_warning': '90'
  'disk_critical': '95'
  'cpu_warning': '99'
  'cpu_critical': '100'
