---
include:
  default:
    - nova::compute::mdev
    - profile::application::create_mdev

named_interfaces::config:
  mgmt:
    - em3
  trp:
    - team1
  live:
    - team1.120

profile::base::network::network_auto_bonding:
  trp:
    p3p1:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'
    p3p2:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'

profile::base::network::network_auto_opts:
  mgmt:
    'defroute': 'no'
  trp:
    'defroute': 'no'
    'ipv6init': 'yes'
    'devicetype': 'Team'
    'mtu': '9000'
    'team_config': >-
                   { "runner" : {  "name" : "lacp",  "active": true, "fast_rate" : true,
                   "tx_hash": ["eth", "ipv4", "ipv6"], "tx_balancer": { "name": "basic" } },
                   "link_watch" : {  "name" : "ethtool" } }
  live:
    'defroute': 'no'

profile::base::lvm::physical_volume:
  '/dev/sda4':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_ext':
    physical_volumes:
      - /dev/sda4
profile::base::lvm::logical_volume:
  'lv_instances':
    volume_group: 'vg_ext'
    fs_type:      "xfs"
    mountpath:    "/var/lib/nova/instances"

# Enable extra yum repo vGPU drivers
profile::base::yumrepo::repo_hash:
  nrec-nonfree:
    ensure: present

profile::base::common::packages:
  'wget': {}
  'kernel-devel': {}
  'kernel-headers': {}
  'unzip': {}
  'NVIDIA-vGPU-rhel': {
#    source: 'http://repo.mgmt.bgo.uhdc.no/NVIDIA-vGPU-rhel-7.8-450.55.x86_64.rpm'
  }

# NVIDIA P40 partitioned into 2x vGPUs, with CUDA support (Q type)
#
# From "mdevctl types":
#
#  nvidia-52
#    Available instances: 1
#    Device API: vfio-pci
#    Name: GRID P40-12Q
#    Description: num_heads=4, frl_config=60, framebuffer=12288M, max_resolution=7680x4320, max_instance=2
#
# Example: 'nvidia-35' or ['nvidia-35', 'nvidia-36']
#
nova::compute::mdev::mdev_types:
  nvidia-52: {}

# Configuration values for the "create-mdev" service
profile::application::create_mdev::enable:                true
profile::application::create_mdev::nvidia_gpu_type:       'nvidia-52'
profile::application::create_mdev::max_instances_per_gpu: 2

# remove when telemetry/ceilometer is up in all environments and move to common
profile::openstack::compute::manage_telemetry: true

profile::base::physical::blacklist_drv: true
profile::base::physical::blacklist_drv_list:
  'nouveau': {}

nova::compute::libvirt::cpu_models: ['Cascadelake-Server-noTSX']

# These compute host uses local storage for instances
nova::compute::rbd::ephemeral_storage: false
nova::compute::libvirt::images_type: 'default'

# Configuration items not explicitly supported by the Puppet module
nova::config::nova_config:
  DEFAULT/metadata_workers:
    value: '4'

