---
include:
  default:
    - multipath
    - profile::base::lvm
    - profile::base::nfs
  kickstart:
    - multipath
    - profile::base::lvm

profile::base::common::packages:
  'lsscsi': {}

# We use lagre iscsi disk for nfs
sensu__disk__warning:     82

multipath::blacklist:
  'devnode': [ '"^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"', '"^hd[a-z][[0-9]*]"', '"^cciss\!c[0-9]d[0-9]*"', '"^(sda|sdb|vda|vdb)"' ]

multipath::devices:
  - 'vendor':               '"HITACHI"'
    'product':              '"OPEN-.*"'
    'path_grouping_policy': "multibus"
    'path_selector':        '"round-robin 0"'
    'path_checker':         'tur'
    'features':             '"0"'
    'hardware_handler':     '"0"'
    'prio':                 'const'
    'rr_weight':            'uniform'
    'no_path_retry':        '6'
    'rr_min_io':            '1000'
    'rr_min_io_rq':         '1'

profile::base::lvm::physical_volume:
  '/dev/mapper/mpatha':
    ensure: present
    force:  true
  '/dev/mapper/mpathb':
    ensure: present
    force:  true
  '/dev/mapper/mpathc':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_volume':
    physical_volumes:
      - /dev/mapper/mpatha
      - /dev/mapper/mpathb
      - /dev/mapper/mpathc
profile::base::lvm::logical_volume:
  'lv_volume':
    volume_group: 'vg_volume'
    fs_type:      "xfs"
    mountpath:    "/opt/volumeshare"

profile::base::nfs::manage_firewall: true
profile::base::nfs::create_share:    true
profile::base::nfs::shares:
  'volumeshare':
    'share':   '/opt/volumeshare'
    'guest':   ''
    'options': 'rw,sync,no_root_squash'

profile::base::nfs::mount_fwsettings:
  source: "%{::network_trp1}/%{::netmask_trp1}"
