---
# Frontend zone
profile::dns::ns::frontend_zone: "uh-iaas.no"
profile::dns::ns::frontend_zone_new: "nrec.no"

# Designate server addresses (used by file templates)
profile::dns::ns::use_public_ip: true
profile::dns::ns::mdns_public_addr:
  - '2001:700:2:82ff::256'
  - '2001:700:2:83ff::256'

# DNS server firewall configuration (IPv6)
profile::dns::ns::rndc_sources_ipv6:
  - '2001:700:2:82ff::256/128'
  - '2001:700:2:83ff::256/128'

# Name servers in zone file
profile::dns::ns::ns_master: "ns1.%{hiera('profile::dns::ns::frontend_zone')}"
profile::dns::ns::ns_slaves:
  - "ns2.%{hiera('profile::dns::ns::frontend_zone')}"

# Master server for master-slave configuration
profile::dns::ns::ns_master_ip_addresses:
  - '158.39.77.251'        # ns2.uh-iaas.no IPv4 (BGO)
  - '2001:700:2:83ff::251' # ns2.uh-iaas.no IPv6 (BGO)

# Slave servers for master-slave configuration
profile::dns::ns::ns_slave_ip_addresses:
  - '158.39.77.251'        # ns2.uh-iaas.no IPv4 (BGO)
  - '2001:700:2:83ff::251' # ns2.uh-iaas.no IPv6 (BGO)

# Forward zones, for which the name server is authoritative
profile::dns::ns::fw_zones:
  internal:
    zone: "%{hiera('profile::dns::ns::internal_zone')}"
    filename: "pz/%{hiera('profile::dns::ns::internal_zone')}"
  public:
    zone: "%{hiera('profile::dns::ns::public_zone')}"
    filename: "pz/%{hiera('profile::dns::ns::public_zone')}"
#    delegations:
#      'customer':
#        - 'ns1.uh-iaas.no'
#        - 'ns2.uh-iaas.no'
  frontend:
    zone: "%{hiera('profile::dns::ns::frontend_zone')}"
    filename: "pz/%{hiera('profile::dns::ns::frontend_zone')}"
    ns_a_records:
      'ns1': "%{hiera('public__ip__ns')}"
      'ns2': '158.39.77.251'
    ns_aaaa_records:
      'ns1': "%{hiera('public__ipv6__ns')}"
      'ns2': '2001:700:2:83ff::251'
    delegations:
      'osl':
        - 'ns1.uh-iaas.no'
        - 'ns2.uh-iaas.no'
      'bgo':
        - 'ns1.uh-iaas.no'
        - 'ns2.uh-iaas.no'
  frontend_new:
    zone: "%{hiera('profile::dns::ns::frontend_zone_new')}"
    filename: "pz/%{hiera('profile::dns::ns::frontend_zone_new')}"


# Reverse zones, for which the name server is authoritative
profile::dns::ns::ptr_zones:
  mgmt01:
    cidr:     "%{hiera('netcfg_mgmt_net_c0')}.0/24"
    origin:   "%{hiera('reverse_mgmt_c0')}"
    filename: "pz/%{hiera('reverse_mgmt_c0')}"
  mgmt02:
    cidr:     "%{hiera('netcfg_mgmt_net_c1')}.0/24"
    origin:   "%{hiera('reverse_mgmt_c1')}"
    filename: "pz/%{hiera('reverse_mgmt_c1')}"
  mgmt03:
    cidr:     "%{hiera('netcfg_mgmt_net_c2')}.0/24"
    origin:   "%{hiera('reverse_mgmt_c2')}"
    filename: "pz/%{hiera('reverse_mgmt_c2')}"
  mgmt04:
    cidr:     "%{hiera('netcfg_mgmt_net_c3')}.0/24"
    origin:   "%{hiera('reverse_mgmt_c3')}"
    filename: "pz/%{hiera('reverse_mgmt_c3')}"
  mgmt05:
    cidr:     "%{hiera('netcfg_mgmt_net_c4')}.0/24"
    origin:   "%{hiera('reverse_mgmt_c4')}"
    filename: "pz/%{hiera('reverse_mgmt_c4')}"
  mgmt06:
    cidr:     "%{hiera('netcfg_mgmt_net_c5')}.0/24"
    origin:   "%{hiera('reverse_mgmt_c5')}"
    filename: "pz/%{hiera('reverse_mgmt_c5')}"
  mgmt07:
    cidr:     "%{hiera('netcfg_mgmt_net_c6')}.0/24"
    origin:   "%{hiera('reverse_mgmt_c6')}"
    filename: "pz/%{hiera('reverse_mgmt_c6')}"
  mgmt08:
    cidr:     "%{hiera('netcfg_mgmt_net_c7')}.0/24"
    origin:   "%{hiera('reverse_mgmt_c7')}"
    filename: "pz/%{hiera('reverse_mgmt_c7')}"
  transport01:
    cidr:     "%{hiera('netcfg_trp_net_c0')}.0/24"
    origin:   "%{hiera('reverse_trp_c0')}"
    filename: "pz/%{hiera('reverse_trp_c0')}"
  transport02:
    cidr:     "%{hiera('netcfg_trp_net_c1')}.0/24"
    origin:   "%{hiera('reverse_trp_c1')}"
    filename: "pz/%{hiera('reverse_trp_c1')}"
  transport03:
    cidr:     "%{hiera('netcfg_trp_net_c2')}.0/24"
    origin:   "%{hiera('reverse_trp_c2')}"
    filename: "pz/%{hiera('reverse_trp_c2')}"
  transport04:
    cidr:     "%{hiera('netcfg_trp_net_c3')}.0/24"
    origin:   "%{hiera('reverse_trp_c3')}"
    filename: "pz/%{hiera('reverse_trp_c3')}"
  transport05:
    cidr:     "%{hiera('netcfg_trp_net_c4')}.0/24"
    origin:   "%{hiera('reverse_trp_c4')}"
    filename: "pz/%{hiera('reverse_trp_c4')}"
  transport06:
    cidr:     "%{hiera('netcfg_trp_net_c5')}.0/24"
    origin:   "%{hiera('reverse_trp_c5')}"
    filename: "pz/%{hiera('reverse_trp_c5')}"
  transport07:
    cidr:     "%{hiera('netcfg_trp_net_c6')}.0/24"
    origin:   "%{hiera('reverse_trp_c6')}"
    filename: "pz/%{hiera('reverse_trp_c6')}"
  transport08:
    cidr:     "%{hiera('netcfg_trp_net_c7')}.0/24"
    origin:   "%{hiera('reverse_trp_c7')}"
    filename: "pz/%{hiera('reverse_trp_c7')}"
  public01:
    cidr: "158.37.63.0/24"
    origin: "63.37.158.in-addr.arpa"
    filename: "pz/63.37.158.in-addr.arpa"
  public02:
    cidr: "158.39.75.0/24"
    origin: "75.39.158.in-addr.arpa"
    filename: "pz/75.39.158.in-addr.arpa"
  public03:
    cidr: "158.39.48.0/24"
    origin: "48.39.158.in-addr.arpa"
    filename: "pz/48.39.158.in-addr.arpa"
  ipv6:
    cidr: "2001:700:2:82ff::/64"
    origin: "f.f.2.8.2.0.0.0.0.0.7.0.1.0.0.2.ip6.arpa"
    filename: "pz/f.f.2.8.2.0.0.0.0.0.7.0.1.0.0.2.ip6.arpa"

# Secondary forward zones, for which this ns is slave
profile::dns::ns::fw_slave_zones:
  bgo_internal:
    zone: "bgo.uhdc.no"
    filename: "sz/bgo.uhdc.no"
  bgo_public:
    zone: "bgo.uh-iaas.no"
    filename: "sz/bgo.uh-iaas.no"

# Secondary reverse zones, for which this ns is slave
profile::dns::ns::ptr_slave_zones:
  bgo_mgmt01:
    cidr: "172.16.0.0/24"
    origin: "0.16.172.in-addr.arpa"
    filename: "sz/0.16.172.in-addr.arpa"
  bgo_mgmt02:
    cidr: "172.16.1.0/24"
    origin: "1.16.172.in-addr.arpa"
    filename: "sz/1.16.172.in-addr.arpa"
  bgo_mgmt03:
    cidr: "172.16.2.0/24"
    origin: "2.16.172.in-addr.arpa"
    filename: "sz/2.16.172.in-addr.arpa"
  bgo_mgmt04:
    cidr: "172.16.3.0/24"
    origin: "3.16.172.in-addr.arpa"
    filename: "sz/3.16.172.in-addr.arpa"
  bgo_mgmt05:
    cidr: "172.16.4.0/24"
    origin: "4.16.172.in-addr.arpa"
    filename: "sz/4.16.172.in-addr.arpa"
  bgo_mgmt06:
    cidr: "172.16.5.0/24"
    origin: "5.16.172.in-addr.arpa"
    filename: "sz/5.16.172.in-addr.arpa"
  bgo_mgmt07:
    cidr: "172.16.6.0/24"
    origin: "6.16.172.in-addr.arpa"
    filename: "sz/6.16.172.in-addr.arpa"
  bgo_mgmt08:
    cidr: "172.16.7.0/24"
    origin: "7.16.172.in-addr.arpa"
    filename: "sz/7.16.172.in-addr.arpa"
  bgo_transport01:
    cidr: "172.18.0.0/24"
    origin: "0.18.172.in-addr.arpa"
    filename: "sz/0.18.172.in-addr.arpa"
  bgo_transport02:
    cidr: "172.18.1.0/24"
    origin: "1.18.172.in-addr.arpa"
    filename: "sz/1.18.172.in-addr.arpa"
  bgo_transport03:
    cidr: "172.18.2.0/24"
    origin: "2.18.172.in-addr.arpa"
    filename: "sz/2.18.172.in-addr.arpa"
  bgo_transport04:
    cidr: "172.18.3.0/24"
    origin: "3.18.172.in-addr.arpa"
    filename: "sz/3.18.172.in-addr.arpa"
  bgo_transport05:
    cidr: "172.18.4.0/24"
    origin: "4.18.172.in-addr.arpa"
    filename: "sz/4.18.172.in-addr.arpa"
  bgo_transport06:
    cidr: "172.18.5.0/24"
    origin: "5.18.172.in-addr.arpa"
    filename: "sz/5.18.172.in-addr.arpa"
  bgo_transport07:
    cidr: "172.18.6.0/24"
    origin: "6.18.172.in-addr.arpa"
    filename: "sz/6.18.172.in-addr.arpa"
  bgo_transport08:
    cidr: "172.18.7.0/24"
    origin: "7.18.172.in-addr.arpa"
    filename: "sz/7.18.172.in-addr.arpa"
  bgo_public01:
    cidr: "158.39.74.0/24"
    origin: "74.39.158.in-addr.arpa"
    filename: "sz/74.39.158.in-addr.arpa"
  bgo_public02:
    cidr: "158.39.77.0/24"
    origin: "77.39.158.in-addr.arpa"
    filename: "sz/77.39.158.in-addr.arpa"
  bgo_ipv6:
    cidr: "2001:700:2:83ff::/64"
    origin: "f.f.3.8.2.0.0.0.0.0.7.0.1.0.0.2.ip6.arpa"
    filename: "sz/f.f.3.8.2.0.0.0.0.0.7.0.1.0.0.2.ip6.arpa"
