---
profile::base::common::manage_lvm: true

profile::base::lvm::physical_volume:
  '/dev/vdb':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_opt':
    physical_volumes:
      - /dev/vdb
profile::base::lvm::logical_volume:
  'lv_opt':
    volume_group: 'vg_opt'
    fs_type:      "xfs"
    mountpath:    "/opt/himlarcli"

netcfg_dns_server1:                       '172.16.32.10'
netcfg_dns_server2:                       '172.16.32.44'
