---
include:
  default:
    - profile::application::access
    - profile::webserver::apache
    - profile::openstack::openrc

# Selinux
profile::base::selinux::manage_selinux:         true

# Read only admin user
profile::openstack::openrc::username:           'access'
profile::openstack::openrc::password:           "%{hiera('access_api_password')}"
profile::openstack::openrc::project_name:       'services'

profile::base::network::manage_dummy:           true
profile::webserver::apache::manage_firewall:    false
profile::application::access::manage_firewall:  true
profile::application::access::package_url:      'https://download.iaas.uio.no/nrec/rpm/himlar-dp-prep-3.0-2.el8.x86_64.rpm' #FIXME
dpapp::installdir:        '/opt/dpapp'

profile::application::access::firewall_extras:
  source: "%{::network_trp1}/%{::netmask_trp1}"

apache::default_mods:   false
profile::webserver::apache::mods_enable:
  - wsgi
  - dir

apache::mod::wsgi::wsgi_python_home: "%{hiera('dpapp::installdir')}"
apache::mod::wsgi::package_name: 'python3.11-mod_wsgi'
apache::mod::wsgi::mod_path: "/usr/lib64/python3.11/site-packages/mod_wsgi/server/mod_wsgi-py311.cpython-311-x86_64-linux-gnu.so"

profile::base::common::packages:
  'python3.11': {}

profile::webserver::apache::vhosts:
  dpapp:
    vhost_name:         "%{hostname}.%{hiera('domain_trp')}"
    servername:         "%{hostname}.%{hiera('domain_trp')}"
    serveraliases:
     - "%{hiera('public__address__access')}"
     - "access-%{::location}.%{hiera('domain_frontend')}"
    port:               80
    manage_docroot:     false
    docroot:            '/var/www/html'
    wsgi_application_group:  '%%{}{GLOBAL}'
    wsgi_pass_authorization: 'on'
    wsgi_daemon_process:     'dpapp'
    wsgi_daemon_process_options:
      threads:      '4'
      python-path:  "%{hiera('dpapp::installdir')}/lib/python3.11/site-packages"
    wsgi_script_aliases:
      '/':   "%{hiera('dpapp::installdir')}/pyramid.wsgi"
    directories:
      - path:             "%{hiera('dpapp::installdir')}"
        require:          'all granted'
        custom_fragment:  'WSGIProcessGroup dpapp'

# Selinux for access
profile::base::selinux::boolean:
  'httpd_can_network_connect':
    ensure: 'on'
    persistent: true
  'httpd_tmp_exec':
    ensure: 'on'
    persistent: true
  'httpd_execmem':
    ensure: 'on'
    persistent: true
