---
include:
  default:
    - profile::application::access
    - profile::webserver::apache

profile::base::network::manage_dummy:           true
profile::base::firewall::purge_firewall:        true
profile::application::access::manage_firewall:  true
profile::application::access::package_url:      'https://download.iaas.uio.no/uh-iaas/rpm/himlar-dp-prep-1.4-1.el7.x86_64.rpm'
dpapp::installdir:        '/opt/dpapp'

apache::default_mods:   false
profile::webserver::apache::manage_firewall:  false
profile::webserver::apache::mods_enable:
  - wsgi
  - dir

profile::webserver::apache::vhosts:
  dpapp:
    vhost_name:         "%{hiera('public__address__access')}"
    servername:         "%{hiera('public__address__access')}"
    serveraliases:      [ "access-%{::location}.%{hiera('domain_frontend')}" ]
    port:               '80'
    manage_docroot:     false
    docroot:            '/var/www/html'
    redirect_dest:      "https://%{hiera('public__address__access')}/"
  dpapp_ssl:
    vhost_name:         "%{hiera('public__address__access')}"
    servername:         "%{hiera('public__address__access')}"
    serveraliases:      [ "access-%{::location}.%{hiera('domain_frontend')}" ]
    port:               '443'
    manage_docroot:     false
    docroot:            '/var/www/html'
    wsgi_application_group:  '%%{}{GLOBAL}'
    wsgi_pass_authorization: 'on'
    wsgi_daemon_process:     'dpapp'
    wsgi_daemon_process_options:
      threads:      '4'
      python-path:  "%{hiera('dpapp::installdir')}/lib/python2.7/site-packages"
    wsgi_script_aliases:
      '/':   "%{hiera('dpapp::installdir')}/pyramid.wsgi"
    directories:
      - path:             "%{hiera('dpapp::installdir')}"
        require:          'all granted'
        custom_fragment:  'WSGIProcessGroup dpapp'
    ssl:                  true
    ssl_ca:               "/etc/pki/tls/certs/cachain.pem"
    ssl_cert:             "/etc/pki/tls/certs/%{hiera('public__address__access')}.cert.pem"
    ssl_key:              "/etc/pki/tls/private/%{hiera('public__address__access')}.key.pem"
