---
include:
  default:
    - profile::application::foreman
    - profile::network::services
    - profile::webserver::apache
    - profile::dns::rndc_key

profile::dns::rndc_key::create_admin_key:    true
profile::dns::rndc_key::create_mdns_key:     false
profile::dns::rndc_key::host_is_bind_server: false

foreman_version: '3.8'

sensu__disk__warning:     80
sensu__disk__crtical:     90
sensu__memory__check:     "check-memory-percent.rb -w 85 -c 95"

profile::base::common::packages:
  'bash-completion': {}
  'bash-completion-extras': {}
  'python3.11-requests': {} # needed for ansible-forman
  'python3.11-pyyaml': {} # needed for ansible-foreman
  'ruby':
    ensure: '2.7'
    provider: 'dnfmodule'
    enable_only: true
  #  'foreman':
    #  ensure: "%{::os_platform}%{os_version}"
    #provider: 'dnfmodule'
    #enable_only: true
  'toml-rb':
    ensure: present
    provider: 'puppetserver_gem'

apache::mod::passenger::manage_repo: false

profile::application::foreman::manage_eyaml:    false
profile::application::foreman::manage_firewall: true
profile::application::foreman::manage_repo_dir: true
profile::application::foreman::manage_r10k:     false
profile::application::foreman::push_facts:      true

profile::network::services::manage_dns_records: true

# We need SCL repos
openstack_extras::repo::redhat::redhat::purge_unmanaged:  false

puppet::server:                        true
puppet::server_foreman_url:            "https://%{hiera('mgmt__address__foreman')}"
puppet::dns_alt_names:
  - "puppet.%{hiera('domain_mgmt')}"
  - "puppetca.%{hiera('domain_mgmt')}"
  - "admin.%{hiera('domain_mgmt')}"

profile::webserver::apache::manage_firewall:  false
profile::webserver::apache::vhosts:
  'repo':
    servername:     "%{hiera('mgmt__address__repo')}"
    port:           80
    docroot:        '/opt/repo/public'
    docroot_owner:  'iaas'
  'repo-oobip':
    servername:     "%{hiera('oob__address__repo')}"
    port:           80
    docroot:        '/opt/repo/public'
    docroot_owner:  'iaas'

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  foreman:
    ensure: present
  foreman-plugins:
    ensure: present
  puppetlabs:
    ensure: absent
  puppetlabs7:
    ensure: present

# Enable gem installation
profile::base::common::manage_gems: true
profile::base::common::gems:
  'ipaddress': {}

# (Some) admin nodes are connected to oob net
named_interfaces::config:
  mgmt:
    - eth0
  oob:
    - eth1

dhcp::pools:
  "out-of-band network definition":
    network: "%{hiera('netcfg_oob_netpart')}.0"
    mask: "%{hiera('netcfg_oob_netmask')}"
    gateway: "%{hiera('netcfg_oob_gateway')}"
    options:
      # iDRAC will search for file in order <servicetag>-config.json, <model>-config.json, config.json
      # examples: 4U1BGM7-config.json, R740xd-config.json, config.json
      # Refer to the zero-touch, bare metal server provisioning document from Dell for options.
      # The config is checked into internal git on login:/opt/repo/public, then use 'sync-admin.sh'
      # (located in that location) to push the files over to the local admin node
      - vendor-class-identifier "iDRAC"
      - idrac-provision-url "-i %{hiera('oob__address__repo')} -s http -t 500 -n %{::location}/"
    parameters:
      - set vendor-string = option vendor-class-identifier
      - default-lease-time 43200
      - max-lease-time 86400
    nameservers:
      - "%{hiera('netcfg_oob_netpart')}.10"
