---
include:
  default:
    - profile::application::foreman
    - profile::network::services
    - profile::webserver::apache

foreman_version: '3.8'

sensu__disk__warning:     80
sensu__disk__crtical:     90
sensu__memory__check:     "check-memory-percent.rb -w 85 -c 95"

profile::base::common::packages:
  'bash-completion': {}
  'bash-completion-extras': {}
  'python3-requests': {}
  'ruby':
    ensure: '2.7'
    provider: 'dnfmodule'
    enable_only: true
  'foreman':
    ensure: "%{::os_platform}%{os_version}"
    provider: 'dnfmodule'
    enable_only: true
  'toml-rb':
    ensure: present
    provider: 'puppetserver_gem'

apache::mod::passenger::manage_repo: false

profile::application::foreman::manage_eyaml:    false
profile::application::foreman::manage_firewall: true
profile::application::foreman::manage_repo_dir: true
profile::application::foreman::manage_r10k:     false
profile::application::foreman::push_facts:      true

# TODO: Move this up the hiera, it doesn't belong here.
profile::application::foreman::dhcp_classes:
  onie_dell_s3048:
    parameters:
      - 'match if (substring(option vendor-class-identifier, 0, 29) = "onie_vendor:x86_64-dell_s3000")'
      - "option default-url = \"http://repo.mgmt.%{location}.uhdc.no/images/cumuluslinux/onie-installer-amd64\""
  onie_dell_s4048:
    parameters:
      - 'match if (substring(option vendor-class-identifier, 0, 29) = "onie_vendor:x86_64-dell_s4000")'
      - "option default-url = \"http://repo.mgmt.%{location}.uhdc.no/images/cumuluslinux/onie-installer-amd64\""
  onie_dell_s4148:
    parameters:
      - 'match if (substring(option vendor-class-identifier, 0, 32) = "onie_vendor:x86_64-dellemc_s4100")'
      - "option default-url = \"http://repo.mgmt.%{location}.uhdc.no/images/cumuluslinux/onie-installer-amd64\""
  onie_dell_s4810:
    parameters:
      - 'match if (substring(option vendor-class-identifier, 0, 19) = "onie_vendor:powerpc")'
      - "option default-url = \"http://repo.mgmt.%{location}.uhdc.no/images/cumuluslinux/onie-installer-powerpc\""
  onie_edgecore_as4610:
    parameters:
      - 'match if (substring(option vendor-class-identifier, 0, 35) = "onie_vendor:arm-accton_as4610_54-r0")'
      - "option default-url = \"http://repo.mgmt.%{location}.uhdc.no/images/cumuluslinux/onie-installer-arm\""
  onie_dell_s5232f:
    parameters:
      - 'match if (substring(option vendor-class-identifier, 0, 33) = "onie_vendor:x86_64-dellemc_s5232f")'
      - "option default-url = \"http://repo.mgmt.%{location}.uhdc.no/images/cumuluslinux/onie-installer-amd64\""
  cumulus_s4810:
    parameters:
      - 'match if (substring(option host-name,0,7) = "cumulus")'
      - "option cumulus-provision-url \"http://repo.mgmt.%{location}.uhdc.no/provision/switch.sh\""
  opx_provision_vagrant:
    parameters:
      - 'match if (substring(option host-name,0,3) = "opx")'
      - "option ztd-provision-url \"http://repo.mgmt.%{location}.uhdc.no/provision/switch.sh\""
  opx_provision:
    parameters:
      - 'match if (substring(option host-name,0,3) = "OPX")'
      - "option ztd-provision-url \"http://repo.mgmt.%{location}.uhdc.no/provision/switch.sh\""

profile::network::services::manage_dns_records: true

# We need SCL repos
openstack_extras::repo::redhat::redhat::purge_unmanaged:  false

puppet::server:                        true
puppet::server_foreman_url:            "https://%{hiera('mgmt__address__foreman')}"
puppet::dns_alt_names:
  - "puppet.%{hiera('domain_mgmt')}"
  - "puppetca.%{hiera('domain_mgmt')}"
  - "admin.%{hiera('domain_mgmt')}"

profile::webserver::apache::manage_firewall:  false
profile::webserver::apache::vhosts:
  'repo':
    servername:     "%{hiera('mgmt__address__repo')}"
    port:           80
    docroot:        '/opt/repo/public'
    docroot_owner:  'iaas'

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  foreman:
    ensure: present
  foreman-plugins:
    ensure: present
  puppetlabs:
    ensure: absent
  puppetlabs7:
    ensure: present

# Enable gem installation
profile::base::common::manage_gems: true
profile::base::common::gems:
  'ipaddress': {}

# (Some) admin nodes are connected to oob net
named_interfaces::config:
  mgmt:
    - eth0
  oob:
    - eth1

