---
include:
  default:
    - profile::openstack::openrc
    - profile::logging::rsyslog::client
    - profile::webserver::apache
    - profile::application::builder

profile::base::common::packages:
  'python3-openstackclient': {}
  'python3-glanceclient': {}
  'packer': {}
  'python3': {}
  'qemu-img': {}
  'bash-completion': {}
  'bash-completion-extras': {}
  'jq': {}

named_interfaces::config:
  mgmt:
    - eth0

profile::base::lvm::physical_volume:
  '/dev/vdb':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_images':
    physical_volumes:
      - /dev/vdb
profile::base::lvm::logical_volume:
  'lv_images':
    volume_group: 'vg_images'
    fs_type:      "xfs"
    mountpath:    "/opt/images"

profile::webserver::apache::vhosts:
  'builds':
    servername:     "builder.%{hiera('domain_mgmt')}"
    ip:             "%{::ipaddress_mgmt1}"
    port:           80
    docroot:        '/opt/images/public_builds'
    docroot_owner:  'iaas'

profile::openstack::openrc::filename:         '/home/imagebuilder/openrc'
profile::openstack::openrc::username:         'imagebuilder'
profile::openstack::openrc::project_name:     'imagebuilder'
profile::openstack::openrc::password:         "%{hiera('imagebuilder_password')}"
profile::openstack::openrc::interface:        'public'


profile::application::builder::package_url:   "https://download.iaas.uio.no/nrec/nrec-internal/%{hiera('repo_dist')}/imagebuilder-1.26-1.el7.x86_64.rpm"
profile::application::builder::ipv6:          true
profile::application::builder::flavor:        'img.zerodisk'
profile::application::builder::template_dir:  '/etc/imagebuilder'
profile::application::builder::download_dir:  '/opt/images/public_builds'
profile::application::builder::rc_file:       '/home/imagebuilder/openrc'
profile::application::builder::images:
  'almalinux8':
    'image_name':       'IMAGEBUILDER AlmaLinux 8'
    'url':              'https://repo.almalinux.org/almalinux/8/cloud/x86_64/images/'
    'latest':           'AlmaLinux-8-GenericCloud-UEFI-latest.x86_64.qcow2'
    'checksum_file':    'CHECKSUM'
    'checksum':         'sha256'
    'min_ram':          768
    'min_disk':         8
    'flavor':           'm1.small'
    'efi':              true
    'username':         'almalinux'
    'hour':             13
    'minute':           30
  'almalinux9':
    'image_name':       'IMAGEBUILDER AlmaLinux 9'
    'url':              'https://repo.almalinux.org/almalinux/9/cloud/x86_64/images/'
    'latest':           'AlmaLinux-9-GenericCloud-latest.x86_64.qcow2'
    'checksum_file':    'CHECKSUM'
    'checksum':         'sha256'
    'min_ram':          1024
    'min_disk':         8
    'flavor':           'm1.small'
    'efi':              true
    'username':         'almalinux'
    'hour':             3
    'minute':           30
  'almalinux8_nv_vgpu':
    'image_name':       'IMAGEBUILDER AlmaLinux 8 (NVIDIA GPU)'
    'url':              'https://repo.almalinux.org/almalinux/8/cloud/x86_64/images/'
    'latest':           'AlmaLinux-8-GenericCloud-UEFI-latest.x86_64.qcow2'
    'checksum_file':    'CHECKSUM'
    'checksum':         'sha256'
    'min_ram':          768
    'min_disk':         8
    'flavor':           'm1.small'
    'efi':              true
    'username':         'almalinux'
    'environment':      [ 'IMAGEBUILDER_REPORT=true', 'IB_TEMPLATE_DIR=/etc/imagebuilder/nv_vgpu' ]
    'hour':             14
    'minute':           30
  'almalinux9_nv_vgpu':
    'image_name':       'IMAGEBUILDER AlmaLinux 9 (NVIDIA GPU)'
    'url':              'https://repo.almalinux.org/almalinux/9/cloud/x86_64/images/'
    'latest':           'AlmaLinux-9-GenericCloud-latest.x86_64.qcow2'
    'checksum_file':    'CHECKSUM'
    'checksum':         'sha256'
    'min_ram':          1024
    'min_disk':         8
    'flavor':           'm1.small'
    'efi':              true
    'username':         'almalinux'
    'environment':      [ 'IMAGEBUILDER_REPORT=true', 'IB_TEMPLATE_DIR=/etc/imagebuilder/nv_vgpu' ]
    'hour':             15
    'minute':           30
  'centos7':
    'image_name':       'IMAGEBUILDER CentOS 7'
    'url':              'http://cloud.centos.org/centos/7/images/'
    'latest':           'CentOS-7-x86_64-GenericCloud.qcow2'
    'min_ram':          768
    'min_disk':         8
    'username':         'centos'
    'hour':             2
    'minute':           30
  'centosstream8':
    'image_name':       'IMAGEBUILDER CentOS Stream 8'
    'url':              'https://cloud.centos.org/centos/8-stream/x86_64/images/'
    'latest':           'CentOS-Stream-GenericCloud-8-20220913.0.x86_64.qcow2'
    'checksum_file':    'CHECKSUM'
    'checksum':         'sha256'
    'min_ram':          768
    'min_disk':         8
    'username':         'centos'
    'hour':             4
    'minute':           30
  'centosstream9':
    'image_name':       'IMAGEBUILDER CentOS Stream 9'
    'url':              'https://cloud.centos.org/centos/9-stream/x86_64/images/'
    'latest':           'CentOS-Stream-GenericCloud-9-20230123.0.x86_64.qcow2'
    'checksum_file':    'CentOS-Stream-GenericCloud-9-20230123.0.x86_64.qcow2.SHA256SUM'
    'checksum':         'sha256'
    'min_ram':          768
    'min_disk':         8
    'username':         'cloud-user'
    'hour':             6
    'minute':           30
  'debian10':
    'image_name':       'IMAGEBUILDER Debian 10'
    'url':              'http://cdimage.debian.org/cdimage/openstack/current-10/'
    'latest':           'debian-10-openstack-amd64.qcow2'
    'checksum_file':    'SHA256SUMS'
    'checksum':         'sha256'
    'min_ram':          768
    'min_disk':         3
    'username':         'debian'
    'hour':             6
  'debian11':
    'image_name':       'IMAGEBUILDER Debian 11'
    'url':              'https://cdimage.debian.org/cdimage/cloud/bullseye/latest/'
    'latest':           'debian-11-generic-amd64.qcow2'
    'checksum_file':    'SHA512SUMS'
    'checksum':         'sha512'
    'min_ram':          768
    'min_disk':         3
    'flavor':           'm1.small'
    'efi':              true
    'username':         'debian'
    'hour':             16
    'minute':           30
  'fedora_37':
    'image_name':       'IMAGEBUILDER Fedora 37'
    'url':              'https://www.mirrorservice.org/sites/dl.fedoraproject.org/pub/fedora/linux/releases/37/Cloud/x86_64/images/'
    'latest':           'Fedora-Cloud-Base-37-1.7.x86_64.qcow2'
    'checksum_file':    'Fedora-Cloud-37-1.7-x86_64-CHECKSUM'
    'checksum':         'sha256'
    'min_ram':          1024
    'min_disk':         3
    'username':         'fedora'
    'hour':             6
    'minute':           10
  'rockylinux8':
    'image_name':       'IMAGEBUILDER RockyLinux 8'
    'url':              'https://dl.rockylinux.org/pub/rocky/8/images/x86_64/'
    'latest':           'Rocky-8-GenericCloud.latest.x86_64.qcow2'
    'checksum_file':    'Rocky-8-GenericCloud.latest.x86_64.qcow2.CHECKSUM'
    'checksum':         'sha256'
    'min_ram':          768
    'min_disk':         8
    'username':         'rocky'
    'hour':             18
    'minute':           30
  'rockylinux9':
    'image_name':       'IMAGEBUILDER RockyLinux 9'
    'url':              'https://dl.rockylinux.org/pub/rocky/9/images/x86_64/'
    'latest':           'Rocky-9-GenericCloud.latest.x86_64.qcow2'
    'checksum_file':    'Rocky-9-GenericCloud.latest.x86_64.qcow2.CHECKSUM'
    'checksum':         'sha256'
    'min_ram':          768
    'min_disk':         8
    'efi':              true
    'username':         'rocky'
    'hour':             18
  'ubuntu_2004':
    'image_name':       'IMAGEBUILDER Ubuntu 20.04'
    'url':              'https://cloud-images.ubuntu.com/focal/current/'
    'latest':           'focal-server-cloudimg-amd64.img'
    'checksum_file':    'SHA256SUMS'
    'checksum':         'sha256'
    'min_ram':          768
    'min_disk':         3
    'username':         'ubuntu'
    'hour':             9
  'ubuntu_2004_nv_vgpu':
    'image_name':       'IMAGEBUILDER Ubuntu 20.04 (NVIDIA VGPU)'
    'url':              'https://cloud-images.ubuntu.com/focal/current/'
    'latest':           'focal-server-cloudimg-amd64.img'
    'checksum_file':    'SHA256SUMS'
    'checksum':         'sha256'
    'min_ram':          768
    'min_disk':         8
    'username':         'ubuntu'
    'flavor':           'm1.small'
    'environment':      [ 'IMAGEBUILDER_REPORT=true', 'IB_TEMPLATE_DIR=/etc/imagebuilder/nv_vgpu' ]
    'hour':             10
  'ubuntu_2204':
    'image_name':       'IMAGEBUILDER Ubuntu 22.04'
    'url':              'https://cloud-images.ubuntu.com/jammy/current/'
    'latest':           'jammy-server-cloudimg-amd64.img'
    'checksum_file':    'SHA256SUMS'
    'checksum':         'sha256'
    'min_ram':          768
    'min_disk':         3
    'username':         'ubuntu'
    'hour':             9
    'minute':           30
  'ubuntu_2204_nv_vgpu':
    'image_name':       'IMAGEBUILDER Ubuntu 22.04 (NVIDIA GPU)'
    'url':              'https://cloud-images.ubuntu.com/jammy/current/'
    'latest':           'jammy-server-cloudimg-amd64.img'
    'checksum_file':    'SHA256SUMS'
    'checksum':         'sha256'
    'min_ram':          768
    'min_disk':         8
    'username':         'ubuntu'
    'flavor':           'm1.small'
    'environment':      [ 'IMAGEBUILDER_REPORT=true', 'IB_TEMPLATE_DIR=/etc/imagebuilder/nv_vgpu' ]
    'hour':             9
    'minute':           30
  'uio_rhel7':
    'image_name':       'IMAGEBUILDER UIO RHEL 7'
    'url':              'http://download.iaas.uio.no/uh-iaas/nonfree/'
    'latest':           'rhel-server-7.9-x86_64-kvm.qcow2'
    'checksum_file':    'rhel-server-7.9-x86_64-kvm.sha256sum'
    'checksum':         'sha256'
    'min_ram':          1024
    'min_disk':         8
    'username':         'cloud-user'
    'hour':             11
  'uio_rhel8':
    'image_name':       'IMAGEBUILDER UIO RHEL 8'
    'url':              'http://download.iaas.uio.no/uh-iaas/nonfree/'
    'latest':           'rhel-8.7-x86_64-kvm.qcow2'
    'checksum_file':    'rhel-8.7-x86_64-kvm.sha256sum'
    'checksum':         'sha256'
    'min_ram':          1024
    'min_disk':         8
    'username':         'cloud-user'
    'hour':             12
  'uio_rhel9':
    'image_name':       'IMAGEBUILDER UIO RHEL 9'
    'url':              'http://download.iaas.uio.no/uh-iaas/nonfree/'
    'latest':           'rhel-baseos-9.1-x86_64-kvm.qcow2'
    'checksum_file':    'rhel-baseos-9.1-x86_64-kvm.sha256sum'
    'checksum':         'sha256'
    'min_ram':          1024
    'min_disk':         8
    'username':         'cloud-user'
    'hour':             13

profile::application::builder::templates:
  'default':
    custom_scripts:     ["%{profile::application::builder::custom_scriptdir}/resolver.sh"]
  'nv_vgpu':
    custom_scripts:     ['/opt/imagebuilder/scripts/nvidia-grid-driver.sh']

# Sensu
profile::monitoring::sensu::agent::plugin_gems:
  sensu-plugins-himlar:
    ensure:       '0.6.0'
    provider:     'sensuclassic_gem'
    source:       'http://download.iaas.uio.no/uh-iaas/gem'

# metadata imagebuild check
profile::monitoring::sensu::agent::expanded_checks:
  - 'almalinux8'
#  - 'almalinux8_nv_vgpu'
  - 'almalinux9'
  - 'centos7'
  - 'centosstream8'
  - 'centosstream9'
  - 'debian10'
  - 'debian11'
  - 'fedora_36'
  - 'rockylinux8'
  - 'rockylinux9'
  - 'ubuntu_1804'
  - 'ubuntu_2004'
  - 'ubuntu_2004_nv_vgpu'
  - 'ubuntu_2204'
  - 'uio_rhel7'
  - 'uio_rhel8'
  - 'uio_rhel9'

profile::monitoring::sensu::agent::expanded_defaults:
    command: "check-imagebuild.rb -d "
    interval:     600
    subscribers:  ['checks']

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present
  epel:
    ensure: present
    includepkgs: 'bash-completion-extras htop inotify-tools python-dogpile-core python-linecache2 python2-mimeparse python2-msgpack python2-pbr python34 python34-libs'

# Turn on agant and add common sensu plugins
profile::monitoring::sensu::agent::enable_agent: true
# profile::monitoring::sensu::agent::plugins:
#   sensu-plugins-logs:
#     type:         package

# # metadata check
# profile::monitoring::sensu::agent::checks:
#   'check-log':
#     command:      "sudo /opt/sensu/embedded/bin/check-log.rb -f /var/log/cron -w 1 -c 1 -q 'imagebuilder: Failed building' -r"
#     interval:     60
#     auto_resolve: false
#     handlers:     'slack'
#     subscribers:  ['checks']

# sensu
sensu__disk__warning:     85
sensu__disk__crtical:     95

sudo::configs:
  sensu_tty:
    priority:   15
    content:    'Defaults:sensu !requiretty'
  sensu:
    priority:   20
    content:    'sensu ALL = (root) NOPASSWD: /opt/sensu/embedded/bin/check-log.rb'

profile::monitoring::sensu::agent::checks:
  'check-log':
    command:      cat /var/log/imagebuilder/*-report.jsonl | jq -r 'select(.result) | .result'
    interval:     60
    auto_resolve: false
    subscribers:  ['checks']
