---
# collectd
include:
  default:
    - profile::monitoring::collectd

named_interfaces::config:
  mgmt:
    - em1
  trp:
    - team1
  live:
    - team1.120

# Turn off nested virtualization
profile::virtualization::nested::manage: false

profile::monitoring::collectd::enable: false

collectd::plugin::interface::interfaces:
  - "%{::interface_trp1}"
  - "%{::interface_mgmt1}"

profile::monitoring::collectd::plugins:
  - collectd::plugin::aggregation
  - collectd::plugin::cpu
  - collectd::plugin::disk
  - collectd::plugin::load
  - collectd::plugin::memory
  - collectd::plugin::interface
  - collectd::plugin::write_graphite
  - collectd::plugin::virt
  - collectd::plugin::processes
  - collectd::plugin::numa
collectd::plugin::virt::hostname_format:        'hostname'
collectd::plugin::virt::plugin_instance_format: 'uuid'

# Nova overrides
nova::compute::libvirt::cpu_models:              ['EPYC']
nova::cpu_allocation_ratio:                      '8'
nova::disk_allocation_ratio:                     '1'
nova::ram_allocation_ratio:                      '1.2'
nova::scheduler::filter::max_instances_per_host: '20'

# Create and enable more swap
profile::base::common::extraswap:        true
profile::base::common::extraswap_sizegb: 30

profile::base::lvm::physical_volume:
  '/dev/sda4':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_ext':
    physical_volumes:
      - /dev/sda4
profile::base::lvm::logical_volume:
  'lv_instances':
    volume_group: 'vg_ext'
    fs_type:      "xfs"
    mountpath:    "/var/lib/nova/instances"

# These compute host uses local storage for instances
nova::compute::rbd::ephemeral_storage: false

# Configuration items not explicitly supported by the Puppet module
nova::config::nova_config:
  DEFAULT/metadata_workers:
    value: '2'

nova::compute::libvirt::images_type: 'default'
