---
#
# Common vgpu settings
#

# Create and enable more swap
profile::base::common::extraswap:         true
profile::base::common::extraswap_sizegb:  10

# Nover overrides
#
# vgpu requirements: 32 GB, 4 vCPU, 20 GB per vGPU installed
#
nova::cpu_allocation_ratio:               4
nova::disk_allocation_ratio:              2
nova::ram_allocation_ratio:               1.2
