---
include:
  default:
    - profile::virtualization::libvirt
    - profile::bootstrap::himlar
    - profile::network::services

named_interfaces::config:
  mgmt:
     - br0
  trp:
     - br1

calico::compute::manage_dhcp_agent: false
calico::compute::manage_metadata_service: false
calico::compute::felix_enable: false
calico::compute::manage_qemu_settings: false
calico::compute::bird_template: 'profile/bird/bird.conf.erb'

libvirt::qemu_user: 'root'
libvirt::qemu_group: 'root'

profile::base::common::manage_lvm: true
profile::base::common::packages:
  'bridge-utils': {}
  'bash-completion': {}
  'bash-completion-extras': {}
  'jq': {}

profile::virtualization::libvirt::manage_firewall: true
profile::virtualization::libvirt::firewall_extras:
  'graphics':
    port: 5900-5999

profile::network::services::ntp_server: true

profile::virtualization::libvirt::networks:
  directnet:
    ensure:              enabled
    autostart:           true
    forward_mode:        bridge
    bridge:              br0
  trpnet:
    ensure:              enabled
    autostart:           true
    forward_mode:        bridge
    bridge:              br1

profile::virtualization::libvirt::pools:
  dirpool:
    ensure:              present
    autostart:           true
    type:                dir
    target:              /var/lib/libvirt/images

libvirt::unix_sock_group:         wheel
libvirt::unix_sock_rw_perms:      0770
libvirt::listen_tls:              false
libvirt::listen_tcp:              true
libvirt::auth_tcp:                none
libvirt::sysconfig:
  LIBVIRTD_ARGS:                  '--listen'
libvirt::qemu_vnc_listen:         '0.0.0.0'
libvirt::qemu_vnc_sasl:           false
libvirt::qemu_vnc_tls:            false

lvm::volume_groups:
  vg_ext:
    physical_volumes:
      - /dev/sda3
    logical_volumes:
      lv_ext:
        fs_type:   xfs
        mountpath: "/var/lib/libvirt/images"

consul::config_hash:
  'server': true
  'ui_dir': '/opt/consul/ui'
  'ports':
    'https': '8550'
