---
include:
  default:
    - profile::openstack::image
    - profile::openstack::openrc
    - profile::logging::rsyslog::client

profile::base::common::packages:
  'bash-completion': {}
  'bash-completion-extras': {}
  'jq': {}
  'openstack-selinux': {}

profile::base::selinux::manage_selinux:       false
profile::openstack::image::registry_enabled:  true
profile::openstack::image::manage_policy:     true
profile::openstack::image::manage_notify:     true

profile::openstack::openrc::password:     "%{hiera('glance_api_password')}"
profile::openstack::openrc::username:     'glance'
profile::openstack::openrc::project_name: 'services'

openstack_version: 'ocata' #FIXME

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present
  ceph-%{hiera('ceph_version')}:
    ensure: present
  epel: # should be absent when using RDO, but whitelist can also work
    ensure:   present
    includepkgs: 'htop bash-completion-extras'

# Image nodes need only glance key
ceph::profile::params::client_keys:
  'client.glance':
    secret: "%{hiera('client_glance::secret')}"
    mode: '0600'
    user: 'glance'
    group: 'glance'
    cap_mon: 'profile rbd'
    cap_osd: 'profile rbd pool=images'

profile::base::selinux::boolean:
  'glance_api_can_network':
    ensure: 'on'
    persistent: true
