---
include:
  default:
    - profile::openstack::image
    - profile::openstack::openrc
    - profile::logging::rsyslog::client
    - profile::openstack::cache
    - profile::storage::cephclient

openstack_version: 'xena'

profile::base::common::packages:
  # we need newer version of six to avoid breaking requests and openstack cli
  'python3-six.noarch': { ensure: latest }
  'bash-completion': {}
  'bash-completion-extras': {}
  'jq': {}
  'openstack-selinux': {}
  'python-memcached': {}
  'python3-sqlalchemy':
    source: 'https://download.iaas.uio.no/nrec/test/el8/rdo-xena/Packages/p/python3-sqlalchemy-1.4.18-1.1.el8.x86_64.rpm'

profile::base::selinux::manage_selinux:       true
profile::openstack::image::manage_policy:     true
profile::openstack::image::manage_notify:     true

profile::openstack::image::api::create_glance_stores: true

profile::openstack::openrc::password:     "%{hiera('glance_api_password')}"
profile::openstack::openrc::username:     'glance'
profile::openstack::openrc::project_name: 'services'

# Default file store when other backends are not defined for location
glance::api::enabled_backends:
  - 'files:file'
glance::api::default_backend: 'files'

memcached::max_memory: '20%'

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present
  ceph-%{hiera('ceph_version')}:
    ensure: present
  ceph-%{hiera('ceph_version')}-noarch:
    ensure: present
  CentOS-PowerTools: # FIXME: remove when CentOS 8 is gone
    ensure: present
  AlmaLinux-PowerTools:
    ensure: present
  epel: # should be absent when using RDO, but whitelist can also work
    ensure:   present
    includepkgs: 'thrift htop bash-completion-extras lttng-ust userspace-rcu libbabeltrace leveldb liboath fmt python3-cherrypy python3-zc-lockfile python3-portend python3-cheroot python3-trustme python3-tempora python3-jaraco-functools python3-jaraco'
    #includepkgs: 'htop bash-completion-extras lttng-ust userspace-rcu libbabeltrace leveldb liboath py-bcrypt python2-bcrypt python36-prettytable python36-requests python36-pyOpenSSL python36-bcrypt python36-six python36-PyYAML python36-dateutil python36-cryptography python36-urllib3 python36-chardet python36-cffi python36-idna python36-pysocks python36-pycparser python36-ply python36-asn1crypto python3-httplib2 fmt python3-cherrypy python3-zc-lockfile python3-portend python3-cheroot python3-trustme python3-tempora python3-jaraco-functools python3-jaraco'

# Image nodes need only glance key
ceph::profile::params::client_keys:
  'client.glance':
    secret: "%{hiera('ceph_storage_client_glance_key')}"
    mode: '0600'
    user: 'glance'
    group: 'glance'
    cap_mon: 'profile rbd'
    cap_osd: 'profile rbd pool=images'

profile::base::selinux::boolean:
  'glance_api_can_network':
    ensure: 'on'
    persistent: true

profile::base::selinux::semodules:
  'postfix_glance':
    avc_file:   "postfix_glance.avc"

profile::storage::cephclient::enable: true
