---
include:
  default:
    - profile::base::login
    - profile::network::services
    - profile::application::git
    - foreman_bootstrap::instances

profile::base::firewall::manage_firewall: false
profile::network::services::manage_nat: true

accounts::accounts:
  'beddari':
    ensure: present
  'ebm':
    ensure: present
  'hege':
    ensure: present
    authorized_keys: [ 'hege_usit', 'hege_home' ]
  'knutvi':
    ensure: present
  'kyrreli':
    ensure: present
  'mikaeld':
    ensure: present
  'raymond':
    ensure: present
  'torldre':
    ensure: present
  'trondham':
    ensure: present
  # disable system users
  'iaas':
    ensure: absent
  'vagrant':
    ensure: absent

ssh::server::options:
  # Need this for 2FA (saz-ssh-module disables by default)
  ChallengeResponseAuthentication: 'yes'
  # The second publickey is until the pam files are fixed
  AuthenticationMethods: 'publickey,keyboard-interactive:pam publickey'
  # Explicitly enable the required methods
  UsePAM: 'yes'
  PasswordAuthentication: 'yes'
  PubKeyAuthentication: 'yes'

googleauthenticator::pam::mode::modes:
  wheel-only:
    condition: 'user ingroup wheel'
    nullok: true

googleauthenticator::pam::modules:
  sshd:
    mode: wheel-only

profile::application::git::settings:
  hostname:     "git.%{::domain}"
  upstream:     'enable'
  mirroring:    'enable'
  site_info:    'Please see http://iaas.readthedocs.org for more info'
