---
include:
  kickstart:
    - profile::application::git
  default:
    - profile::base::login
    - profile::development::network::dns
    - profile::application::git
    - profile::application::rngd
    - profile::bootstrap::himlar
    - profile::network::nat
    - profile::application::postfix
    - profile::logging::rsyslog::client

# We need to define oob for login, but this should be overridden in location
# with the correct oob interface where we use oob network
named_interfaces::config:
  mgmt:
    - eth0
  trp:
    - eth1
  oob:
    - eth0

profile::application::rngd::enable:               true
profile::base::firewall::manage_firewall:         true
profile::network::nat::enable_masquerade:         true
profile::network::nat::source:                   "0.0.0.0/0"
profile::network::nat::outiface:                 "%{::interface_public1}"
profile::development::network::dns::manage_hosts: true
profile::development::network::dns::use_dnsmasq:  true

profile::firewall::pre::ssh_settings:
  source: "0.0.0.0/0"

profile::base::login::manage_repo_incoming_dir:   true
profile::base::login::gpg_receiver:              "%{hiera('gpg_receiver')}"
profile::base::login::manage_firewall:           "%{hiera('profile::base::firewall::manage_firewall')}"
profile::base::login::manage_dnsmasq:             true

accounts::accounts:
#  'hege':
#    ensure: present
#    authorized_keys: [ 'hege_usit', 'hege_home' ]
#  'kolbu':
#    ensure: present
  'mikaeld':
    ensure: present
  'raymond':
    ensure: present
    authorized_keys: [ 'raymond_uib', 'raymond_home']
  'trondham':
    ensure: present
  'erikberg':
    ensure: present
  'sjurher':
    ensure: present
  'lennart':
    ensure: present
    authorized_keys: [ 'lennart_uib', 'lennart_home']
  'terjef':
    ensure: present
  'torldre':
    ensure: present
  'erlenboh':
    ensure: present
  'ivarth':
    ensure: present
  # system user for db backup
  'norcams':
    ensure: present
  # disable system users
  'iaas':
    ensure: absent
  'vagrant':
    ensure: absent



# special user for common files which should be synced between locations (can not be owned by root)
accounts::users:
  'norcams':
    shell: '/bin/false'

# Sensu (login has larger disks)
sensu__disk__warning:     85
sensu__disk__crtical:     95

#openstack_extras::repo::redhat::redhat::manage_rdo: true
profile::base::common::packages:
  'bash-completion': {}
  'bash-completion-extras': {}
  'jq': {}
#  'python-oslo-log': {}
  'python3': {}
  'python3-virtualenv': {} # used for ca_setup
  'rsync': {}              # used for repository sync between login nodes
  'ansible': {}

ssh::server::options:
  # Need this for 2FA (saz-ssh-module disables by default)
  ChallengeResponseAuthentication: 'yes'
  # The second publickey is until the pam files are fixed
  AuthenticationMethods: 'publickey,keyboard-interactive:pam'
  # Explicitly enable the required methods
  UsePAM: 'yes'
  PasswordAuthentication: 'no'
  PubKeyAuthentication: 'yes'
  # OpenSSH hardening - removing unwanted chipers. Based on
  #   https://infosec.mozilla.org/guidelines/openssh
  # Modern and with NIST curves removed
  # Revision: 2021-06-22
  HostKeyAlgorithms: 'ssh-ed25519,ssh-rsa'
  KexAlgorithms: 'curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256'
  Ciphers: 'chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes128-ctr'
  MACs: 'hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com'

profile::base::common::users_ssh_options:
  'git':
    'options':
      'Host bgo':
        'User':     'git'
        'Hostname': 'git.iaas.uib.no'
      'Host bgo2':
        'User':     'git'
        'Hostname': 'bgo-login-02.iaas.uib.no'
      'Host osl':
        'User':     'git'
        'Hostname': 'git.iaas.uio.no'
      'Host osl2':
        'User':     'git'
        'Hostname': 'osl-login-02.iaas.uio.no'

googleauthenticator::pam::mode::modes:
  wheel-only:
    condition: 'user ingroup wheel'
    nullok: false
    service: 'sshd'

googleauthenticator::pam::modules:
  sshd:
    mode: wheel-only

profile::application::git::settings:
  hostname:     "git.%{::domain}"
  upstream:     'enable'
  mirroring:    'enable'
  site_info:    'Please see http://iaas.readthedocs.org for more info'

profile::base::yumrepo::repo_hash:
  # Enable extra yum repo
  epel:
    ensure: present
  # on login node we must actually use dnsmasq from Appstream as Calico repo not available
  AlmaLinux-AppStream:
    exclude:        'postgres*'

profile::base::login::dump_owner:      'norcams'
profile::base::login::dump_group:      'wheel'

# DB backup cron jobs
profile::base::login::db_servers:
  "%{::location}-db-global-01":
    hour:     '*'
    minute:   '20'
    command:  "/usr/local/sbin/db-dump.sh %{::location}-db-global-01 >/dev/null"
  "%{::location}-db-regional-01":
    hour:     '*'
    minute:   '30'
    command:  "/usr/local/sbin/db-dump.sh %{::location}-db-regional-01 >/dev/null"
  "%{::location}-metric-01":
    hour:     '*'
    minute:   '40'
    command:  "/usr/local/sbin/db-dump.sh %{::location}-metric-01 >/dev/null"
  "%{::location}-db-archival":
    hour:     '0'
    minute:   '00'
    weekday:  'Monday'
    command:  "/usr/local/sbin/db-longterm-bck.sh -e %{::location} >/dev/null"

