---
include:
  default:
    - profile::base::login
    - profile::network::services
    - profile::application::git
    - profile::bootstrap::himlar
    - profile::network::nat

profile::base::login::manage_rngd:        true

# Manage NAT with iptables
profile::base::firewall::manage_firewall:     true
profile::network::services::manage_nat:       false
profile::network::nat::enable_masquerade:     true
profile::network::nat::source:                "0.0.0.0/0"

profile::firewall::pre::ssh_settings:
  source: "0.0.0.0/0"

profile::base::login::manage_repo_incoming_dir: true
profile::base::login::gpg_receiver:             "%{hiera('gpg_receiver')}"

accounts::accounts:
#  'hege':
#    ensure: present
#    authorized_keys: [ 'hege_usit', 'hege_home' ]
#  'kolbu':
#    ensure: present
  'mikaeld':
    ensure: present
  'raymond':
    ensure: present
  'torldre':
    ensure: present
  'trondham':
    ensure: present
#  'jarleb':
#    ensure: present
  'andersv':
    ensure: present
  # disable system users
  'iaas':
    ensure: absent
  'vagrant':
    ensure: absent
  'norcams':
    ensure: present
  'tannazn':
    ensure: present


# special user for common files which should be synced between locations (can not be owned by root)
accounts::users:
  'norcams':
    shell: '/bin/false'

#openstack_extras::repo::redhat::redhat::manage_rdo: true
profile::base::common::packages:
  'python-openstackclient': {}
  'bash-completion': {}
  'bash-completion-extras': {}
  'jq': {}
  'rng-tools': {}
#  'python-oslo-log': {}

ssh::server::options:
  # Need this for 2FA (saz-ssh-module disables by default)
  ChallengeResponseAuthentication: 'yes'
  # The second publickey is until the pam files are fixed
  AuthenticationMethods: 'publickey,keyboard-interactive:pam'
  # Explicitly enable the required methods
  UsePAM: 'yes'
  PasswordAuthentication: 'no'
  PubKeyAuthentication: 'yes'

googleauthenticator::pam::mode::modes:
  wheel-only:
    condition: 'user ingroup wheel'
    nullok: false

googleauthenticator::pam::modules:
  sshd:
    mode: wheel-only

profile::application::git::settings:
  hostname:     "git.%{::domain}"
  upstream:     'enable'
  mirroring:    'enable'
  site_info:    'Please see http://iaas.readthedocs.org for more info'

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present

profile::base::login::manage_db_backup: true
profile::base::login::dump_owner:      'norcams'
profile::base::login::dump_group:      'wheel'
