---
include:
  default:
    - profile::messaging::rabbitmq
    - profile::logging::rsyslog::client

profile::messaging::rabbitmq::manage_rsyslog: true

# Sensu
profile::base::common::packages:
  'gcc-c++': {}
  'make': {}
  'bash-completion': {}
  'bash-completion-extras': {}
  'jq': {}


profile::monitoring::sensu::agent::plugins:
  sensu-plugins-rabbitmq:
    type:         package
    pkg_version:  '4.1.1'

profile::monitoring::sensu::agent::checks:
  'metrics-rabbitmq-overview':
    type:         'metric'
    command:      "metrics-rabbitmq-overview.rb --scheme mq.%{::hostname} --user local --password %{hiera('local_rabbit_password')}"
    interval:     60
    subscribers:  ['metrics']
    handlers:     ['graphite_tcp']
  'metrics-rabbitmq-queue':
    type:         'metric'
    command:      "metrics-rabbitmq-queue.rb --scheme mq.%{::hostname} --user local --password %{hiera('local_rabbit_password')}"
    interval:     60
    subscribers:  ['metrics']
    handlers:     ['graphite_tcp']
  'metrics-rabbitmq-exchange':
    type:         'metric'
    command:      "metrics-rabbitmq-exchange.rb --scheme mq.%{::hostname} --user local --password %{hiera('local_rabbit_password')}"
    interval:     60
    subscribers:  ['metrics']
    handlers:     ['graphite_tcp']

profile::messaging::rabbitmq::users:
  nova:
    password: "%{hiera('nova::rabbit_password')}"
  cinder:
    password: "%{hiera('cinder::rabbit_password')}"
  neutron:
    password: "%{hiera('neutron::rabbit_password')}"
  sensu:
    password: "%{hiera('sensu::rabbit_password')}"
  local:
    password: "%{hiera('local_rabbit_password')}"
    tags:     'monitoring'
  ceilometer:
    password: "%{hiera('ceilometer_rabbit_password')}"
  himlarcli:
    password: "%{hiera('himlarcli_rabbit_password')}"
  access:
    password: "%{hiera('access_rabbit_password')}"
#  glance:
#    password: "%{hiera('glance::rabbit_password')}"

profile::messaging::rabbitmq::vhosts:
  nova: {}
  cinder: {}
  neutron: {}
  sensu: {}
  ceilometer: {}
  himlarcli: {}
#  glance: {}

profile::messaging::rabbitmq::user_permissions:
  'nova@nova':
    configure_permission: '.*'
    write_permission:     '.*'
    read_permission:      '.*'
  'cinder@cinder':
    configure_permission: '.*'
    write_permission:     '.*'
    read_permission:      '.*'
  'neutron@neutron':
    configure_permission: '.*'
    write_permission:     '.*'
    read_permission:      '.*'
  'sensu@sensu':
    configure_permission: '.*'
    write_permission:     '.*'
    read_permission:      '.*'
  'ceilometer@ceilometer':
    configure_permission: '.*'
    write_permission:     '.*'
    read_permission:      '.*'
  'himlarcli@himlarcli':
    configure_permission: '.*'
    write_permission:     '.*'
    read_permission:      '.*'
  'access@himlarcli':
    configure_permission: '.*'
    write_permission:     '.*'
    read_permission:      '.*'
#  'glance@glance':
#    configure_permission: '.*'
#    write_permission:     '.*'
#    read_permission:      '.*'
  # mgmt access for sensu and rabbitmqadmin dashboard
  'local@nova':
    read_permission:      '.*'
  'local@cinder':
    read_permission:      '.*'
  'local@neutron':
    read_permission:      '.*'
  'local@sensu':
    read_permission:      '.*'
  'local@ceilometer':
    read_permission:      '.*'
  'local@himlarcli':
    read_permission:      '.*'

profile::messaging::rabbitmq::policy:
  ha-all@nova:
    pattern:                '.*'
    priority:               0
    applyto:                'all'
    definition:
      'ha-mode':            'all'
      'ha-sync-mode':       'automatic'
