---
named_interfaces::config:
  mgmt:
     - vtnet0
  trp:
     - vtnet1
  public:
     - tap0

include:
  default:
    - profile::network::nat

bsd::network::v4forwarding: true

profile::base::network::net_ifnames:             false
profile::base::common::manage_keyboard:          false
profile::base::common::manage_yumrepo:           false
profile::base::common::manage_packages:          false
profile::monitoring::sensu::agent::enable_agent: false
