---
include:
  default:
    - profile::network::nat
    - profile::logging::rsyslog::client
    - profile::monitoring::collectd

named_interfaces::config:
  mgmt:
    - eth0
  trp:
    - eth1
  public:
    - dummy0

profile::base::network::manage_dummy:            true # FIXME: Remove when el7 is gone
profile::network::interface::manage_dummy:       true

profile::network::nat::enable_bird:              true
profile::network::nat::manage_bird_firewall:     true
profile::network::nat::enable_snat:              true
profile::network::nat::outiface:                 "%{::interface_trp1}"
profile::network::nat::source:                   "!%{::ipaddress_trp1}"

profile::monitoring::sensu::agent::enable_agent: true

# collectd
collectd::plugin::interface::interfaces:
  - "%{::interface_trp1}"
  - "%{::interface_mgmt1}"

profile::monitoring::collectd::plugins:
  - collectd::plugin::aggregation
  - collectd::plugin::cpu
#  - collectd::plugin::load
  - collectd::plugin::memory
  - collectd::plugin::interface
  - collectd::plugin::write_graphite

