---
include:
  default:
    - profile::network::nat
    - profile::logging::rsyslog::client

named_interfaces::config:
  mgmt:
    - eth0
  trp:
    - eth1
  public:
    - dummy0

profile::base::network::manage_dummy:            true # FIXME: Remove when el7 is gone
profile::network::interface::manage_dummy:       true

profile::network::nat::enable_bird:              true
profile::network::nat::manage_bird_firewall:     true
profile::network::nat::enable_snat:              true
profile::network::nat::outiface:                 "%{::interface_trp1}"
profile::network::nat::source:                   "!%{::ipaddress_trp1}"

profile::monitoring::sensu::agent::enable_agent: true
