---
include:
  default:
    - profile::openstack::network::controller
    - profile::openstack::resource::createnetworks
    - profile::application::etcd
    - profile::openstack::openrc
    - profile::logging::rsyslog::client

openstack_version: 'ocata' # FIXME

etcd::proxy: "off"
etcd::initial_cluster_state: 'new'
etcd::initial_cluster_token: 'etcd-cluster'

calico::controller: true

profile::openstack::network::manage_quotas: true

profile::base::common::packages:
  'bash-completion': {}
  'bash-completion-extras': {}
  'jq': {}
  'gcc-c++': {}
  'openstack-selinux': {}

profile::openstack::openrc::password:     "%{hiera('neutron_api_password')}"
profile::openstack::openrc::username:     'neutron'
profile::openstack::openrc::project_name: 'services'

profile::openstack::network::controller::neutron_config:
  nova/endpoint_type:
    value:  'internal'

profile::openstack::network::policies:
  create_network:
    key:   'create_network'
    value: 'rule:admin_only'
  create_router:
    key:   'create_router'
    value: 'rule:admin_only'

# Sensu (needs gcc-c++)
profile::monitoring::sensu::agent::plugins:
  sensu-plugins-http:
    type:         package
    pkg_version:  '2.8.4'

profile::monitoring::sensu::agent::checks:
  'etcd-client-health':
    command:      "check-http.rb -u http://127.0.0.1:2379/health -q 'true' --response-code 405"
    interval:     60
    subscribers:  ['checks']
  'etcd-peer-health':
    command:      "check-http.rb -u http://127.0.0.1:2380/version -q 'etcdcluster' --response-code 405"
    interval:     60
    subscribers:  ['checks']

profile::openstack::network::calico::manage_bird: false

# openstack-neutron-common creates a sudoers.d file that
# maybe should be managed
sudo::purge: false

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present
  calico26:
    ensure: present
