---
include:
  default:
    - profile::openstack::network::controller
    - profile::openstack::resource::createnetworks
    - profile::application::etcd
    - profile::openstack::openrc
    - profile::openstack::cache
    - profile::logging::rsyslog::client
    - profile::base::systemd
    - profile::monitoring::telegraf


openstack_version: 'zed'

# This creates /etc/openstack/puppet/admin-clouds.yaml
keystone::bootstrap::bootstrap:        false
keystone::bootstrap::manage_resources: false
keystone::bootstrap::username:         'neutron'
keystone::bootstrap::password:         "%{hiera('neutron_api_password')}"
keystone::bootstrap::project_name:     "%{hiera('keystone__service__project')}"
keystone::bootstrap::internal_url:     "%{hiera('endpoint__identity__internal')}"
keystone::bootstrap::region:           "%{location}"
keystone::bootstrap::interface:        'internal'

etcd::proxy: "off"
etcd::initial_cluster_state: 'new'
etcd::initial_cluster_token: 'etcd-cluster'

profile::application::etcd::install_bootstrap_script: true

calico::controller: true
calico_version:     '327' # FIXME: move to common when versions on compute have been reconciled

profile::openstack::network::manage_quotas: true

profile::openstack::network::controller::manage_neutron_policies: true

profile::base::common::packages:
  # we need newer version of six to avoid breaking requests and openstack cli
  'python3-six.noarch': { ensure: latest }
  'bash-completion': {}
  'jq': {}
  'openstack-selinux': {}
  'python3-etcd3gw': {}
  'python3-memcached': {}
  'libibverbs': {}
  'python3-openstackclient': {}

profile::openstack::openrc::password:     "%{hiera('neutron_api_password')}"
profile::openstack::openrc::username:     'neutron'
profile::openstack::openrc::project_name: 'services'

# FIXME:sensu-go
profile::monitoring::sensu::agent::enable_go_agent:   true
profile::monitoring::sensu::agent::enable_agent:      false

# Sensu
sensu::agent::subscriptions:
  - 'base'
  - 'nodes'
  - 'metrics'
  - 'network'

profile::openstack::network::calico::manage_bird: false

# openstack-neutron-common creates a sudoers.d file that
# maybe should be managed
sudo::purge: false

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present
  calico37:
    ensure: absent
  calico%{hiera('calico_version')}:
    ensure: present
  CentOs-nfv-Openvswitch:
    ensure: present
  AlmaLinux-PowerTools:
    ensure: present
  epel: # should be absent when using RDO, but whitelist can also work
    ensure:   present
    includepkgs: 'htop libidn'
  influxdb:
    ensure: present

# logrotate
# 2022-01-07 (mikaeld): some issue on network nodes, especially in OSL, have the effect that one of the nodes
# in the cluster is logging a LOT! Until this is fixed we set up a more agressive log rotation
#
# One of the downsides is that we do not have control of how far back we have logs:
# On nodes with extensive logging: as low as 14 hours (hourly rotation due to more than 100 MB/hour)
# On nodes with a more normal log ratio: as far bask as several weeks (might be more than one full day until reached the 100 MB limit)
#
# We may rotate every hour regardless (drop the 100 MB requirement) and raise the 'rotate' parameter, but then most nodes will have
# a large number of very small rotated log files and be more cumbersome to wade through.
#
profile::logging::logrotate::manage_logrotate:    true

logrotate::rules:
  openstack-neutron:
    path:           '/var/log/neutron/*.log'
    size:           '100M'
    rotate:         14
    missingok:      true
    rotate_every:   'hourly'
    compress:       true
    dateext:        true
    dateformat:     '-%Y%m%d%H'

# Adjust the limits for open files for neutron-server via systemd
profile::base::systemd::manage_limits: true
profile::base::systemd::limits:
  neutron-server:
    limits:
      Service:
        'LimitNOFILE': 32768
        'LimitNOFILESoft': 32768

# Influx
profile::monitoring::telegraf::enable_telegraf:     true
#profile::monitoring::telegraf::use_http_proxy: true

## Flux: ETCD
etcd_influxdb_bucket: "etcd"

profile::monitoring::telegraf::outputs:
  influxdb_v2:
    options:
      - urls: ["https://%{hiera('mgmt__address__influx')}:8086"]
        tls_ca: '/etc/puppetlabs/puppet/ssl/certs/ca.pem'
        token: "%{hiera('influxdb_admin_token')}"
        organization: "%{hiera('profile::monitoring::influxdb::org')}"
        bucket: "%{hiera('etcd_influxdb_bucket')}"
        insecure_skip_verify: true
        tagpass:
          bucket: ["%{hiera('etcd_influxdb_bucket')}"]

profile::monitoring::telegraf::inputs:
  socket_listener:
    ensure: absent
  prometheus:
    options:
      - urls: ["http://localhost:2379/metrics"]
        metric_version: 2
        tags:
          bucket: "%{hiera('etcd_influxdb_bucket')}"
