---
include:
  default:
    - profile::openstack::openrc
    - profile::application::himlarcli
    - profile::application::himlarservice
    - profile::development::network::dns
    - profile::network::services
    - profile::network::nat
    - profile::application::rngd


named_interfaces::config:
  mgmt:
    - eth0
  trp:
    - eth1
  public:
    - dummy0

profile::application::rngd::enable: true

profile::base::common::packages:
  'python2-openstackclient': {} # FIXME remove when all proxies are el8
  'python3-openstackclient': {}
  'python3-designateclient': {}
  'bash-completion': {}
  'bash-completion-extras': {}  # FIXME remove when all proxies are el8
  'jq': {}
  'python2-gnocchiclient': {}   # FIXME remove when all proxies are el8
  'python3-gnocchiclient': {}
  'python2-osc-placement': {}   # FIXME remove when all proxies are el
  'python3-osc-placement': {}
  'openstack-selinux': {}
  'rsyslog': { ensure: present } # nice to have
  'git': {}
  'gcc': {}
  'openldap-devel': {}
  'openssl-devel': {}
  'libffi-devel': {}

profile::network::services::firewall_extras:
  source: '%{network_mgmt1}/%{netmask_mgmt1}'

profile::network::interface::create_custom_routes: true # New interface class needs enabling
profile::network::services::dns_proxy:             true
profile::network::services::http_proxy:            true
profile::development::network::dns::manage_hosts:  true
profile::development::network::dns::use_dnsmasq:   true
profile::base::network::manage_dummy:              true # FIXME remove when all proxies are migrated to el8
profile::network::interface::manage_dummy:         true
profile::network::nat::enable_snat:                true
profile::network::nat::source:                     "%{::network_mgmt1}/%{::netmask_mgmt1}"
profile::network::nat::outiface:                   'eth1'
profile::application::himlarservice::package_url:  'http://download.iaas.uio.no/nrec/rpm/himlarservice-1.1-3.el7.x86_64.rpm'
profile::application::himlarservice::enable:       true

# sensu python2 plugin (depricated)
# profile::monitoring::sensu::agent::plugin_gems:
#   sensu-plugins-openstack:
#     ensure:   '0.2.0'
#     provider: 'sensuclassic_gem'
#     source:   'http://download.iaas.uio.no/uh-iaas/gem'
# nova compute metrics
# profile::monitoring::sensu::agent::checks:
#   'nova-compute-metrics':
#     type:         'metric'
#     command:      "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-openstack-0.2.0/bin/nova/nova-hypervisor-metrics.py -s compute -t openstack -d Default -r %{::location} -p %{hiera('keystone_admin_password')} -a %{hiera('public__address__api')}"
#     interval:     60
#     subscribers:  ['metrics']
#     handlers:     ['graphite_tcp']

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present
  epel: # should be absent when using RDO, but whitelist can also work
    ensure:   present
    includepkgs: 'tinyproxy htop bash-completion-extras privoxy' # FIXME: Remove tinyproxy when el7 is gone
  calico%{hiera('calico_version')}:
    ensure: present
    includepkgs: 'dnsmasq'

logrotate::rules:
  himlarcli:
    path:           ['/opt/himlarcli/logs/himlar.log']
    rotate:         4
    size:           '100M'
    dateext:        true
    missingok:      true
    compress:       true
