---
include:
  default:
    - profile::openstack::openrc
    - profile::application::himlarcli
    - profile::application::himlarservice
    - profile::development::network::dns
    - profile::network::services
    - profile::network::nat

profile::base::common::packages:
  'python-openstackclient': {}
  'bash-completion': {}
  'bash-completion-extras': {}
  'jq': {}
  'python2-gnocchiclient': {}
  'openstack-selinux': {}

profile::network::services::firewall_extras:
  source: '%{network_mgmt1}/%{netmask_mgmt1}'

profile::network::services::dns_proxy:            true
profile::network::services::http_proxy:           true
profile::development::network::dns::manage_hosts: true
profile::development::network::dns::use_dnsmasq:  true
profile::base::network::manage_dummy:             true
profile::network::nat::enable_snat:               true
profile::network::nat::source:                    "%{::network_mgmt1}/%{::netmask_mgmt1}"
profile::network::nat::outiface:                  'eth1'
profile::application::himlarservice::package_url: 'http://download.iaas.uio.no/uh-iaas/rpm/himlarservice-1.0-1.el7.x86_64.rpm'

# sensu
profile::monitoring::sensu::agent::plugin_gems:
  sensu-plugins-openstack:
    ensure:   '0.2.0'
    provider: 'sensu_gem'
    source:   'http://download.iaas.uio.no/uh-iaas/gem'
# nova compute metrics
profile::monitoring::sensu::agent::checks:
  'nova-compute-metrics':
    type:         'metric'
    command:      "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-openstack-0.2.0/bin/nova/nova-hypervisor-metrics.py -s compute -t openstack -d Default -r %{::location} -p %{hiera('keystone_admin_password')} -a %{hiera('public__address__api')}"
    interval:     60
    subscribers:  ['metrics']
    handlers:     ['graphite_tcp']

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present
  epel: # should be absent when using RDO, but whitelist can also work
    ensure:   present
    includepkgs: 'tinyproxy htop bash-completion-extras jq oniguruma'
