---
include:
  default:
    - profile::webserver::apache
    - profile::application::report

profile::base::selinux::manage_selinux:       true
profile::base::selinux::boolean:
  'httpd_can_network_connect':
    ensure: 'on'
    persistent: true
  'httpd_tmp_exec':
    ensure: 'on'
    persistent: true

profile::webserver::apache::manage_firewall:  true
profile::webserver::apache::firewall_ports:   80

profile::base::common::packages:
  'gcc': {}
  'bash-completion': {}
  'bash-completion-extras': {}
  'python3-libs': {}

apache::default_mods:   false
apache::mod::wsgi::mod_path: /opt/report-app/lib/python3.6/site-packages/mod_wsgi-4.8.0-py3.6-linux-x86_64.egg/mod_wsgi/server/mod_wsgi-py36.cpython-36m-x86_64-linux-gnu.so
apache::mod::wsgi::package_name: mod_wsgi
profile::webserver::apache::mods_enable:
  - wsgi
  - dir
  - alias

profile::application::report::package_url:  'https://download.iaas.uio.no/uh-iaas/yumrepo/report-app-1.6.1-1.el7.x86_64.rpm'
profile::application::report::database_uri: "mysql+pymysql://report:%{hiera('report_db_password')}@%{hiera('service__address__db_global')}/report"
profile::application::report::debug:        true
profile::application::report::report_utils:
  'el':
    scripts:
      report6: ['el/shebang', 'common/imports.py', 'el/imports.py', 'common/common_functions.py', 'el/check_updates.py', 'common/payload.py', 'el/updates_payload.py', 'common/request.py' ]
      report8: ['el/shebang_8', 'common/imports.py', 'fedora/imports.py', 'common/common_functions.py', 'fedora/check_updates.py', 'common/payload.py', 'fedora/updates_payload.py', 'common/request.py' ]
    versions:
      7: 'report6'
      8: 'report8'
      9: 'report8'
  'fedora':
    scripts:
      report30: ['fedora/shebang', 'common/imports.py', 'fedora/imports.py', 'common/common_functions.py', 'fedora/check_updates.py', 'common/payload.py', 'fedora/updates_payload.py', 'common/request.py' ]
    versions:
      30: 'report30'
      31: 'report30'
      32: 'report30'
      34: 'report30'
      35: 'report30'
      36: 'report30'
      37: 'report30'
      38: 'report30'
  'ubuntu':
    scripts:
      report17: ['ubuntu/shebang', 'common/imports.py', 'ubuntu/imports.py', 'common/common_functions.py', 'ubuntu/check_updates_functions.py', 'common/payload.py', 'ubuntu/updates_payload.py', 'common/request.py' ]
    versions:
      17: 'report17'
      18: 'report17'
      19: 'report17'
      20: 'report17'
      21: 'report17'
      22: 'report17'
  'debian':
    scripts:
      report9: ['debian/shebang', 'common/imports.py', 'debian/imports.py', 'common/common_functions.py', 'debian/check_updates_functions.py', 'common/payload.py', 'debian/updates_payload.py', 'common/request.py' ]
    versions:
      9:  'report9'
      10: 'report9'
      11: 'report9'
  'windows':
    scripts:
      report2016: ['windows/full_script' ]
    versions:
      Microsoft_Windows_Server_2016_Standard: 'report2016'
      Microsoft_Windows_Server_2019_Standard: 'report2016'
      Microsoft_Windows_Server_2022_Standard: 'report2016'

profile::webserver::apache::vhosts:
  report-app:
    vhost_name:         "%{hostname}.%{hiera('domain_trp')}"
    servername:         "%{hostname}.%{hiera('domain_trp')}"
    serveraliases:
     - "%{hiera('public__address__report')}"
     - "report-%{::location}.%{hiera('domain_frontend')}"
     - "report-%{::location}.%{hiera('domain_frontend2')}"
    port:               '80'
    manage_docroot:     false
    docroot:            '/var/www/html'
    wsgi_application_group:  '%%{}{GLOBAL}'
    wsgi_pass_authorization: 'on'
    wsgi_daemon_process:     'report-app'
    wsgi_daemon_process_options:
      threads:      '4'
      python-path:  "/opt/report-app:/opt/report-app/lib/python3.6/site-packages"
    wsgi_script_aliases:
      '/':   "/opt/report-app/flask.wsgi"
    aliases:
      - alias:            '/downloads'
        path:             '/opt/report-utils'
    directories:
      - path:             '/opt/report-app/'
        require:          'all granted'
        custom_fragment:  'WSGIProcessGroup report-app'
      - path:             '/opt/report-utils'
        require:          'all granted'
