---
include:
  default:
    - profile::network::leaf
    - profile::base::common
    - profile::base::cl_limits
    - profile::monitoring::collectd
  bootstrap:
    - profile::base::common

profile::base::common::classes:
  - puppet
  - openstack_extras::repo::debian::debian

profile::base::common::manage_keyboard:           false
profile::base::common::include_virtual:           false
profile::base::common::include_physical:          false
profile::base::common::manage_yumrepo:            false
profile::base::common::disable_firewalld:         false
profile::base::firewall::manage_firewall:         false
profile::base::network::net_ifnames:              false
profile::network::leaf::manage_quagga:            false
profile::network::leaf::manage_frrouting:         true
profile::network::leaf::manage_acls:              true
profile::base::network::cumulus_ifs:              true
network::config_file_per_interface:               true
profile::logging::logrotate::manage_logrotate:    false
profile::base::cl_limits::manage_cl_limits:       true
profile::base::cl_limits::as_value:               2097152

profile::base::common::manage_ntp:     false
profile::base::common::manage_chrony:  true
chrony::service_name: 'chrony@mgmt'

profile::monitoring::collectd::enable: true
profile::monitoring::collectd::merge_strategy: 'first'
profile::monitoring::collectd::plugins:
   - collectd::plugin::interface
   - collectd::plugin::write_graphite
# The upstream collectd module does not allow setting the service name
collectd::service_ensure: stopped                                                                       
collectd::service_enable: false
profile::monitoring::collectd::manage_service: true
profile::monitoring::collectd::service_name:   'collectd@mgmt'

# ntp service managed by profile because of mgmt VRF
ntp::service_enable: false
ntp::service_ensure: 'stopped'
ntp::interfaces: [ 'eth0' ]

frrouting::zebra:                 true
frrouting::bgpd:                  true
frrouting::single_config_file:    true
frrouting::frrouting::hostname:   'cumulus-test'
frrouting::frrouting::password:   'pass123'
frrouting::frrouting::bgp_as:     "%{hiera('bgp_as')}"

profile::network::leaf::acls:
  '02control_plane_custom.rules':
    rule_vars:
      - "INGRESS_CHAIN = INPUT"
      - "INGRESS_INTF = swp+"
      - "FORWARD_CHAIN = FORWARD"
    iptables:
      - "-A $INGRESS_CHAIN -s %{hiera('netcfg_mgmt_netpart')}.0/%{hiera('netcfg_mgmt_netmask')} -p tcp --dport 19999 -j ACCEPT"
      - "-A $INGRESS_CHAIN -p tcp --dport 19999 -j DROP"
      - "-A $INGRESS_CHAIN -s %{hiera('netcfg_trp_netpart')}.0/%{hiera('netcfg_trp_netmask')} -p tcp --dport 179 -j ACCEPT"
      - "-A $INGRESS_CHAIN -s %{hiera('netcfg_elastic_cidr')} -p tcp --dport 179 -j ACCEPT"
      - "-A $INGRESS_CHAIN -p tcp --dport 179 -j DROP"
      - "-A $INGRESS_CHAIN -s %{hiera('netcfg_mgmt_netpart')}.0/%{hiera('netcfg_mgmt_netmask')} -p tcp --dport 22 -j ACCEPT"
      - "-A $INGRESS_CHAIN -s %{hiera('netcfg_trp_netpart')}.0/%{hiera('netcfg_trp_netmask')} -p tcp --dport 22 -j ACCEPT"
      - "-A $INGRESS_CHAIN -p tcp --dport 22 -j DROP"
    ip6tables:
      - "-A $INGRESS_CHAIN --in-interface $INGRESS_INTF -s %{hiera('netcfg_trp_netpart6')}::/%{hiera('netcfg_trp_netmask6')} -p tcp -m multiport --dports 22,179 -j ACCEPT"
      - "-A $INGRESS_CHAIN --in-interface $INGRESS_INTF -p tcp  -m multiport --dports 22,179 -j DROP"

accounts::groups:
  'wheel':
    ensure: 'present'

openstack_extras::repo::debian::debian::package_require: true
openstack_extras::repo::debian::debian::manage_uca: false
openstack_extras::repo::debian::debian::manage_whz: false
openstack_extras::repo::debian::debian::source_hash:
  'buster':
    'location': 'http://ftp.no.debian.org/debian'
    'repos':    'main'
  'nrec':
    'location': 'https://download.iaas.uio.no/nrec/'
    'repos':    'main'
    'release':  'buster'

profile::base::common::packages:
  'vim-enhanced': { 'ensure': 'absent', }
  'bind-utils': { 'ensure': 'absent', }
  'yum-utils': { 'ensure': 'absent', }
  'augeas-tools': {}
  'sysstat': {} # needed for sensu network plugin

sudo::configs:
  snmp:
    content:
      - '# SNMP needs access to the bcmcmd to serve up some of the MIBs.'
      - 'snmp ALL = NOPASSWD: /usr/lib/cumulus/bcmcmd'
      - 'snmp ALL = NOPASSWD: /usr/cumulus/bin/cl-resource-query'
      - 'snmp ALL=(root) NOPASSWD: /sbin/ethtool -S *'
      - 'snmp ALL=(root) NOPASSWD: /sbin/ip'

profile::base::network::cumulus_interfaces:
  'lo':
    'addr_method': 'loopback'
