---
include:
  default:
    - profile::monitoring::grafana

profile::base::common::packages:
  'bash-completion': {}
  'bash-completion-extras': {}

# Selinux
profile::base::selinux::manage_selinux:         true

# Grafana
profile::monitoring::grafana::enable:           true
profile::monitoring::grafana::manage_firewall:  true
profile::monitoring::grafana::firewall_extras:
  source: "%{::network_trp1}/%{::netmask_trp1}"

grafana_openstack_user: 'status'
grafana_openstack_password: "%{hiera('status_metric_password')}"

grafana::plugins:
  gnocchixyz-gnocchi-datasource:
    ensure: present
  ryantxu-ajax-panel:
    ensure: present

grafana::cfg:
  app_mode: 'production'
  server:
    http_port:    '8080'
    http_addr:    '0.0.0.0'
  security:
    admin_user:     'admin'
    admin_password: "%{hiera('grafana_admin_password')}"
  auth.anonymous:
    enabled:        true
    org_name:       'norcams'
  auth:
    disable_login_form: true
    disable_login: true
    disable_signout_menu: true
  auth.basic:
    enabled: false
  users:
    allow_sign_up:    false
    allow_org_create: false

grafana::provisioning_dashboards:
  apiVersion: 1
  providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: true
      options:
        path: '/var/lib/grafana/dashboards'
      #   puppetsource: 'puppet:///modules/profile/status/grafana/dashboard'

profile::monitoring::grafana::dashboards:
  home:
    template: status

# FIXME:sensu-go
profile::monitoring::sensu::agent::enable_go_agent:   true
profile::monitoring::sensu::agent::enable_agent:      false

# Sensu
sensu::agent::subscriptions:
  - 'base'
  - 'nodes'
  - 'metrics'

# Enable extra yum repo for openstack client
profile::base::yumrepo::repo_hash:
  "%{operatingsystem}-AppStream":
    exclude: 'grafana'
  grafana:
    ensure: absent
  grafana-oss:
    ensure: present
