---
include:
  default:
    - profile::monitoring::grafana

profile::base::common::packages:
  'bash-completion': {}
  'bash-completion-extras': {}
  'jq': {}

# Selinux
profile::base::selinux::manage_selinux:         false

# Grafana
profile::monitoring::grafana::enable:           true
profile::monitoring::grafana::manage_firewall:  true
profile::monitoring::grafana::firewall_extras:
  source: "%{::network_trp1}/%{::netmask_trp1}"

grafana::cfg:
  app_mode: 'production'
  server:
    http_port:    '8080'
    http_addr:    '0.0.0.0'
  security:
    admin_user:     'admin'
    admin_password: "%{hiera('grafana_admin_password')}"
  auth.anonymous:
    enabled:        true
    org_name:       'norcams'
  users:
    allow_sign_up:    false
    allow_org_create: false

# Enable extra yum repo for openstack client
profile::base::yumrepo::repo_hash:
  grafana:
    ensure: present
