---
include:
  default:
    - profile::application::openssl

profile::application::openssl::manage_ca_cert: true

profile::application::openssl::certs:
  "star.api.%{hiera('domain_public')}":
    cn:     "*.api.%{hiera('domain_public')}"
    altnames:
      - "*.api.%{hiera('domain_public')}"
    concat: true
  "status.%{hiera('domain_public')}":
    cn:     "*.%{hiera('domain_public')}"
    altnames:
      - "status.%{hiera('domain_public')}"
      - "access.%{hiera('domain_public')}"
      - "report.%{hiera('domain_public')}"
    concat: true
  "api.%{hiera('domain_public')}":
    cn:     "api.%{hiera('domain_public')}"
    altnames:
      - "api.%{hiera('domain_public')}"
    concat: true
  "console.%{hiera('domain_public')}":
    cn:     "console.%{hiera('domain_public')}"
    concat: true

#
# Example of override network backend for more nodes
#
# profile::highavailability::loadbalancing::haproxy::haproxy_balancermembers:
#   network:
#     listening_service:  'bk_network'
#     ports:              9696
#     server_names:
#       - '%{::location}-network-01'
#       - '%{::location}-network-02'
#     ipaddresses:
#       - "%{hiera('netcfg_trp_netpart')}.71"
#       - "%{hiera('netcfg_trp_netpart')}.72"
#     options:            'check'


# Example of override compute backend for more nodes
#
# profile::highavailability::loadbalancing::haproxy::haproxy_balancermembers:
#   compute:
#     listening_service:  'bk_compute'
#     ports:              8774
#     server_names:
#       - '%{::location}-novactrl-01'
#       - '%{::location}-novactrl-02'
#     ipaddresses:
#       - "%{hiera('netcfg_trp_netpart')}.66"
#       - "%{hiera('netcfg_trp_netpart')}.67"
#     options:            'check'

## Example of override placement backend for more nodes
#
# profile::highavailability::loadbalancing::haproxy::haproxy_balancermembers:
#   placement:
#     listening_service:  'bk_placement'
#     ports:              8778
#     server_names:
#       - '%{::location}-novactrl-01'
#       - '%{::location}-novactrl-02'
#     ipaddresses:
#       - "%{hiera('netcfg_trp_netpart')}.66"
#       - "%{hiera('netcfg_trp_netpart')}.67"
#     options:            'check'

## Example of override dns backend for more nodes
#
# profile::highavailability::loadbalancing::haproxy::haproxy_balancermembers:
#   dns:
#     server_names:
#       - '%{::location}-dns-01'
#       - '%{::location}-dns-02'
#       - '%{::location}-dns-03'
#     ipaddresses:
#       - "%{hiera('netcfg_trp_netpart')}.34"
#       - "%{hiera('netcfg_trp_netpart')}.35"
#       - "%{hiera('netcfg_trp_netpart')}.39"
