classes:
  - hostname
classes_bootstrap:
  - hostname

foreman_proxy::dhcp_range:                    '10.0.3.100 10.0.3.199'
foreman_proxy::dhcp_gateway:                  10.0.3.1
foreman_proxy::dhcp_nameservers:              10.0.3.5
foreman_proxy::dhcp_interface:                eth1
foreman_proxy::tftp_servername:               10.0.3.5
foreman_proxy::dns_server:                    10.0.3.5
foreman_proxy::dns_managed:                   true
foreman_proxy::dns_forwarders:                ['8.8.8.8']
foreman_proxy::dns_zone:                      'himlar.local'
foreman_proxy::dns_reverse:                   '3.0.10.in-addr.arpa'

profile::base::common::manage_networkifs:     true
network_if:
  eth1:
    ipv4_ips:   10.0.3.5/24
    ensure:     up
    start_mode: onboot
    type:       ethernet
