---
include:
  default:
    - profile::development::patch

# Turn on for debug
# include:
#   default:
#     - apache::mod::dumpio
#
# apache::log_level:  dumpio:trace7

# profile::openstack::identity::keystone_config:
#   'federation/trusted_dashboard':
#     value:  "https://%{hiera('public__address__dashboard')}/dashboard/auth/websso/"
#   'federation/remote_id_attribute':
#     value:  'OIDC-iss'
#   'resource/project_name_url_safe':
#     value:  'new'
#   'resource/domain_name_url_safe':
#     value:  'new'
#   'cors/allowed_origin': # allow gnocchi access on monitor
#     value:  "http://%{hiera('mgmt__address__monitor')}:8080"
#   'DEFAULT/notification_opt_out':
#     value:  'identity.authenticate.success'
#   'security_compliance/lockout_duration':
#     value:  '60'
#   'security_compliance/lockout_failure_attempts':
#     value:  '3'
#   'DEFAULT/insecure_debug':
#     value:  'true'
#

# Make sure we fully bootstrap keystone in vagrant on identity
keystone::bootstrap::bootstrap:  true

# Project for global image sharing
profile::openstack::resource::image_sharing::manage: false
#profile::openstack::resource::image_sharing::domain: 'default'

# FIXME:sensu-go
profile::monitoring::sensu::agent::checks:              {}

profile::base::common::packages:
  'python3-redis': {} # OSProfiler dependency

profile::openstack::identity::manage_osprofiler: true
