---
# Our internal zone
profile::dns::ns::internal_zone: "vagrant.iaas.intern"

# Name servers in zone file
profile::dns::ns::name_servers:
  - "ns.%{hiera('profile::dns::ns::internal_zone')}"

# Forward zones, for which the name server is authoritative
profile::dns::ns::fw_zones:
  internal:
    zone: "%{hiera('profile::dns::ns::internal_zone')}"
    filename: "%{hiera('profile::dns::ns::zonedir')}/%{hiera('profile::dns::ns::internal_zone')}"

# Reverse zones, for which the name server is authoritative
profile::dns::ns::ptr_zones:
  internal:
    cidr: "172.31.0.0/16"
    origin: "31.172.in-addr.arpa"
    filename: "%{hiera('profile::dns::ns::zonedir')}/31.172.in-addr.arpa"
  public:
    cidr: "192.168.0/16"
    origin: "168.192.in-addr.arpa"
    filename: "%{hiera('profile::dns::ns::zonedir')}/168.192.in-addr.arpa"
  ipv6:
    cidr: "fc00::/7"
    origin: "c.f.ip6.arpa"
    filename: "%{hiera('profile::dns::ns::zonedir')}/c.f.ip6.arpa"
