---
profile::application::report::db_sync:        false

# used to build report app package
profile::base::common::packages:
  'httpd-devel': {}
  'python3-virtualenv': {}

# copy of test01 - DO NOT COMMIT
profile::base::selinux::manage_selinux:       true
profile::base::selinux::boolean:
  'httpd_can_network_connect':
    ensure: 'on'
    persistent: true
  'httpd_tmp_exec':
    ensure: 'on'
    persistent: true

profile::webserver::apache::manage_firewall:  true
profile::webserver::apache::firewall_ports:   80

# Very verbose logging in vagrant
apache::log_level:                              debug

apache::default_mods:   false
apache::mod::wsgi::wsgi_python_home: '/opt/report-app/'
apache::mod::wsgi::package_name: 'python3.12-mod_wsgi'
apache::mod::wsgi::mod_path: "/usr/lib64/python3.12/site-packages/mod_wsgi/server/mod_wsgi-py312.cpython-312-x86_64-linux-gnu.so"
profile::webserver::apache::mods_enable:
  - wsgi
  - dir
  - alias

profile::application::report::manage_alembic:   true
profile::application::report::package_url:      "https://download.iaas.uio.no/nrec/rpm/report-app-2.1.1-1.el8.x86_64.rpm"
profile::application::report::database_uri:     "mysql+pymysql://report:%{hiera('report_db_password')}@%{hiera('service__address__db_global')}/report"
profile::application::report::debug:            true
profile::application::report::report_api_url:   "https://%{hiera('public__address__report')}/api/v1/instance"

profile::webserver::apache::vhosts:
  report-app:
    vhost_name:         "%{hostname}.%{hiera('domain_trp')}"
    servername:         "%{hostname}.%{hiera('domain_trp')}"
    serveraliases:
     - "%{hiera('public__address__report')}"
     - "report-%{::location}.%{hiera('domain_frontend')}"
     - "report-%{::location}.%{hiera('domain_frontend2')}"
    port:               80
    manage_docroot:     false
    docroot:            '/var/www/html'
    wsgi_application_group:  '%%{}{GLOBAL}'
    wsgi_pass_authorization: 'on'
    wsgi_daemon_process:     'report-app'
    wsgi_daemon_process_options:
      threads:      '4'
      python-path:  "/opt/report-app:/opt/report-app/lib/python3.12/site-packages"
    wsgi_script_aliases:
      '/':   "/opt/report-app/flask.wsgi"
    aliases:
      - alias:            '/downloads'
        path:             '/opt/report-utils'
    directories:
      - path:             '/opt/report-app/'
        require:          'all granted'
        custom_fragment:  'WSGIProcessGroup report-app'
      - path:             '/opt/report-utils'
        require:          'all granted'
    use_servername_for_filenames: true
