---
profile::application::access::allow_from_network:
  - '129.177.6.133/32'  # bgo-login
  - '129.177.31.96/27'  # test01
  - '129.177.10.189/32' # tor
  - '129.177.10.212/32' # raymond
  - '129.240.130.12/32' # trond
  - '129.240.130.124/32'# mikael
  - '129.240.202.64/32' # mikael
  - '129.240.202.96/32' # tannaz

# Test new package
#profile::application::access::package_url:      'https://download.iaas.uio.no/uh-iaas/rpm/himlar-dp-prep-1.3-1.el7.x86_64.rpm'

