---
profile::openstack::compute::consoleproxy::allow_from_network:
  - '129.177.6.133/32'  # bgo-login
  - '129.177.31.96/27'  # test01
  - '129.177.9.135/32'  # lennart
  - '129.177.10.189/32' # tor
  - '129.177.10.212/32' # raymond
  - '129.240.130.12/32' # trond
  - '129.240.130.124/32'# mikael
  - '129.240.202.64/32' # mikael
