---
include:
  default:
    - profile::base::tuned

profile::bootstrap::himlar::libvirt:
  '%{location}-admin-01':
    domain:           'mgmt.test01.uhdc.no'
    libvirt_pool:     'dirpool'
    libvirt_network:  'directnet'
    node_ip:          '172.28.0.11'
    node_netmask:     '255.255.255.0'
    node_gateway:     '172.28.0.10'
    vm_vcpus:         2
    vm_memory:        8096

profile::virtualization::libvirt::networks:
  directnet:
    ensure:              enabled
    autostart:           true
    forward_mode:        bridge
    bridge:              br0
  trpnet:
    ensure:              enabled
    autostart:           true
    forward_mode:        bridge
    bridge:              br1
  oobnet:
    ensure:              enabled
    autostart:           true
    forward_mode:        bridge
    bridge:              br2

# Set tuned profile to "virtual-host"
profile::base::tuned::manage_tuned:  true
profile::base::tuned::tuned_profile: 'virtual-host'

# FIXME:sensu-go
profile::base::physical::enable_redfish_sensu_check: true
sensu::agent::subscriptions:
  - 'base'
  - 'metrics'
  - 'physical'
