---
profile::openstack::resource::host_aggregate:
  central1:
    availability_zone: "%{::location}-default-1"
    metadata:
      type: 'standard'
  shpc_cpu1:
    availability_zone: "%{::location}-default-1"
    metadata:
      type: 'shpc_cpu'
  local1:
    availability_zone: "%{::location}-default-1"
    metadata:
      type: 'local'
#    hosts: "%{::location}-compute-01.%{hiera('domain_mgmt')}"
  placeholder1:
    availability_zone: "%{::location}-iaas-team-only-1"
#    hosts: "%{::location}-compute-02.%{hiera('domain_mgmt')}"
    metadata:
      type: 'standard'
      filter_tenant_id: >-
        9edeba0543ac4824a0aa95f947528c02,
        2ce04b3aaf3e45378f4f00072ceb5f20,
        8664497aa1224161bb1ed3bd88a65858

nova::config::nova_config:
  # Enable Placement-based quota counting (this enables freeing up resources when VM is shelved_offloaded)
  "quota/count_usage_from_placement":
    value: "true"
