---
named_interfaces::config:
  mgmt:
     - em3
  transport:
     - bond0
  trp:
     - bond0

profile::base::lvm::physical_volume:
  '/dev/sda3':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_journala':
    physical_volumes:
      - /dev/sda3
profile::base::lvm::logical_volume:
  lv_journala01:
    size:         11G
    volume_group: 'vg_journala'
    fs_type:      xfs
    mountpath:    "/journal/journala01"
  lv_journala02:
    size:         11G
    volume_group: 'vg_journala'
    fs_type:      xfs
    mountpath:    "/journal/journala02"
  lv_journala03:
    size:         11G
    volume_group: 'vg_journala'
    fs_type:      xfs
    mountpath:    "/journal/journala03"
  lv_journala04:
    size:         11G
    volume_group: 'vg_journala'
    fs_type:      xfs
    mountpath:    "/journal/journala04"
  lv_journala05:
    size:         11G
    volume_group: 'vg_journala'
    fs_type:      xfs
    mountpath:    "/journal/journala05"
  lv_journala06:
    size:         11G
    volume_group: 'vg_journala'
    fs_type:      xfs
    mountpath:    "/journal/journala06"
  lv_journala07:
    size:         11G
    volume_group: 'vg_journala'
    fs_type:      xfs
    mountpath:    "/journal/journala07"
  lv_journala08:
    size:         11G
    volume_group: 'vg_journala'
    fs_type:      xfs
    mountpath:    "/journal/journala08"
  lv_journala09:
    size:         11G
    volume_group: 'vg_journala'
    fs_type:      xfs
    mountpath:    "/journal/journala09"
  lv_journala10:
    size:         11G
    volume_group: 'vg_journala'
    fs_type:      xfs
    mountpath:    "/journal/journala10"
#  lv_journala11:
#    size:         11G
#    volume_group: 'vg_journala'
#    fs_type:      xfs
#    mountpath:    "/journal/journala11"
#  lv_journala12:
#    size:         11G
#    volume_group: 'vg_journala'
#    fs_type:      xfs
#    mountpath:    "/journal/journala12"
#  lv_journala13:
#    size:         11G
#    volume_group: 'vg_journala'
#    fs_type:      xfs
#    mountpath:    "/journal/journala13"
#  lv_journala14:
#    size:         11G
#    volume_group: 'vg_journala'
#    fs_type:      xfs
#    mountpath:    "/journal/journala14"
#  lv_journala15:
#    size:         11G
#    volume_group: 'vg_journala'
#    fs_type:      xfs
#    mountpath:    "/journal/journala15"

ceph::profile::params::osds:
  '/dev/sdc':
    journal: '/journal/journala01/journal'
  '/dev/sdd':
    journal: '/journal/journala02/journal'
  '/dev/sde':
    journal: '/journal/journala03/journal'
  '/dev/sdf':
    journal: '/journal/journala04/journal'
  '/dev/sdg':
    journal: '/journal/journala05/journal'
  '/dev/sdh':
    journal: '/journal/journala06/journal'
  '/dev/sdi':
    journal: '/journal/journala07/journal'
  '/dev/sdj':
    journal: '/journal/journala08/journal'
  '/dev/sdk':
    journal: '/journal/journala09/journal'
  '/dev/sdl':
    journal: '/journal/journala10/journal'
#  '/dev/sdm':
#    journal: '/journal/journala11/journal'
#  '/dev/sdn':
#    journal: '/journal/journala12/journal'
#  '/dev/sdo':
#    journal: '/journal/journala13/journal'
#  '/dev/sdp':
#    journal: '/journal/journala14/journal'
#  '/dev/sdq':
#    journal: '/journal/journala15/journal'
