---
named_interfaces::config:
  mgmt:
    - em3
  transport:
    - team1
  trp:
    - team1
  ceph:
    - team1.110

profile::base::network::network_auto_opts:
  trp:
    'defroute': 'no'
    'devicetype': 'Team'
    'mtu': '9000'
    'team_config': >-
                   { "runner" : {  "name" : "lacp",  "active": true, "fast_rate" : true,
                   "tx_hash": ["eth", "ipv4", "ipv6"], "tx_balancer": { "name": "basic" } },
                   "link_watch" : {  "name" : "ethtool" } }
  ceph:
    'defroute': 'no'

profile::base::network::network_auto_bonding:
  trp:
    p3p1:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'
    p3p2:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'

# Disable intel c states for performance
profile::base::physical::disable_intel_cstates: true

profile::base::common::extraswap:         true
profile::base::common::extraswap_sizegb:  40
profile::base::common::extraswap_fileloc: '/var/lib/swap/swapfile'

# Ensure that the BOSS device is the last device
profile::base::physical::load_ahci_last: true
profile::base::physical::load_ahci_last_scsidrv: 'megaraid_sas'
profile::base::physical::scsi_load_order: true
profile::base::physical::scsi_load_order_first:  'megaraid_sas'
profile::base::physical::scsi_load_order_second: 'mpt3sas'

profile::base::selinux::manage_selinux: false

profile::base::yumrepo::repo_hash:
  elrepo:
    ensure: present

#profile::base::common::manage_fake_ssd: true

# FIXME
profile::base::common::manage_lvm:                  true
profile::base::lvm::create_lvm:                     true
profile::storage::cephosd::create_osds:             true
profile::storage::cephosd::crush_move:              true
profile::storage::cephpool::manage_ec_pools:        true
profile::storage::cephpool::manage_cephpool_params: true

profile::storage::cephclient::create_extraconf: true
profile::storage::ceph_extraconf::config:
  osd_memory_target:
    'config_key'  : "osd/osd_memory_target"
    'config_value': "3973054464"

# Disable write cache on osd cache disk
profile::base::disk::manage_hdparm: true
profile::base::disk::disk_hdparams:
  '/dev/sda': { hdparams: '-W0', }

profile::base::lvm::volume_group:
  'vg_swap':
    physical_volumes:
      - /dev/sdr3
  'vg_cache1':
    physical_volumes:
      - /dev/sda
  'vg_cache2':
    physical_volumes:
      - /dev/sdb
profile::base::lvm::logical_volume:
  'lv_swap2':
    volume_group: 'vg_swap'
    fs_type:      xfs
    size:         60G
    mountpath:    "/var/lib/swap"
  'lv_dbf':
    volume_group: 'vg_cache1'
    createfs:     false
    size:         31G
  'lv_dbg':
    volume_group: 'vg_cache1'
    createfs:     false
    size:         31G
  'lv_dbh':
    volume_group: 'vg_cache1'
    createfs:     false
    size:         31G
  'lv_dbi':
    volume_group: 'vg_cache1'
    createfs:     false
    size:         31G
  'lv_dbj':
    volume_group: 'vg_cache1'
    createfs:     false
    size:         31G
  'lv_dbk':
    volume_group: 'vg_cache1'
    createfs:     false
    size:         31G
  'lv_dbl':
    volume_group: 'vg_cache1'
    createfs:     false
    size:         31G
  'lv_dbm':
    volume_group: 'vg_cache2'
    createfs:     false
    size:         31G
  'lv_dbn':
    volume_group: 'vg_cache2'
    createfs:     false
    size:         31G
  'lv_dbo':
    volume_group: 'vg_cache2'
    createfs:     false
    size:         31G
  'lv_dbp':
    volume_group: 'vg_cache2'
    createfs:     false
    size:         31G
  'lv_dbq':
    volume_group: 'vg_cache2'
    createfs:     false
    size:         31G

profile::storage::cephosd::osds:
  '/dev/sdc':
    db_device:  false
    wal_device: false
  '/dev/sdd':
    db_device:  false
    wal_device: false
  '/dev/sde':
    db_device:  false
    wal_device: false
  '/dev/sdf':
    wal_device: false
    db_device:  'vg_cache1/lv_dbf'
  '/dev/sdg':
    wal_device: false
    db_device:  'vg_cache1/lv_dbg'
  '/dev/sdh':
    wal_device: false
    db_device:  'vg_cache1/lv_dbh'
  '/dev/sdi':
    wal_device: false
    db_device:  'vg_cache1/lv_dbi'
  '/dev/sdj':
    wal_device: false
    db_device:  'vg_cache1/lv_dbj'
  '/dev/sdk':
    wal_device: false
    db_device:  'vg_cache1/lv_dbk'
  '/dev/sdl':
    wal_device: false
    db_device:  'vg_cache1/lv_dbl'
  '/dev/sdm':
    wal_device: false
    db_device:  'vg_cache2/lv_dbm'
  '/dev/sdn':
    wal_device: false
    db_device:  'vg_cache2/lv_dbn'
  '/dev/sdo':
    wal_device: false
    db_device:  'vg_cache2/lv_dbo'
  '/dev/sdp':
    wal_device: false
    db_device:  'vg_cache2/lv_dbp'
  '/dev/sdq':
    wal_device: false
    db_device:  'vg_cache2/lv_dbq'

profile::storage::ceph::pool::pools:
  'rbd':
    ensure: absent
  'volumes':
    size:    3
    tag:     'rbd'
    custom:
      crush_rule: 'hdd-storage'
      nodelete:   'true'
      min_size:   '2'
  'images':
    size:    3
    tag:    'rbd'
    custom:
      crush_rule: 'hdd-storage'
      nodelete:   'true'
      min_size:   '2'
  'vms':
    size:    3
    tag:     'rbd'
    custom:
      crush_rule: 'ssd-storage'
      nodelete:   'true'
      min_size:   '2'
  'volumes_hdd_ec_meta':
    size:    3
    tag:     'rbd'
    custom:
      crush_rule: 'ssd-storage'
      nodelete:   'true'
      min_size:   '2'
  'volumes_ssd_ec_meta':
    size:    3
    tag:     'rbd'
    custom:
      crush_rule: 'ssd-storage'
      nodelete:   'true'
      min_size:   '2'
  'cephfs_internal_meta':
    size:    3
    pg_num:  16
    custom:
      crush_rule: 'ssd-storage'
      nodelete:   'true'
      min_size:   '2'
  'cephfs_internal_data_default':
    size:    3
    pg_num:  16
    custom:
      crush_rule: 'ssd-storage'
      nodelete:   'true'
      min_size:   '2'
profile::storage::ceph::pool::ec_pools:
  'placeholder':
    manage: false

profile::storage::ceph_ecpool::ec_pools:
  'volumes_hdd_ec_data':
    manage:              true
    allow_ec_overwrites: true
    k_data:              "4"
    m_code:              "1"
    crush_root:          "storage"
  'volumes_ssd_ec_data':
    manage:              true
    allow_ec_overwrites: true
    k_data:              "4"
    m_code:              "1"
    crush_root:          "storage"
    crush_device_class:  "ssd"
  'cephfs_internal_data_ec':
    manage:              true
    allow_ec_overwrites: true
    k_data:              "4"
    m_code:              "1"
    crush_root:          "storage"

profile::storage::cephpool_params::pools:
  'volumes_hdd_ec_data':
    application_enable: 'rbd'
  'volumes_ssd_ec_data':
    application_enable: 'rbd'

# Sensu

profile::base::physical::enable_redfish_sensu_check: true

sudo::configs:
  sensu_tty:
    priority: 20
    content:  'Defaults:sensu !requiretty'
  sensu:
    priority: 25
    content:  'sensu ALL=(ALL) NOPASSWD: /opt/sensu/embedded/bin/check-smart.rb'

profile::monitoring::sensu::agent::checks:
  'redfish-check':
    command:                '/usr/local/bin/redfish_check.sh'
    interval:               1800
    subscriptions:          ['entity:%{::hostname}']
    handlers:               ['default']
  # 'check-smart':
  #   command:      "/usr/bin/sudo /opt/sensu/embedded/bin/check-smart.rb"
  #   interval:     3600
  #   subscribers:  ['checks']
  # 'metrics-netif':
  #   type:         'metric'
  #   command:      'metrics-netif.rb --scheme network.%{::hostname}'
  #   interval:     60
  #   subscribers:  ['metrics']
  #   handlers:     ['graphite_tcp']
  # 'metrics-disk':
  #   type:         'metric'
  #   command:      'metrics-disk.rb --scheme disk.%{::hostname} -I sd[a-z]$'
  #   interval:     60
  #   subscribers:  ['metrics']
  #   handlers:     ['graphite_tcp']

profile::monitoring::sensu::agent::plugin_gems: {}
  # sensu-plugins-himlar:
  #   ensure:   '0.4.0'
  #   provider: 'sensuclassic_gem'
  #   source:   'http://download.iaas.uio.no/uh-iaas/gem'

profile::monitoring::sensu::agent::plugins: {}
  # sensu-plugins-network-checks:
  #   type:         package
  #   pkg_version:  '4.1.1'
