---
status_ssl_pem:   "api.%{hiera('domain_public')}.pem" #FIXME (status cert)
console_ssl_pem:  "api.%{hiera('domain_public')}.pem" #FIXME (console cert)
access_ssl_pem:   "api.%{hiera('domain_public')}.pem" #FIXME (access cert)

profile::highavailability::loadbalancing::haproxy::haproxy_balancermembers:
  network:
    server_names:       ['%{::location}-network-02']
    ipaddresses:        ["%{hiera('netcfg_trp_netpart')}.72"]
