---
include:
  kickstart:
    - profile::monitoring::sensu::agent
  default:
    - profile::monitoring::collectd


named_interfaces::config:
  mgmt:
    - em3
  trp:
    - em1
  live:
    - em1

profile::base::network::network_auto_opts:
  mgmt:
    'defroute': 'no'
  trp:
    'ipv6init': 'yes'

ntp::servers:
  - 172.28.32.100
  - 172.28.32.101
  - 172.28.32.102

profile::monitoring::sensu::agent::enable_agent:  true

# Add custom routing table for private network to NAT
profile::base::network::routes:
  'em1':
    'ipaddress': [ '0.0.0.0', '0.0.0.0', ]
    'netmask':   [ '0.0.0.0', '0.0.0.0', ]
    'gateway':   [ "%{hiera('netcfg_priv_gateway')}", "%{hiera('netcfg_trp_gateway')}" ]
    'table':     [ 'private', 'main', ]
profile::base::network::routing_tables:
  'private':
    'table_id':  '240'
profile::base::network::rules:
  'em1':
    iprule: [ "from %{hiera('netcfg_priv_network')} lookup private", ]
profile::base::network::manage_neutron_blackhole: true

# IPv6 is enabled for bgp, bfd
profile::openstack::network::calico::manage_firewall6: true

################ TEMP DATA - SHOULD BE FIXED IN COMMON #########################
calico::compute::bird_template: 'profile/bird/bird.conf.erb'

nova::debug: true

# remove when telemetry/ceilometer is up in all environments and move to common
profile::openstack::compute::manage_telemetry: true

nova::compute::libvirt::libvirt_hw_machine_type: 'x86_64=q35'

# collectd
profile::monitoring::collectd::enable: true
profile::monitoring::collectd::plugins:
  - collectd::plugin::aggregation
  - collectd::plugin::cpu
  - collectd::plugin::disk
  - collectd::plugin::load
  - collectd::plugin::memory
  - collectd::plugin::interface
  - collectd::plugin::write_graphite
  - collectd::plugin::virt
  - collectd::plugin::processes

collectd::plugin::virt::hostname_format:        'hostname'
collectd::plugin::virt::plugin_instance_format: 'uuid'
