---
named_interfaces::config:
  mgmt:
    - em3
  trp:
    - bond1
  ceph:
    - bond1

profile::storage::fake_ssds:
  'sdb': {}
  'sdc': {}

profile::storage::cephosd::osds:
  '/dev/sdb': {}
  '/dev/sdc': {}
  '/dev/sdd': {}
  '/dev/sde': {}
  '/dev/sdf': {}
  '/dev/sdg': {}
