---
named_interfaces::config:
  mgmt:
    - eth0
  trp:
    - eth1
  ceph:
    - eth1

profile::base::common::manage_fake_ssd: true

profile::storage::fake_ssds:
  'vdb': {}

profile::storage::cephosd::osds:
  '/dev/vdb': {}
  '/dev/vdc': {}
  '/dev/vdd': {}
  '/dev/vde': {}
  '/dev/vdf': {}
  '/dev/vdg': {}
  '/dev/vdh': {}
  '/dev/vdi': {}
  '/dev/vdj': {}

profile::storage::cephpool::pools:
  'rbd':
    ensure: absent
  'volumes':
    ensure: present
    pg_num: 256
    pgp_num: 256
  'images':
    ensure: present
    pg_num: 256
    pgp_num: 256
  'vms':
    ensure: present
    pg_num: 64
    pgp_num: 64
