---
named_interfaces::config:
  mgmt:
    - eth0
  trp:
    - eth1
  ceph:
    - eth1

profile::base::common::manage_fake_ssd: true

profile::storage::cephfs::create_cephfs: true

profile::storage::cephpool::manage_ec_pools:        true
profile::storage::cephpool::manage_cephpool_params: true

profile::storage::cephfs::filesystems:
  'manila_hdd':
    data_pool:     "manila_data"
    metadata_pool: "manila_meta"

profile::storage::fake_ssds:
  'vdb': {}

profile::storage::cephosd::osds:
  '/dev/vdb': {}
  '/dev/vdc': {}
  '/dev/vdd': {}
  '/dev/vde': {}
  '/dev/vdf': {}
  '/dev/vdg': {}
  '/dev/vdh': {}

profile::storage::ceph_ecpool::ec_pools:
  'manila_data':
    manage:              true
    allow_ec_overwrites: true
profile::storage::cephpool::pools:
  'rbd':
    ensure: absent
  'volumes':
    ensure: present
    pg_num: 256
    pgp_num: 256
  'images':
    ensure: present
    pg_num: 256
    pgp_num: 256
  'vms':
    ensure: present
    pg_num: 64
    pgp_num: 64
  'manila_meta':
    ensure: present
    pg_num: 64
    pgp_num: 64
profile::storage::cephpool_params::pools:
  'volumes':
    replicas_min_size: 2
  'images':
    replicas_min_size: 2
  'vms':
    replicas_min_size: 2
    crush_rule:        "ssd"
  'manila_meta':
    replicas_num:      5
    replicas_min_size: 3
    crush_rule:        "ssd"
