---
named_interfaces::config:
  mgmt:
    - br0
  trp:
    - br1
  ceph:
    - br1

libvirt::qemu_vnc_listen:         '%{::ipaddress_mgmt1}'

# Turn off bird on controller until we use cumulus
profile::openstack::network::calico::manage_bird: false

# bootstrap admin-01
profile::bootstrap::himlar::libvirt:
  '%{location}-admin-01':
    domain:           "%{hiera('domain_mgmt')}"
    libvirt_pool:     'dirpool'
    libvirt_network:  'directnet'
    node_ip:          "%{hiera('netcfg_mgmt_netpart')}.11"
    node_netmask:     "%{hiera('netcfg_mgmt_netmask')}"
    node_gateway:     "%{hiera('netcfg_mgmt_gateway')}"
    vm_vcpus:         2
    vm_memory:        4096

# Create and enable more swap
profile::base::common::extraswap:        true
profile::base::common::extraswap_sizegb: 10
profile::base::common::extraswap_fileloc: '/var/lib/libvirt/images/swapfile'

# This change is needed for new libvirt module
profile::virtualization::libvirt::moduler_daemons: true
profile::virtualization::libvirt::networks:
  default:
    ensure:              absent
  directnet:
    ensure:              present
  trpnet:
    ensure:              present
