---
# Turn off bird on controller until we use cumulus
profile::openstack::network::calico::manage_bird: false

himlar_bootstrap::virt_install:
  '%{location}-admin-01':
    domain:          "%{hiera('domain_mgmt')}"
    libvirt_pool:    'dirpool'
    libvirt_network: 'directnet'
    install_ip:      "%{hiera('netcfg_mgmt_netpart')}.11"
    install_netmask: "%{hiera('netcfg_mgmt_netmask')}"
    install_gateway: "%{hiera('netcfg_mgmt_gateway')}"
    vm_vcpus:        2
    vm_memory:       4096
    vm_console:      false
    use_dhcp:        false

lvm::volume_groups:
  vg_ext:
    physical_volumes:
      - /dev/sdb
    logical_volumes:
      lv_ext:
        fs_type:   xfs
        mountpath: "/var/lib/libvirt/images"
