---
named_interfaces::config:
  mgmt:
    - em3
  trp:
    - team1
  ceph:
    - team1
  client:
    - team2

profile::base::lvm::physical_volume:
  '/dev/sdn':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_cache':
    physical_volumes:
      - /dev/sdn
profile::base::lvm::logical_volume:
  'lv_walb':
    volume_group: 'vg_cache'
    createfs:     false
    size:         2G
  'lv_dbb':
    volume_group: 'vg_cache'
    createfs:     false
    size:         4G
  'lv_walc':
    volume_group: 'vg_cache'
    createfs:     false
    size:         2G
  'lv_dbc':
    volume_group: 'vg_cache'
    createfs:     false
    size:         4G
  'lv_wald':
    volume_group: 'vg_cache'
    createfs:     false
    size:         2G
  'lv_dbd':
    volume_group: 'vg_cache'
    createfs:     false
    size:         4G
  'lv_wale':
    volume_group: 'vg_cache'
    createfs:     false
    size:         2G
  'lv_dbe':
    volume_group: 'vg_cache'
    createfs:     false
    size:         4G
  'lv_walf':
    volume_group: 'vg_cache'
    createfs:     false
    size:         2G
  'lv_dbf':
    volume_group: 'vg_cache'
    createfs:     false
    size:         4G
  'lv_walg':
    volume_group: 'vg_cache'
    createfs:     false
    size:         2G
  'lv_dbg':
    volume_group: 'vg_cache'
    createfs:     false
    size:         4G
  'lv_walh':
    volume_group: 'vg_cache'
    createfs:     false
    size:         2G
  'lv_dbh':
    volume_group: 'vg_cache'
    createfs:     false
    size:         4G
  'lv_wali':
    volume_group: 'vg_cache'
    createfs:     false
    size:         2G
  'lv_dbi':
    volume_group: 'vg_cache'
    createfs:     false
    size:         4G
  'lv_walj':
    volume_group: 'vg_cache'
    createfs:     false
    size:         2G
  'lv_dbj':
    volume_group: 'vg_cache'
    createfs:     false
    size:         4G
  'lv_walk':
    volume_group: 'vg_cache'
    createfs:     false
    size:         2G
  'lv_dbk':
    volume_group: 'vg_cache'
    createfs:     false
    size:         4G
  'lv_wall':
    volume_group: 'vg_cache'
    createfs:     false
    size:         2G
  'lv_dbl':
    volume_group: 'vg_cache'
    createfs:     false
    size:         4G
  'lv_walm':
    volume_group: 'vg_cache'
    createfs:     false
    size:         2G
  'lv_dbm':
    volume_group: 'vg_cache'
    createfs:     false
    size:         4G
  'lv_walo':
    volume_group: 'vg_cache'
    createfs:     false
    size:         2G
  'lv_dbo':
    volume_group: 'vg_cache'
    createfs:     false
    size:         4G
  'lv_walp':
    volume_group: 'vg_cache'
    createfs:     false
    size:         2G
  'lv_dbp':
    volume_group: 'vg_cache'
    createfs:     false
    size:         4G
  'lv_walq':
    volume_group: 'vg_cache'
    createfs:     false
    size:         2G
  'lv_dbq':
    volume_group: 'vg_cache'
    createfs:     false
    size:         4G
  'lv_walr':
    volume_group: 'vg_cache'
    createfs:     false
    size:         2G
  'lv_dbr':
    volume_group: 'vg_cache'
    createfs:     false
    size:         4G

profile::storage::cephosd::osds:
  '/dev/nvme0n1':
    ensure:     'present'
  '/dev/sdb':
    db_device:  'vg_cache/lv_dbb'
    wal_device: 'vg_cache/lv_walb'
  '/dev/sdc':
    db_device:  'vg_cache/lv_dbc'
    wal_device: 'vg_cache/lv_walc'
  '/dev/sdd':
    db_device:  'vg_cache/lv_dbd'
    wal_device: 'vg_cache/lv_wald'
  '/dev/sde':
    db_device:  'vg_cache/lv_dbe'
    wal_device: 'vg_cache/lv_wale'
  '/dev/sdf':
    db_device:  'vg_cache/lv_dbf'
    wal_device: 'vg_cache/lv_walf'
  '/dev/sdg':
    db_device:  'vg_cache/lv_dbg'
    wal_device: 'vg_cache/lv_walg'
  '/dev/sdh':
    db_device:  'vg_cache/lv_dbh'
    wal_device: 'vg_cache/lv_walh'
  '/dev/sdi':
    db_device:  'vg_cache/lv_dbi'
    wal_device: 'vg_cache/lv_wali'
  '/dev/sdj':
    db_device:  'vg_cache/lv_dbj'
    wal_device: 'vg_cache/lv_walj'
  '/dev/sdk':
    db_device:  'vg_cache/lv_dbk'
    wal_device: 'vg_cache/lv_walk'
  '/dev/sdl':
    db_device:  'vg_cache/lv_dbl'
    wal_device: 'vg_cache/lv_wall'
  '/dev/sdm':
    db_device:  'vg_cache/lv_dbm'
    wal_device: 'vg_cache/lv_walm'
  '/dev/sdo':
    db_device:  'vg_cache/lv_dbo'
    wal_device: 'vg_cache/lv_walo'
  '/dev/sdp':
    db_device:  'vg_cache/lv_dbp'
    wal_device: 'vg_cache/lv_walp'
  '/dev/sdq':
    db_device:  'vg_cache/lv_dbq'
    wal_device: 'vg_cache/lv_walq'
  '/dev/sdr':
    db_device:  'vg_cache/lv_dbr'
    wal_device: 'vg_cache/lv_walr'

profile::storage::cephpool::pools:
  'rbd':
    ensure: absent
