---
foreman_proxy::dhcp_range:       '192.168.10.100 192.168.10.120'
foreman_proxy::dhcp_gateway:     '192.168.10.1'
foreman_proxy::dhcp_nameservers: '129.177.6.54, 129.177.12.31'
foreman_proxy::dns_server:       '129.177.6.54'
