---

dhcp::hosts:
  bgo-leaf-01:
    mac: '00:01:e8:d8:38:aa'
    ip:  '172.16.3.1'
  bgo-leaf-02:
    mac: '00:01:e8:d8:36:e3'
    ip:  '172.16.3.2'
  bgo-leaf-03:
    mac: '00:01:e8:d8:36:61'
    ip:  '172.16.0.3'
  bgo-leaf-04:
    mac: '00:01:e8:d8:37:24'
    ip:  '172.16.0.4'
  bgo-leaf-05:
    mac: 'f8:8e:a1:f5:41:a0'
    ip:  "%{hiera('netcfg_mgmt_net_c0')}.5"
  bgo-leaf-06:
    mac: 'f8:8e:a1:f5:21:a0'
    ip:  "%{hiera('netcfg_mgmt_net_c0')}.6"
  bgo-spine-01:
    mac: '3c:2c:30:49:2f:00'
    ip:  "%{hiera('netcfg_mgmt_net_c6')}.1"
  bgo-spine-02:
    mac: '3c:2c:30:49:27:80'
    ip:  "%{hiera('netcfg_mgmt_net_c6')}.2"
  bgo-torack-01:
    mac: '68:4f:64:b2:3c:11'
    ip:  '172.16.0.1'
  bgo-torack-02:
    mac: '14:18:77:01:22:00'
    ip:  '172.16.0.2'
  bgo-mgmt-opx-01:
    mac: '3c:2c:30:33:fa:80'
    ip:  '172.16.2.1'
  bgo-mgmt-opx-02:
    mac: '3c:2c:30:33:de:80'
    ip:  '172.16.2.2'
  bgo-mgmt-opx-03:
    mac: '3c:2c:30:33:f8:80'
    ip:  '172.16.2.3'
  bgo-mgmt-opx-04:
    mac: '34:17:eb:32:45:80'
    ip:  '172.16.2.4'
  bgo-mgmt-opx-05:
    mac: '8c:04:ba:b2:b3:40'
    ip:  '172.16.2.5'
  bgo-mgmt-opx-06:
    mac: '8c:04:ba:b2:a1:40'
    ip:  '172.16.2.6'
  bgo-mgmt-opx-07:
    mac: '0c:29:ef:d8:32:20'
    ip:  '172.16.2.7'
  bgo-mgmt-opx-08:
    mac: '74:86:e2:ab:a4:a5'
    ip: '172.16.2.8'
  bgo-mgmt-opx-09:
    mac: '0c:29:ef:d6:37:20'
    ip:  '172.16.2.9'
  bgo-cephmon-01-bmc:
    mac: 'b8:2a:72:fc:4c:7e'
    ip:  '172.17.0.91'
  bgo-cephmon-02-bmc:
    mac: 'b8:2a:72:fc:46:d4'
    ip:  '172.17.0.92'
  bgo-cephmon-03-bmc:
    mac: 'b8:2a:72:fc:42:92'
    ip:  '172.17.0.93'
  bgo-compute-01-bmc:
    mac: 'b8:2a:72:fc:71:32'
    ip:  '172.17.0.103'
  bgo-compute-02-bmc:
    mac: 'b8:2a:72:fc:70:34'
    ip:  '172.17.0.104'
  bgo-compute-03-bmc:
    mac: 'b8:2a:72:fc:73:36'
    ip:  '172.17.0.105'
  bgo-compute-04-bmc:
    mac: '84:7b:eb:d6:b7:1a'
    ip:  '172.17.0.111'
  bgo-compute-05-bmc:
    mac: '84:7b:eb:d6:b6:f2'
    ip:  '172.17.0.112'
  bgo-compute-06-bmc:
    mac: '84:7b:eb:d6:b2:2e'
    ip:  '172.17.0.113'
  bgo-compute-07-bmc:
    mac: 'f8:ca:b8:8c:ef:a0'
    ip:  '172.17.0.115'
  bgo-compute-08-bmc:
    mac: 'f8:ca:b8:8c:ef:ad'
    ip:  '172.17.0.116'
  bgo-compute-09-bmc:
    mac: 'f8:ca:b8:8c:ef:ba'
    ip:  '172.17.0.117'
  bgo-compute-10-bmc:
    mac: 'f8:ca:b8:8c:ef:c7'
    ip:  '172.17.0.118'
  bgo-compute-11-bmc:
    'mac': '4c:d9:8f:1c:09:1c'
    'ip':  '172.17.1.11'
  bgo-compute-12-bmc:
    'mac': '4c:d9:8f:1c:09:52'
    'ip':  '172.17.1.12'
  bgo-compute-13-bmc:
    'mac': '4c:d9:8f:1c:0b:e0'
    'ip':  '172.17.1.13'
  bgo-compute-14-bmc:
    'mac': '4c:d9:8f:1c:0b:80'
    'ip':  '172.17.1.14'
  bgo-compute-15-bmc:
    'mac': '4c:d9:8f:1c:06:5e'
    'ip':  '172.17.1.15'
  bgo-compute-16-bmc:
    'mac': '4c:d9:8f:1c:0f:04'
    'ip':  '172.17.1.16'
  bgo-compute-17-bmc:
    'mac': '4c:d9:8f:1c:0a:78'
    'ip':  '172.17.1.17'
  bgo-compute-18-bmc:
    'mac': '4c:d9:8f:1c:0a:d8'
    'ip':  '172.17.1.18'
  bgo-compute-19-bmc:
    'mac': '4c:d9:8f:1c:0a:54'
    'ip':  '172.17.1.19'
  bgo-compute-20-bmc:
    'mac': '4c:d9:8f:1c:05:86'
    'ip':  '172.17.1.20'
  bgo-compute-21-bmc:
    'mac': '4c:d9:8f:1c:0f:88'
    'ip':  '172.17.1.21'
  bgo-compute-22-bmc:
    'mac': '4c:d9:8f:1c:05:14'
    'ip':  '172.17.1.22'
  bgo-compute-23-bmc:
    'mac': '4c:d9:8f:1c:08:ce'
    'ip':  '172.17.1.23'
  bgo-compute-24-bmc:
    'mac': '4c:d9:8f:1c:06:22'
    'ip':  '172.17.1.24'
  bgo-compute-25-bmc:
    'mac': '4c:d9:8f:1c:0b:e6'
    'ip':  '172.17.1.25'
  bgo-compute-26-bmc:
    'mac': '4c:d9:8f:1c:07:2a'
    'ip':  '172.17.1.26'
  bgo-compute-27-bmc:
    'mac': '4c:d9:8f:1c:0f:7c'
    'ip':  '172.17.1.27'
  bgo-compute-28-bmc:
    'mac': '4c:d9:8f:1c:05:62'
    'ip':  '172.17.1.28'
  bgo-compute-29-bmc:
    'mac': '4c:d9:8f:1c:0c:34'
    'ip':  '172.17.1.29'
  bgo-compute-30-bmc:
    'mac': '4c:d9:8f:1c:0b:aa'
    'ip':  '172.17.1.30'
  bgo-compute-31-bmc:
    'mac': '4c:d9:8f:1c:0e:02'
    'ip':  '172.17.1.31'
  bgo-compute-32-bmc:
    'mac': '4c:d9:8f:1c:0f:e8'
    'ip':  '172.17.1.32'
  bgo-compute-33-bmc:
    'mac': '4c:d9:8f:1c:07:8a'
    'ip':  '172.17.1.33'
  bgo-compute-34-bmc:
    'mac': '4c:d9:8f:1c:04:e4'
    'ip':  '172.17.1.34'
  bgo-compute-35-bmc:
    'mac': '4c:d9:8f:a4:11:7c'
    'ip':  '172.17.1.35'
  bgo-compute-36-bmc:
    'mac': 'f4:02:70:d1:e7:e8'
    'ip':  '172.17.1.36'
  bgo-compute-37-bmc:
    'mac': 'f4:02:70:d1:e8:cc'
    'ip':  '172.17.1.37'
  bgo-compute-38-bmc:
    'mac': 'f4:02:70:c1:59:36'
    'ip':  '172.17.1.38'
  bgo-compute-39-bmc:
    'mac': 'f4:02:70:c1:58:46'
    'ip':  '172.17.1.39'
  bgo-compute-40-bmc:
    'mac': 'f4:02:70:c0:de:d8'
    'ip':  '172.17.1.40'
  bgo-compute-41-bmc:
    'mac': 'f4:02:70:d8:c3:42'
    'ip':  '172.17.1.41'
  bgo-compute-42-bmc:
    'mac': 'f4:02:70:d8:c7:c8'
    'ip':  '172.17.1.42'
  bgo-compute-43-bmc:
    'mac': 'f4:02:70:d8:ca:6e'
    'ip':  '172.17.1.43'
  bgo-compute-44-bmc:
    'mac': 'f4:02:70:dd:21:02'
    'ip':  '172.17.1.44'
  bgo-compute-45-bmc:
    'mac': 'f4:02:70:d3:f9:3e'
    'ip':  '172.17.1.45'
  bgo-compute-46-bmc:
    'mac': 'f4:02:70:d8:cc:30'
    'ip':  '172.17.1.46'
  bgo-compute-47-bmc:
    'mac': 'f4:02:70:d3:fb:5a'
    'ip':  '172.17.1.47'
  bgo-compute-48-bmc:
    'mac': 'f4:02:70:d3:f9:14'
    'ip':  '172.17.1.48'
  bgo-compute-49-bmc:
    'mac': 'f4:02:70:d3:f7:64'
    'ip':  '172.17.1.49'
  bgo-compute-50-bmc:
    'mac': 'f4:02:70:d3:f9:80'
    'ip':  '172.17.1.82'
  bgo-compute-51-bmc:
    'mac': 'f4:02:70:d3:f8:00'
    'ip':  '172.17.1.83'
  bgo-compute-52-bmc:
    'mac': '4c:d9:8f:b5:ea:71'
    'ip':  '172.17.1.84'
  bgo-compute-53-bmc:
    'mac': '70:b5:e8:df:ef:96'
    'ip':  '172.17.1.85'
  bgo-compute-54-bmc:
    'mac': '70:b5:e8:df:f9:38'
    'ip':  '172.17.1.86'
  bgo-compute-55-bmc:
    'mac': '70:b5:e8:e9:32:1a'
    'ip':  '172.17.1.87'
  bgo-compute-56-bmc:
    'mac': '70:b5:e8:e9:33:5e'
    'ip':  '172.17.1.88'
  bgo-compute-57-bmc:
    'mac': '70:b5:e8:e9:32:50'
    'ip':  '172.17.1.89'
  bgo-compute-58-bmc:
    'mac': '2c:ea:7f:fa:a7:28'
    'ip':  '172.17.1.90'
  bgo-compute-59-bmc:
    'mac': '2c:ea:7f:fb:ff:52'
    'ip':  '172.17.1.91'
  bgo-compute-60-bmc:
    'mac': '2c:ea:7f:fb:4b:76'
    'ip':  '172.17.1.92'
  bgo-compute-61-bmc:
    'mac': 'ec:2a:72:01:84:ce'
    'ip':  '172.17.1.122'
  bgo-compute-62-bmc:
    'mac': 'ec:2a:72:01:8f:00'
    'ip':  '172.17.1.123'
  bgo-compute-63-bmc:
    'mac': 'ec:2a:72:01:8f:48'
    'ip':  '172.17.1.124'
  bgo-compute-64-bmc:
    'mac': 'ec:2a:72:01:92:84'
    'ip':  '172.17.1.125'
  bgo-compute-65-bmc:
    'mac': 'ec:2a:72:01:83:00'
    'ip':  '172.17.1.126'
  bgo-compute-66-bmc:
    'mac': 'b0:7b:25:fc:77:a0'
    'ip':  '172.17.1.127'
  bgo-compute-67-bmc:
    'mac': 'ec:2a:72:11:93:c0'
    'ip':  '172.17.1.128'
  bgo-compute-68-bmc:
    'mac': 'ec:2a:72:11:92:a6'
    'ip':  '172.17.1.129'
  bgo-compute-69-bmc:
    'mac': 'ec:2a:72:11:84:a2'
    'ip':  '172.17.1.130'
  bgo-compute-70-bmc:
    'mac': 'b0:7b:25:fc:74:5e'
    'ip':  '172.17.1.131'
  bgo-compute-71-bmc:
    'mac': 'ec:2a:72:1e:95:b2'
    'ip':  '172.17.1.132'
  bgo-compute-72-bmc:
    'mac': 'ec:2a:72:15:3f:fe'
    'ip':  '172.17.1.133'
  bgo-compute-73-bmc:
    'mac': 'ec:2a:72:1e:95:c4'
    'ip':  '172.17.1.134'
  bgo-compute-74-bmc:
    'mac': 'ec:2a:72:1e:9c:8a'
    'ip':  '172.17.1.135'
  bgo-compute-75-bmc:
    'mac': 'ec:2a:72:15:40:e2'
    'ip':  '172.17.1.136'
  bgo-compute-76-bmc:
    'mac': 'ec:2a:72:15:41:06'
    'ip':  '172.17.1.137'
  bgo-compute-77-bmc:
    'mac': 'ec:2a:72:15:36:68'
    'ip':  '172.17.1.138'
  bgo-compute-78-bmc:
    'mac': 'b0:7b:25:e5:b4:ee'
    'ip':  '172.17.1.139'
  bgo-compute-79-bmc:
    'mac': 'ec:2a:72:1e:84:42'
    'ip':  '172.17.1.140'
  bgo-compute-80-bmc:
    'mac': 'ec:2a:72:15:41:8a'
    'ip':  '172.17.1.141'
  bgo-compute-81-bmc:
    'mac': 'd0:8e:79:c3:d0:cc'
    'ip':  '172.17.1.142'
  bgo-compute-82-bmc:
    'mac': 'c4:cb:e1:b1:1c:92'
    'ip':  '172.17.1.143'
  bgo-compute-83-bmc:
    'mac': 'c4:cb:e1:b1:2a:cc'
    'ip':  '172.17.1.144'
  bgo-compute-84-bmc:
    'mac': 'c4:cb:e1:b1:1b:b4'
    'ip':  '172.17.1.145'
  bgo-compute-85-bmc:
    'mac': 'c4:cb:e1:b1:32:7c'
    'ip': '172.17.1.146'
  bgo-compute-86-bmc:
    'mac': 'c4:cb:e1:b5:11:66'
    'ip': '172.17.1.147'
  bgo-compute-87-bmc:
    'mac': 'c4:cb:e1:b5:12:1a'
    'ip': '172.17.1.148'  
  bgo-compute-88-bmc:
    'mac': 'c4:cb:e1:c2:ed:4a'
    'ip':  '172.17.1.149'
  bgo-compute-89-bmc:
    'mac': 'c4:cb:e1:c2:ed:74'
    'ip':  '172.17.1.150'
  bgo-compute-90-bmc:
    'mac': 'c4:cb:e1:c2:ea:aa'
    'ip':  '172.17.1.151'
  bgo-compute-91-bmc:
    'mac': 'c4:cb:e1:c2:ee:22'
    'ip':  '172.17.1.152'
  bgo-compute-92-bmc:
    'mac': 'c0:47:0e:e1:2d:21'
    'ip':  '172.17.1.153'
  bgo-compute-93-bmc:
    'mac': 'c4:ef:bb:1f:9e:4e'
    'ip':  '172.17.1.154'
  bgo-compute-94-bmc:
    'mac': 'c4:ef:bb:23:29:9a'
    'ip':  '172.17.1.155'
  bgo-compute-95-bmc:
    'mac': 'c4:cb:e1:de:3c:70'
    'ip':  '172.17.1.156'
  bgo-compute-96-bmc:
    'mac': 'c4:cb:e1:ac:f9:50'
    'ip':  '172.17.1.157'
  bgo-compute-97-bmc:
    'mac': 'c4:cb:e1:ac:f9:f8'
    'ip':  '172.17.1.158'
  bgo-controller-04-bmc:
    mac: 'b0:83:fe:e9:01:a5'
    ip:  '172.17.0.114'
  bgo-controller-05-bmc:
    mac: 'f4:02:70:c1:56:e4'
    ip:  '172.17.0.126'
  bgo-controller-06-bmc:
    mac: 'f4:02:70:c1:57:08'
    ip:  '172.17.0.127'
  bgo-controller-07-bmc:
    mac: 'f4:02:70:c1:57:44'
    ip:  '172.17.0.128'
  bgo-controller-08-bmc:
    mac: '2c:ea:7f:f4:51:08'
    ip:  '172.17.0.129'
  bgo-object-01-bmc:
    mac: '50:9a:4c:a9:97:0e'
    ip:  '172.17.0.119'
  bgo-object-02-bmc:
    mac: '50:9a:4c:a9:77:fa'
    ip:  '172.17.0.120'
  bgo-object-03-bmc:
    mac: '50:9a:4c:a9:90:a8'
    ip:  '172.17.0.121'
  bgo-object-04-bmc:
    mac: '50:9a:4c:a9:95:76'
    ip:  '172.17.0.122'
  bgo-object-05-bmc:
    mac: '50:9a:4c:a9:90:b4'
    ip:  '172.17.0.123'
  bgo-storage-04-bmc:
    mac: '18:fb:7b:99:4f:da'
    ip:  '172.17.0.109'
  bgo-storage-05-bmc:
    mac: '18:fb:7b:99:4f:fe'
    ip:  '172.17.0.110'
  bgo-storage-06-bmc:
    mac: '58:8a:5a:e8:e8:b0'
    ip:  '172.17.0.124'
  bgo-storage-07-bmc:
    mac: '58:8a:5a:e8:ef:e2'
    ip:  '172.17.0.125'
  bgo-storage-08-bmc:
    mac: '4c:d9:8f:29:d4:a0'
    ip:  '172.17.1.50'
  bgo-storage-09-bmc:
    mac: '4c:d9:8f:29:d4:d0'
    ip:  '172.17.1.51'
  bgo-storage-10-bmc:
    mac: '4c:d9:8f:1a:59:50'
    ip:  '172.17.1.52'
  bgo-storage-11-bmc:
    mac: '4c:d9:8f:1a:9a:ae'
    ip:  '172.17.1.53'
  bgo-storage-12-bmc:
    mac: '4c:d9:8f:1a:51:be'
    ip:  '172.17.1.54'
  bgo-storage-13-bmc:
    mac: '4c:d9:8f:1a:51:ac'
    ip:  '172.17.1.55'
  bgo-storage-14-bmc:
    mac: '4c:d9:8f:1a:51:ca'
    ip:  '172.17.1.56'
  bgo-storage-15-bmc:
    mac: '4c:d9:8f:1a:5c:62'
    ip:  '172.17.1.57'
  bgo-storage-16-bmc:
    mac: '4c:d9:8f:1a:5b:7e'
    ip:  '172.17.1.58'
  bgo-storage-17-bmc:
    mac: '4c:d9:8f:1a:56:da'
    ip:  '172.17.1.59'
  bgo-storage-18-bmc:
    mac: '4c:d9:8f:1a:56:86'
    ip:  '172.17.1.60'
  bgo-storage-19-bmc:
    mac: '4c:d9:8f:1a:36:d0'
    ip:  '172.17.1.61'
  bgo-storage-20-bmc:
    mac: '4c:d9:8f:18:a5:c6'
    ip:  '172.17.1.62'
  bgo-storage-21-bmc:
    mac: '4c:d9:8f:1a:56:d4'
    ip:  '172.17.1.63'
  bgo-storage-22-bmc:
    mac: '4c:d9:8f:1a:56:b6'
    ip:  '172.17.1.64'
  bgo-storage-23-bmc:
    mac: '4c:d9:8f:1a:58:6c'
    ip:  '172.17.1.65'
  bgo-storage-24-bmc:
    mac: '4c:d9:8f:1a:58:72'
    ip:  '172.17.1.66'
  bgo-storage-25-bmc:
    mac: '4c:d9:8f:1a:07:c0'
    ip:  '172.17.1.67'
  bgo-storage-26-bmc:
    mac: '4c:d9:8f:2b:28:fc'
    ip:  '172.17.1.68'
  bgo-storage-27-bmc:
    mac: '4c:d9:8f:2b:28:e4'
    ip:  '172.17.1.69'
  bgo-storage-28-bmc:
    mac: '4c:d9:8f:2b:29:d4'
    ip:  '172.17.1.70'
  bgo-storage-29-bmc:
    mac: '4c:d9:8f:2b:29:fe'
    ip:  '172.17.1.71'
  bgo-storage-30-bmc:
    mac: '4c:d9:8f:2b:28:ba'
    ip:  '172.17.1.72'
  bgo-storage-31-bmc:
    mac: '4c:d9:8f:1a:07:72'
    ip:  '172.17.1.73'
  bgo-storage-32-bmc:
    mac: '4c:d9:8f:1a:01:5a'
    ip:  '172.17.1.74'
  bgo-storage-33-bmc:
    mac: '4c:d9:8f:1a:07:ba'
    ip:  '172.17.1.75'
  bgo-storage-34-bmc:
    mac: '4c:d9:8f:1a:06:b2'
    ip:  '172.17.1.76'
  bgo-storage-35-bmc:
    mac: 'f4:02:70:c9:41:60'
    ip:  '172.17.1.77'
  bgo-storage-36-bmc:
    mac: 'f4:02:70:c8:88:74'
    ip:  '172.17.1.78'
  bgo-storage-37-bmc:
    mac: 'f4:02:70:c9:40:88'
    ip:  '172.17.1.79'
  bgo-storage-38-bmc:
    mac: 'f4:02:70:c9:41:12'
    ip:  '172.17.1.80'
  bgo-storage-39-bmc:
    mac: 'f4:02:70:c9:09:38'
    ip:  '172.17.1.81'
  bgo-storage-40-bmc:
    mac: '70:b5:e8:df:d6:ca'
    ip:  '172.17.1.93'
  bgo-storage-41-bmc:
    mac: '70:b5:e8:df:d4:84'
    ip:  '172.17.1.94'
  bgo-storage-42-bmc:
    mac: '70:b5:e8:df:d6:e8'
    ip:  '172.17.1.95'
  bgo-storage-43-bmc:
    mac: '70:b5:e8:df:d6:88'
    ip:  '172.17.1.96'
  bgo-storage-44-bmc:
    mac: 'ec:2a:72:0c:04:9a'
    ip:  '172.17.1.97'
  bgo-storage-45-bmc:
    mac: 'b0:7b:25:fd:5d:20'
    ip:  '172.17.1.98'
  bgo-storage-46-bmc:
    mac: 'b0:7b:25:fd:a6:ee'
    ip:  '172.17.1.99'
  bgo-storage-47-bmc:
    mac: 'ec:2a:72:0c:04:dc'
    ip:  '172.17.1.100'
  bgo-storage-48-bmc:
    mac: 'ec:2a:72:0c:05:a2'
    ip:  '172.17.1.101'
  bgo-storage-49-bmc:
    mac: 'b0:7b:25:fd:61:16'
    ip:  '172.17.1.102'
  bgo-storage-50-bmc:
    mac: 'ec:2a:72:0c:04:46'
    ip:  '172.17.1.103'
  bgo-storage-51-bmc:
    mac: 'ec:2a:72:0c:04:10'
    ip:  '172.17.1.104'
  bgo-storage-52-bmc:
    mac: 'b0:7b:25:fe:24:22'
    ip:  '172.17.1.105'
  bgo-storage-53-bmc:
    mac: 'b0:7b:25:fe:37:6c'
    ip:  '172.17.1.106'
  bgo-storage-54-bmc:
    mac: 'b0:7b:25:fe:37:90'
    ip:  '172.17.1.107'
  bgo-storage-55-bmc:
    mac: 'ec:2a:72:0f:7a:c4'
    ip:  '172.17.1.108'
  bgo-storage-56-bmc:
    mac: 'ec:2a:72:0e:87:a6'
    ip:  '172.17.1.109'
  bgo-storage-57-bmc:
    mac: 'ec:2a:72:0f:83:ca'
    ip:  '172.17.1.110'
  bgo-storage-58-bmc:
    mac: 'ec:2a:72:0f:84:a8'
    ip:  '172.17.1.111'
  bgo-storage-59-bmc:
    mac: 'ec:2a:72:0f:7c:4a'
    ip:  '172.17.1.112'
  bgo-storage-60-bmc:
    mac: 'ec:2a:72:0f:85:fe'
    ip:  '172.17.1.113'
  bgo-storage-61-bmc:
    mac: 'ec:2a:72:0f:85:2c'
    ip:  '172.17.1.114'
  bgo-storage-62-bmc:
    mac: 'ec:2a:72:0f:84:18'
    ip:  '172.17.1.115'
  bgo-storage-63-bmc:
    mac: 'ec:2a:72:0f:83:e2'
    ip:  '172.17.1.116'
  bgo-storage-64-bmc:
    mac: 'ec:2a:72:0f:7f:b6'
    ip:  '172.17.1.117'
  bgo-storage-65-bmc:
    mac: 'ec:2a:72:0b:fb:dc'
    ip:  '172.17.1.118'
  bgo-storage-66-bmc:
    mac: 'b0:7b:25:fd:a2:3e'
    ip:  '172.17.1.119'
  bgo-storage-67-bmc:
    mac: 'b0:7b:25:fd:61:10'
    ip:  '172.17.1.120'
  bgo-storage-68-bmc:
    mac: 'b0:7b:25:fd:a6:88'
    ip:  '172.17.1.121'
  bgo-chassis-01-cmc:
    mac: 'f4:8e:38:c0:4f:30'
    ip:  '172.17.7.254'
