---
include:
  default:
    - nova::compute::vgpu
    - profile::application::create_mdev

named_interfaces::config:
  mgmt:
    - em3
  trp:
    - team1
  live:
    - team1.120

profile::base::network::network_auto_bonding:
  trp:
    p3p1:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'
    p3p2:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'

profile::base::network::network_auto_opts:
  mgmt:
    'defroute': 'no'
  trp:
    'defroute': 'no'
    'ipv6init': 'yes'
    'devicetype': 'Team'
    'mtu': '9000'
    'team_config': >-
                   { "runner" : {  "name" : "lacp",  "active": true, "fast_rate" : true,
                   "tx_hash": ["eth", "ipv4", "ipv6"], "tx_balancer": { "name": "basic" } },
                   "link_watch" : {  "name" : "ethtool" } }
  live:
    'defroute': 'no'

# Enable extra yum repo vGPU drivers
profile::base::yumrepo::repo_hash:
  uh-iaas-nonfree:
    ensure: present

profile::base::common::packages:
  'wget': {}
  'kernel-devel': {}
  'kernel-headers': {}
  'unzip': {}
  'NVIDIA-vGPU-rhel': {
#    source: 'http://repo.mgmt.bgo.uhdc.no/NVIDIA-vGPU-rhel-7.8-450.55.x86_64.rpm'
  }

# Example: 'nvidia-35' or ['nvidia-35', 'nvidia-36']
# valid profiles for vcomputeserver are 299, 300, 301 for 4, 2, 1 partitions respectively
nova::compute::vgpu::vgpu_types_device_addresses_mapping: { 'nvidia-300', }

# Configuration values for the "create-mdev" service
profile::application::create_mdev::enable:                true
profile::application::create_mdev::nvidia_gpu_type:       'nvidia-300'
profile::application::create_mdev::max_instances_per_gpu: 2

#yum_base_mirror:    'https://download.iaas.uio.no/uh-iaas/vgpu'

# remove when telemetry/ceilometer is up in all environments and move to common
profile::openstack::compute::manage_telemetry: true

profile::base::physical::blacklist_drv: true
profile::base::physical::blacklist_drv_list:
  'nouveau': {}

nova::compute::libvirt::libvirt_cpu_model: 'Skylake-Server-IBRS'

# These compute host uses local storage for instances
nova::compute::rbd::ephemeral_storage: false
nova::config::nova_config:
  libvirt/images_type:
    value: default
  DEFAULT/metadata_workers:
    value: '4'
  libvirt/remote_filesystem_transport:
    value: 'rsync'
