---
named_interfaces::config:
  mgmt:
    - em3
  transport:
    - em1
    - em2
  service:
    - em1

ntp::servers:
  - 172.16.0.100
  - 172.16.0.101
  - 172.16.0.102

profile::base::network::manage_httpproxy: 'true'
profile::base::network::http_proxy:       "%{hiera('service__address__proxy')}:8888"

puppet::cron_cmd: "if [ -e /etc/profile.d/proxy.sh ] ; then source /etc/profile.d/proxy.sh ; fi ; \
  /usr/bin/env puppet agent --config %{puppet::dir}/puppet.conf --onetime --no-daemonize"
  