---
profile::monitoring::collectd::enable: false

# Turn off nested virtualization
profile::virtualization::nested::manage: false

profile::base::common::packages:
  'numactl': {}

# Enable hugepages to prevent OOM-killer when using NUMA
profile::base::physical::enable_hugepages: true
# Number and size of hugepages, based on 512GB - 32 GB (4GB free pr node)
profile::base::physical::hugepagesz:       '2M'
profile::base::physical::hugepages:        '245760'
# Isolate the following CPUs from the kernel's balancing scheduler
#profile::base::physical::enable_isolcpus: true
#profile::base::physical::isolcpus: [ 0,1,2,3,4,5,7,8,9,10,11,12,13,15,16,17,18,19,20,21,23,24,25,26,27,28,29,31,32,33,34,35,36,37,39,40,41,42,43,44,45,47,48,49,50,51,52,53,55,56,57,58,59,60,61,63,64,65,66,67,68,69,71,72,73,74,75,76,77,79,80,81,82,83,84,85,87,88,89,90,91,92,93,95,96,97,98,99,100,101,103,104,105,106,107,108,109,111,112,113,114,115,116,117,119,120,121,122,123,124,125,127 ]

# Reserve the same CPUs for virtual machines
#nova::compute::vcpu_pin_set: [ 0,1,2,3,4,5,7,8,9,10,11,12,13,15,16,17,18,19,20,21,23,24,25,26,27,28,29,31,32,33,34,35,36,37,39,40,41,42,43,44,45,47,48,49,50,51,52,53,55,56,57,58,59,60,61,63,64,65,66,67,68,69,71,72,73,74,75,76,77,79,80,81,82,83,84,85,87,88,89,90,91,92,93,95,96,97,98,99,100,101,103,104,105,106,107,108,109,111,112,113,114,115,116,117,119,120,121,122,123,124,125,127 ]

# Nover overrides
nova::compute::libvirt::cpu_models: ['EPYC']
nova::cpu_allocation_ratio:                '1'

# Create and enable more swap
profile::base::common::extraswap:        true
profile::base::common::extraswap_sizegb: 10

profile::base::lvm::physical_volume:
  '/dev/sda3':
    ensure: present
    force:  true
  '/dev/nvme0n1':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_instances':
    physical_volumes:
      - /dev/nvme0n1
profile::base::lvm::logical_volume:
  'lv_instances':
    volume_group: 'vg_instances'
    fs_type:      "xfs"
    mountpath:    "/var/lib/nova/instances"

profile::base::network::network_auto_opts:
  mgmt:
    'defroute': 'no'
  trp:
    'defroute': 'no'
    'ipv6init': 'yes'
    'devicetype': 'Team'
    'mtu': '9000'
    'team_config': >-
                   { "runner" : {  "name" : "lacp",  "active": true, "fast_rate" : true,
                   "tx_hash": ["eth", "ipv4", "ipv6"], "tx_balancer": { "name": "basic" } },
                   "link_watch" : {  "name" : "ethtool" } }
  live:
    'defroute': 'no'

profile::base::network::network_auto_bonding:
  trp:
    p2p1:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'
    p2p2:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'

# These compute host uses local storage for instances
nova::compute::rbd::ephemeral_storage: false

# Configuration items not explicitly supported by the Puppet module
nova::config::nova_config:
  libvirt/images_type:
    value: default
  DEFAULT/metadata_workers:
    value: '2'
  # Use rsync, not ssh for migrate transport to support sparse images
  libvirt/remote_filesystem_transport:
    value: 'rsync'
  # From 2023.1 onwards these can be configured properly
  libvirt/live_migration_downtime:
    value: '1000'
  libvirt/live_migration_downtime_steps:
    value: '20'
  libvirt/live_migration_downtime_delay:
    value: '10'

sensu__memory__check:     "check-memory.rb -w 2048 -c 1024"

# Red Hat Subscription Management (RHSM)
profile::rhsm::subscription::manage: false
profile::rhsm::virtwho::manage:      false
