---
profile::base::network::network_auto_bonding:
  trp:
    em3:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'
    em4:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'

# Do not use ceph cluster for instance disk
nova::compute::rbd::ephemeral_storage: false

# Nova overrides
nova::compute::libvirt::libvirt_cpu_model:       'EPYC'
nova::cpu_allocation_ratio:                      '8'
nova::disk_allocation_ratio:                     '2'
nova::ram_allocation_ratio:                      '1.4'
nova::scheduler::filter::max_instances_per_host: '20'
