---
ntp::servers:
  - 172.16.0.126
  - 172.16.0.127
  - 172.16.0.128
chrony::servers:
  - "%{hiera('netcfg_mgmt_netpart')}.126"
  - "%{hiera('netcfg_mgmt_netpart')}.127"
  - "%{hiera('netcfg_mgmt_netpart')}.128"

# EL9 routing for this region
network::routing::table::tables:
  'private':
    'table_id':  '240'
  'lhc':
    'table_id':  '241'
  'lhc-private':
    'table_id':  '242'
  'uib':
    'table_id':  '243'

profile::base::network::nm_auto_routes:
  trp:
    ipv4: # 7 ipv4 routes in bgo
      # default NAT
      route1: "0.0.0.0/0,%{hiera('netcfg_priv_gateway')}"
      route1_options: 'table=240'
      # Elastic IP
      route2: "%{hiera('netcfg_priv_anycast_net')}/%{hiera('netcfg_priv_anycast_cidr4')},%{hiera('netcfg_trp_gateway')}"
      route2_options: 'table=240'
      # TSM cern
      route3: "192.168.243.0/24,%{hiera('netcfg_trp_gateway')}"
      route3_options: 'table=241'
      # LHC network
      route4: "0.0.0.0/0,%{hiera('netcfg_lhc_gateway')}"
      route4_options: 'table=241'
      # LHC priv network
      route5: "0.0.0.0/0,%{hiera('netcfg_lhcpriv_gateway')}"
      route5_options: 'table=242'
      # uib-dualStack
      route6: "129.177.0.0/16,%{hiera('netcfg_uib_gateway')}"
      route6_options: 'table=243'
      # default route
      route7: "0.0.0.0/0,%{hiera('netcfg_trp_gateway')}"
      # IPv4 Rules
      routing-rule1: "priority 5 from %{hiera('netcfg_priv_network')} lookup 240"
      routing-rule2: "priority 5 from %{hiera('netcfg_elastic_cidr')} lookup 240"
      routing-rule3: "priority 5 from %{hiera('netcfg_uio_priv1_network')} lookup 240"
      routing-rule4: "priority 5 from %{hiera('netcfg_educloud1_network')} lookup 240"
      routing-rule5: "priority 5 from %{hiera('netcfg_lhc_network')} lookup 241"
      routing-rule6: "priority 5 from %{hiera('netcfg_lhcpriv_network')} lookup 242"
      routing-rule7: "priority 5 from 158.37.64.0/24 to %{hiera('netcfg_uib_network')} lookup 243"
    ipv6: # 3 ipv6 routes in bgo
      # LHC
      route1: "::/0,%{hiera('netcfg_lhc_gateway6')}"
      route1_options: 'table=241'
      # UiB
      route2: "2001:700:200::/48,%{hiera('netcfg_uib_gateway6')}"
      route2_options: 'table=243'
      # default route
      route3: "::/0,%{hiera('netcfg_trp_gateway6')}"
      # IPv6 Rules
      routing-rule1: "priority 5 from %{hiera('netcfg_lhc_network6')} lookup 241"
      routing-rule2: "priority 5 from %{hiera('netcfg_lhc2_network6')} lookup 241"
      routing-rule3: "priority 5 from 2001:700:2:8302::/64 to %{hiera('netcfg_uib_network6')} lookup 243"

# el8 auto config
profile::base::network::network_auto_opts:
  mgmt:
    'defroute': 'no'
  trp:
    'defroute': 'no'
    'ipv6init': 'yes'
    'devicetype': 'Team'
    'mtu': '9000'
    'team_config': >-
                   { "runner" : {  "name" : "lacp",  "active": true, "fast_rate" : true,
                   "tx_hash": ["eth", "ipv4", "ipv6"], "tx_balancer": { "name": "basic" } },
                   "link_watch" : {  "name" : "ethtool" } }
  live:
    'defroute': 'no'

profile::base::network::network_auto_bonding:
  trp:
    em1:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'
    em2:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'

# IPv6 is enabled for bgp, bfd
profile::openstack::network::calico::manage_firewall6: true

# Add custom routing table for private network to NAT, lhc to other gw
profile::base::network::routes:
  team1:
    ipaddress:
      - '0.0.0.0'
      - "%{hiera('netcfg_priv_anycast_net')}"
      - '192.168.243.0'
      - '0.0.0.0'
      - '0.0.0.0'
      - '0.0.0.0'
      - '::'
      - '129.177.0.0'
      - '2001:700:200::'
    netmask:
      - '0.0.0.0'
      - "%{hiera('netcfg_priv_anycast_cidr4')}"
      - '255.255.255.0'
      - '0.0.0.0'
      - '0.0.0.0'
      - '0.0.0.0'
      - '0'
      - '255.255.0.0'
      - '48'
    gateway:
      - "%{hiera('netcfg_priv_gateway')}"
      - "%{hiera('netcfg_trp_gateway')}"
      - "%{hiera('netcfg_trp_gateway')}"
      - "%{hiera('netcfg_trp_gateway')}"
      - "%{hiera('netcfg_lhc_gateway')}"
      - "%{hiera('netcfg_lhcpriv_gateway')}"
      - "%{hiera('netcfg_lhc_gateway6')}"
      - "%{hiera('netcfg_uib_gateway')}"
      - "%{hiera('netcfg_uib_gateway6')}"
    table:
      - 'private'
      - 'private'
      - 'lhc'
      - 'main'
      - 'lhc'
      - 'lhc-private'
      - 'lhc'
      - 'uib'
      - 'uib'
    family:
      - 'inet4'
      - 'inet4'
      - 'inet4'
      - 'inet4'
      - 'inet4'
      - 'inet4'
      - 'inet6'
      - 'inet4'
      - 'inet6'
profile::base::network::routing_tables:
  'private':
    'table_id':  '240'
  'lhc':
    'table_id':  '241'
  'lhc-private':
    'table_id':  '242'
  'uib':
    'table_id':  '243'
profile::base::network::rules:
  'team1':
    'iprule':  [ "from %{hiera('netcfg_priv_network')} lookup private", "from %{hiera('netcfg_lhc_network')} lookup lhc", "from %{hiera('netcfg_lhcpriv_network')} lookup lhc-private", "from 158.37.64.0/24 to %{hiera('netcfg_uib_network')} lookup uib", "from %{hiera('netcfg_educloud1_network')} lookup private", "from %{hiera('netcfg_uio_priv1_network')} lookup private", "from %{hiera('netcfg_elastic_cidr')} lookup private", ]
    'iprule6': [ "from %{hiera('netcfg_lhc_network6')} lookup lhc", "from %{hiera('netcfg_lhc2_network6')} lookup lhc", "from 2001:700:2:8302::/64 to %{hiera('netcfg_uib_network6')} lookup uib", ]
profile::network::interface::manage_neutron_blackhole: true

profile::base::physical::configure_bmc_nic:                       true
profile::openstack::compute::hypervisor::enable_dhcp_agent_check: true
profile::base::physical::enable_redfish_scripts:                  true
profile::base::physical::enable_redfish_http_proxy:               true

calico::compute::bird_template:  'profile/bird/bird.conf.bgo.%{::os.release.major}.erb'
calico::compute::bird6_template: 'profile/bird/bird6.conf.bgo.erb'
calico::compute::felix_mtuIfacePattern: "^%{::interface_trp1}*"

# Cron tabs for power metric
profile::base::common::manage_cron: true
profile::base::cron::crontabs:
  power_metric:
    hour:     '*'
    minute:   '*/5'
    weekday:  '*'
    command:  "/usr/local/bin/power_metric.sh >/dev/null"
