---
# NVIDIA Ampere cards need SR-IOV and creation of mdevs
include:
  kickstart:
    - profile::openstack::compute::pci_passthrough
    - profile::openstack::compute::nvidia_vgpu_createmdev
  default:
    - nova::compute::mdev
    - profile::application::create_mdev
    - profile::openstack::compute::pci_passthrough
    - profile::openstack::compute::nvidia_vgpu_createmdev

named_interfaces::config:
  mgmt:
  - em1
  trp:
  - team1
  live:
  - team1.120

profile::base::network::network_auto_bonding:
  trp:
    em3:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'
    em4:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'


profile::base::network::network_auto_opts:
  mgmt:
    'defroute': 'no'
  trp:
    'defroute': 'no'
    'ipv6init': 'yes'
    'devicetype': 'Team'
    'mtu': '9000'
    'team_config': >-
                   { "runner" : {  "name" : "lacp",  "active": true, "fast_rate" : true,
                   "tx_hash": ["eth", "ipv4", "ipv6"], "tx_balancer": { "name": "basic" } },
                   "link_watch" : {  "name" : "ethtool" } }
  live:
    'defroute': 'no'

## Sensu 
sensu::agent::subscriptions:
  - 'base'
  - 'metrics'
  - 'compute'
  - 'physical'

profile::base::physical::enable_l40s_pci_check:  true

# Enable extra yum repo vGPU drivers
profile::base::yumrepo::repo_hash:
  nrec-nonfree:
    ensure: present

# NVIDIA Ampere cards need to create mediated devices at every boot
profile::openstack::compute::nvidia_vgpu_createmdev::enable: true
profile::base::selinux::semodules:
  sriov_manage:
    avc_file:   'sriov_manage.avc'

## Custom Sensu checks FIXME:sensu-go
# profile::monitoring::sensu::agent::checks:
#   'num-gpus-check':
#     command:      "/usr/local/bin/check_number_of_gpus.sh"
#     interval:     60
#     subscribers:  ['checks']
#   'metrics-nvidia':
#     type:         'metric'
#     command:      'metrics-nvidia.rb --scheme nvidia.%{::hostname}'
#     interval:     60
#     subscribers:  ['metrics']
#     handlers:     ['graphite_tcp']

profile::base::lvm::physical_volume:
  '/dev/sda4':
    ensure: present
    force:  true
  '/dev/sdb':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_instances':
    physical_volumes:
      - /dev/sdb
  'vg_ext':
    physical_volumes:
      - /dev/sda4
profile::base::lvm::logical_volume:
  'lv_instances':
    volume_group: 'vg_instances'
    fs_type:      "xfs"
    mountpath:    "/var/lib/nova/instances"


profile::base::common::packages:
  'wget': {}
  'kernel-devel': {}
  'kernel-headers': {}
  'unzip': {}
  'NVIDIA-vGPU-rhel': {
#    source: 'http://repo.mgmt.bgo.uhdc.no/NVIDIA-vGPU-rhel-7.8-450.55.x86_64.rpm'
  }


# NVIDIA L40S partitioned into 1x vGPUs, with CUDA support
#
# From "mdevctl types":
#
#  nvidia-1155
#    Available instances: 1
#    Device API: vfio-pci
#    Name: NVIDIA L40S-24Q
#    Description: num_heads=4, frl_config=60, framebuffer=24576M, max_resolution=7680x4320, max_instance=2
#
nova::compute::mdev::mdev_types_device_addresses_mapping: { 'nvidia-1155', }

# Max 8 instances per host
nova::scheduler::filter::max_instances_per_host: '8'

# NVIDIA newer generation cards need SR-IOV
profile::openstack::compute::pci_passthrough::configure_intel_iommu: true

# Configuration values for the "create-mdev" service
profile::application::create_mdev::enable:          true
profile::application::create_mdev::nvidia_gpu_type: 'nvidia-1155'
profile::application::create_mdev::trait:           'CUSTOM_NREC_VGPU_L40S_24G'

#yum_base_mirror:    'https://download.iaas.uio.no/uh-iaas/vgpu'

# remove when telemetry/ceilometer is up in all environments and move to common
profile::openstack::compute::manage_telemetry: true


## Not sure we need this, ref. line 121-123 ##
kmod::list_of_blacklists:
#  'nouveau': {}
#kmod::list_of_installs:
#  'nouveau':
#    command: '/bin/false'
kmod::list_of_options:
  'nouveau modeset':
    module: 'nouveau'
    option: 'modeset'
    value: '0'

profile::base::physical::blacklist_drv: true
profile::base::physical::blacklist_drv_list:
  'nouveau': {}


nova::compute::libvirt::cpu_models: ['Broadwell-noTSX-IBRS']

# These compute host uses local storage for instances
nova::compute::rbd::ephemeral_storage: false
nova::compute::libvirt::images_type: 'default'

# Configuration items not explicitly supported by the Puppet module
nova::config::nova_config:
  DEFAULT/metadata_workers:
    value: '4'

# Influx
ceph_influxdb_bucket: "gpu"
profile::monitoring::telegraf::enable_telegraf:     true
profile::monitoring::telegraf::outputs:
  influxdb_v2:
    options:
      - urls: ["https://%{hiera('mgmt__address__influx')}:8086"]
        tls_ca: '/etc/puppetlabs/puppet/ssl/certs/ca.pem'
        token: "%{hiera('influxdb_admin_token')}"
        organization: "%{hiera('profile::monitoring::influxdb::org')}"
        bucket: "%{hiera('ceph_influxdb_bucket')}"
        insecure_skip_verify: true
        tagpass:
          bucket: ["%{hiera('ceph_influxdb_bucket')}"]

profile::monitoring::telegraf::inputs:
#  prometheus:
#    options:
#      - urls: ["http://%{::ipaddress_mgmt1}:9400/metrics"]
#        metric_version: 2
#        tags:
#          bucket: "%{hiera('ceph_influxdb_bucket')}"
  nvidia_smi:
    options:
      - tags:
          bucket: "%{hiera('ceph_influxdb_bucket')}"
