---

# collectd
include:
  default:
    - profile::monitoring::collectd

profile::monitoring::collectd::enable: true

collectd::plugin::interface::interfaces:
  - "%{::interface_trp1}"
  - "%{::interface_mgmt1}"

profile::monitoring::collectd::plugins:
  - collectd::plugin::aggregation
  - collectd::plugin::cpu
#  - collectd::plugin::disk
  - collectd::plugin::load
  - collectd::plugin::memory
  - collectd::plugin::interface
  - collectd::plugin::write_graphite
  - collectd::plugin::virt
  - collectd::plugin::processes
  - collectd::plugin::numa
collectd::plugin::virt::hostname_format:        'hostname'
collectd::plugin::virt::plugin_instance_format: 'uuid'

ntp::servers:
  - 172.16.0.126
  - 172.16.0.127
  - 172.16.0.128
chrony::servers:
  - "%{hiera('netcfg_mgmt_netpart')}.126"
  - "%{hiera('netcfg_mgmt_netpart')}.127"
  - "%{hiera('netcfg_mgmt_netpart')}.128"

profile::base::network::network_auto_opts:
  mgmt:
    'defroute': 'no'
  trp:
    'defroute': 'no'
    'ipv6init': 'yes'
    'devicetype': 'Team'
    'mtu': '9000'
    'team_config': >-
                   { "runner" : {  "name" : "lacp",  "active": true, "fast_rate" : true,
                   "tx_hash": ["eth", "ipv4", "ipv6"], "tx_balancer": { "name": "basic" } },
                   "link_watch" : {  "name" : "ethtool" } }
  live:
    'defroute': 'no'

profile::base::network::network_auto_bonding:
  trp:
    em1:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'
    em2:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'

# IPv6 is enabled for bgp, bfd
profile::openstack::network::calico::manage_firewall6: true

# Add custom routing table for private network to NAT, lhc to other gw
profile::base::network::routes:
  team1:
    ipaddress:
      - '0.0.0.0'
      - "%{hiera('netcfg_priv_anycast_net')}"
      - '192.168.243.0'
      - '0.0.0.0'
      - '0.0.0.0'
      - '0.0.0.0'
      - '::'
      - '129.177.0.0'
      - '2001:700:200::'
    netmask:
      - '0.0.0.0'
      - "%{hiera('netcfg_priv_anycast_cidr4')}"
      - '255.255.255.0'
      - '0.0.0.0'
      - '0.0.0.0'
      - '0.0.0.0'
      - '0'
      - '255.255.0.0'
      - '48'
    gateway:
      - "%{hiera('netcfg_priv_gateway')}"
      - "%{hiera('netcfg_trp_gateway')}"
      - "%{hiera('netcfg_trp_gateway')}"
      - "%{hiera('netcfg_trp_gateway')}"
      - "%{hiera('netcfg_lhc_gateway')}"
      - "%{hiera('netcfg_lhcpriv_gateway')}"
      - "%{hiera('netcfg_lhc_gateway6')}"
      - "%{hiera('netcfg_uib_gateway')}"
      - "%{hiera('netcfg_uib_gateway6')}" 
    table:
      - 'private'
      - 'private'
      - 'lhc'
      - 'main'
      - 'lhc'
      - 'lhc-private'
      - 'lhc'
      - 'uib'
      - 'uib'
    family:
      - 'inet4'
      - 'inet4'
      - 'inet4'
      - 'inet4'
      - 'inet4'
      - 'inet4'
      - 'inet6'
      - 'inet4'
      - 'inet6'
profile::base::network::routing_tables:
  'private':
    'table_id':  '240'
  'lhc':
    'table_id':  '241'
  'lhc-private':
    'table_id':  '242'
  'uib':
    'table_id':  '243'
profile::base::network::rules:
  'team1':
    'iprule':  [ "from %{hiera('netcfg_priv_network')} lookup private", "from %{hiera('netcfg_lhc_network')} lookup lhc", "from %{hiera('netcfg_lhcpriv_network')} lookup lhc-private", "from 158.37.64.0/24 to %{hiera('netcfg_uib_network')} lookup uib", "from %{hiera('netcfg_educloud1_network')} lookup private", "from %{hiera('netcfg_elastic_cidr')} lookup private", ]
    'iprule6': [ "from %{hiera('netcfg_lhc_network6')} lookup lhc", "from %{hiera('netcfg_lhc2_network6')} lookup lhc", "from 2001:700:2:8302::/64 to %{hiera('netcfg_uib_network6')} lookup uib", ]
profile::base::network::manage_neutron_blackhole:      true # FIXME - remove when el7 is gone
profile::network::interface::manage_neutron_blackhole: true

profile::base::physical::configure_bmc_nic:                       true
profile::openstack::compute::hypervisor::enable_dhcp_agent_check: true
profile::base::physical::enable_redfish_sensu_check:              true
profile::base::physical::enable_redfish_http_proxy:               true
profile::monitoring::sensu::agent::checks:
  'redfish-check':
    command:      '/usr/local/bin/redfish_check.sh'
    interval:     1800
    subscribers:  ['checks']
  'dhcp-agent-check':
    command:      '/usr/local/bin/calico_dhcp_agent_check.sh'
    interval:     600
    subscribers:  ['checks']

calico::compute::bird_template:  'profile/bird/bird.conf.bgo.%{operatingsystemmajrelease}.erb'
calico::compute::bird6_template: 'profile/bird/bird6.conf.bgo.erb'
calico::compute::felix_mtuIfacePattern: '^team*'

# Cron tabs for power metric
profile::base::common::manage_cron: true
profile::base::cron::crontabs:
  power_metric:
    hour:     '*'
    minute:   '*/5'
    weekday:  '*'
    command:  "/usr/local/bin/power_metric.sh >/dev/null"

