---
ntp::servers:
  - 172.16.0.100
  - 172.16.0.101
  - 172.16.0.102

# NOTE: reflectors will be on cumulus gws for prod
calico::reflector: true

profile::firewall::rules:
  '020 allow all from transport network to public ip':
    destination: "%{ipaddress_public1}"
    source: '172.18.0.0/19'

profile::base::network::manage_httpproxy: 'true'
profile::base::network::http_proxy:       "%{hiera('service__address__proxy')}:8888"

puppet::cron_cmd: "if [ -e /etc/profile.d/proxy.sh ] ; then source /etc/profile.d/proxy.sh ; fi ; \
  /usr/bin/env puppet agent --config %{puppet::dir}/puppet.conf --onetime --no-daemonize"
