---
include:
  default:
    - profile::network::yum_proxy

puppet::cron_cmd: "/usr/bin/env puppet agent --config %{puppet::dir}/puppet.conf --onetime --no-daemonize"

ntp::servers:
  - 172.16.0.106
  - 172.16.0.107
  - 172.16.0.108

profile::openstack::network::calico::manage_bird: false

profile::openstack::resource::networks:
  public:
    name: 'public'
    admin_state_up: true
    shared: true
    tenant_name: 'openstack'
    provider_network_type: 'local'

profile::openstack::resource::subnets:
  public:
    name: 'public'
    cidr: '158.39.77.0/24'
    ip_version: '4'
    allocation_pools:
      - 'start=158.39.77.2,end=158.39.77.245'
    gateway_ip: '158.39.77.1'
    dns_nameservers:
      - '129.177.6.54'
      - '129.177.12.31'
    network_name: 'public'
    tenant_name: 'openstack'
