---
profile::network::leaf::manage_license: false

network::interfaces_hash:
  'e101-049-0':
    post_up: [ 'opx-ethtool -s e101-049-0 speed 1000 duplex full autoneg off' ]
  'e101-050-0':
    post_up: [ 'opx-ethtool -s e101-050-0 speed 1000 duplex full autoneg off' ]
  'e101-051-0':
    post_up: [ 'opx-ethtool -s e101-051-0 speed 1000 duplex full autoneg off' ]
  'e101-051-0':
    post_up: [ 'opx-ethtool -s e101-052-0 speed 1000 duplex full autoneg off' ]

