---
# Frontend zone
profile::dns::ns::frontend_zone: "uh-iaas.no"

# Designate server addresses (used by file templates)
profile::dns::ns::use_public_ip: true
profile::dns::ns::mdns_public_addr:
  - '2001:700:2:82ff::256'
  - '2001:700:2:83ff::256'

# DNS server firewall configuration (IPv6)
profile::dns::ns::rndc_sources_ipv6:
  - '2001:700:2:82ff::256/128'
  - '2001:700:2:83ff::256/128'

# Name servers in zone file
profile::dns::ns::ns_master: "ns2.%{hiera('profile::dns::ns::frontend_zone')}"
profile::dns::ns::ns_slaves:
  - "ns1.%{hiera('profile::dns::ns::frontend_zone')}"

# Master server for master-slave configuration
profile::dns::ns::ns_master_ip_addresses:
  - '158.37.63.251'        # ns1.uh-iaas.no IPv4 (OSL)
  - '2001:700:2:82ff::251' # ns1.uh-iaas.no IPv6 (OSL)

# Slave servers for master-slave configuration
profile::dns::ns::ns_slave_ip_addresses:
  - '158.37.63.251'        # ns1.uh-iaas.no IPv4 (OSL)
  - '2001:700:2:82ff::251' # ns1.uh-iaas.no IPv6 (OSL)

# Forward zones, for which the name server is authoritative
profile::dns::ns::fw_zones:
  internal:
    zone: "%{hiera('profile::dns::ns::internal_zone')}"
    filename: "pz/%{hiera('profile::dns::ns::internal_zone')}"
  public:
    zone: "%{hiera('profile::dns::ns::public_zone')}"
    filename: "pz/%{hiera('profile::dns::ns::public_zone')}"
#    delegations:
#      'customer':
#        - 'ns1.uh-iaas.no'
#        - 'ns2.uh-iaas.no'

# Reverse zones, for which the name server is authoritative
profile::dns::ns::ptr_zones:
  mgmt01:
    cidr:     "%{hiera('netcfg_mgmt_net_c0')}.0/24"
    origin:   "%{hiera('reverse_mgmt_c0')}"
    filename: "pz/%{hiera('reverse_mgmt_c0')}"
  mgmt02:
    cidr:     "%{hiera('netcfg_mgmt_net_c1')}.0/24"
    origin:   "%{hiera('reverse_mgmt_c1')}"
    filename: "pz/%{hiera('reverse_mgmt_c1')}"
  mgmt03:
    cidr:     "%{hiera('netcfg_mgmt_net_c2')}.0/24"
    origin:   "%{hiera('reverse_mgmt_c2')}"
    filename: "pz/%{hiera('reverse_mgmt_c2')}"
  mgmt04:
    cidr:     "%{hiera('netcfg_mgmt_net_c3')}.0/24"
    origin:   "%{hiera('reverse_mgmt_c3')}"
    filename: "pz/%{hiera('reverse_mgmt_c3')}"
  mgmt05:
    cidr:     "%{hiera('netcfg_mgmt_net_c4')}.0/24"
    origin:   "%{hiera('reverse_mgmt_c4')}"
    filename: "pz/%{hiera('reverse_mgmt_c4')}"
  mgmt06:
    cidr:     "%{hiera('netcfg_mgmt_net_c5')}.0/24"
    origin:   "%{hiera('reverse_mgmt_c5')}"
    filename: "pz/%{hiera('reverse_mgmt_c5')}"
  mgmt07:
    cidr:     "%{hiera('netcfg_mgmt_net_c6')}.0/24"
    origin:   "%{hiera('reverse_mgmt_c6')}"
    filename: "pz/%{hiera('reverse_mgmt_c6')}"
  mgmt08:
    cidr:     "%{hiera('netcfg_mgmt_net_c7')}.0/24"
    origin:   "%{hiera('reverse_mgmt_c7')}"
    filename: "pz/%{hiera('reverse_mgmt_c7')}"
  transport01:
    cidr:     "%{hiera('netcfg_trp_net_c0')}.0/24"
    origin:   "%{hiera('reverse_trp_c0')}"
    filename: "pz/%{hiera('reverse_trp_c0')}"
  transport02:
    cidr:     "%{hiera('netcfg_trp_net_c1')}.0/24"
    origin:   "%{hiera('reverse_trp_c1')}"
    filename: "pz/%{hiera('reverse_trp_c1')}"
  transport03:
    cidr:     "%{hiera('netcfg_trp_net_c2')}.0/24"
    origin:   "%{hiera('reverse_trp_c2')}"
    filename: "pz/%{hiera('reverse_trp_c2')}"
  transport04:
    cidr:     "%{hiera('netcfg_trp_net_c3')}.0/24"
    origin:   "%{hiera('reverse_trp_c3')}"
    filename: "pz/%{hiera('reverse_trp_c3')}"
  transport05:
    cidr:     "%{hiera('netcfg_trp_net_c4')}.0/24"
    origin:   "%{hiera('reverse_trp_c4')}"
    filename: "pz/%{hiera('reverse_trp_c4')}"
  transport06:
    cidr:     "%{hiera('netcfg_trp_net_c5')}.0/24"
    origin:   "%{hiera('reverse_trp_c5')}"
    filename: "pz/%{hiera('reverse_trp_c5')}"
  transport07:
    cidr:     "%{hiera('netcfg_trp_net_c6')}.0/24"
    origin:   "%{hiera('reverse_trp_c6')}"
    filename: "pz/%{hiera('reverse_trp_c6')}"
  transport08:
    cidr:     "%{hiera('netcfg_trp_net_c7')}.0/24"
    origin:   "%{hiera('reverse_trp_c7')}"
    filename: "pz/%{hiera('reverse_trp_c7')}"
  public01:
    cidr: "158.39.74.0/24"
    origin: "74.39.158.in-addr.arpa"
    filename: "pz/74.39.158.in-addr.arpa"
  public02:
    cidr: "158.39.77.0/24"
    origin: "77.39.158.in-addr.arpa"
    filename: "pz/77.39.158.in-addr.arpa"
  ipv6:
    cidr: "2001:700:2:83ff::/64"
    origin: "f.f.3.8.0.0.7.0.2.0.0.0.1.0.0.2.ip6.arpa"
    filename: "pz/f.f.3.8.0.0.7.0.2.0.0.0.1.0.0.2.ip6.arpa"

# Secondary forward zones, for which this ns is slave
profile::dns::ns::fw_slave_zones:
  osl_internal:
    zone: "osl.uhdc.no"
    filename: "sz/osl.uhdc.no"
  osl_public:
    zone: "osl.uh-iaas.no"
    filename: "sz/osl.uh-iaas.no"
  frontend:
    zone: "uh-iaas.no"
    filename: "sz/uh-iaas.no"

# Secondary reverse zones, for which this ns is slave
profile::dns::ns::ptr_slave_zones:
  osl_mgmt01:
    cidr: "172.16.32.0/24"
    origin: "32.16.172.in-addr.arpa"
    filename: "sz/32.16.172.in-addr.arpa"
  osl_mgmt02:
    cidr: "172.16.33.0/24"
    origin: "33.16.172.in-addr.arpa"
    filename: "sz/33.16.172.in-addr.arpa"
  osl_mgmt03:
    cidr: "172.16.34.0/24"
    origin: "34.16.172.in-addr.arpa"
    filename: "sz/34.16.172.in-addr.arpa"
  osl_mgmt04:
    cidr: "172.16.35.0/24"
    origin: "35.16.172.in-addr.arpa"
    filename: "sz/35.16.172.in-addr.arpa"
  osl_mgmt05:
    cidr: "172.16.36.0/24"
    origin: "36.16.172.in-addr.arpa"
    filename: "sz/36.16.172.in-addr.arpa"
  osl_mgmt06:
    cidr: "172.16.37.0/24"
    origin: "37.16.172.in-addr.arpa"
    filename: "sz/37.16.172.in-addr.arpa"
  osl_mgmt07:
    cidr: "172.16.38.0/24"
    origin: "38.16.172.in-addr.arpa"
    filename: "sz/38.16.172.in-addr.arpa"
  osl_mgmt08:
    cidr: "172.16.39.0/24"
    origin: "39.16.172.in-addr.arpa"
    filename: "sz/39.16.172.in-addr.arpa"
  osl_transport01:
    cidr: "172.18.32.0/24"
    origin: "32.18.172.in-addr.arpa"
    filename: "sz/32.18.172.in-addr.arpa"
  osl_transport02:
    cidr: "172.18.33.0/24"
    origin: "33.18.172.in-addr.arpa"
    filename: "sz/33.18.172.in-addr.arpa"
  osl_transport03:
    cidr: "172.18.34.0/24"
    origin: "34.18.172.in-addr.arpa"
    filename: "sz/34.18.172.in-addr.arpa"
  osl_transport04:
    cidr: "172.18.35.0/24"
    origin: "35.18.172.in-addr.arpa"
    filename: "sz/35.18.172.in-addr.arpa"
  osl_transport05:
    cidr: "172.18.36.0/24"
    origin: "36.18.172.in-addr.arpa"
    filename: "sz/36.18.172.in-addr.arpa"
  osl_transport06:
    cidr: "172.18.37.0/24"
    origin: "37.18.172.in-addr.arpa"
    filename: "sz/37.18.172.in-addr.arpa"
  osl_transport07:
    cidr: "172.18.38.0/24"
    origin: "38.18.172.in-addr.arpa"
    filename: "sz/38.18.172.in-addr.arpa"
  osl_transport08:
    cidr: "172.18.39.0/24"
    origin: "39.18.172.in-addr.arpa"
    filename: "sz/39.18.172.in-addr.arpa"
  osl_public01:
    cidr: "158.37.63.0/24"
    origin: "63.37.158.in-addr.arpa"
    filename: "sz/63.37.158.in-addr.arpa"
  osl_public02:
    cidr: "158.39.75.0/24"
    origin: "75.39.158.in-addr.arpa"
    filename: "sz/75.39.158.in-addr.arpa"
  osl_ipv6:
    cidr: "2001:700:2:82ff::/64"
    origin: "f.f.2.8.0.0.7.0.2.0.0.0.1.0.0.2.ip6.arpa"
    filename: "sz/f.f.2.8.0.0.7.0.2.0.0.0.1.0.0.2.ip6.arpa"
