---
named_interfaces::config:
  mgmt:
    - em3
  trp:
    - team1
  ceph:
    - team1.130

profile::base::network::network_auto_opts:
  trp:
    'defroute': 'no'
    'devicetype': 'Team'
    'team_config': >-
                   { "runner" : {  "name" : "lacp",  "active": true, "fast_rate" : true,
                   "tx_hash": ["eth", "ipv4", "ipv6"], "tx_balancer": { "name": "basic" } },
                   "link_watch" : {  "name" : "ethtool" } }
  ceph:
    'defroute': 'no'

ceph::profile::params::mon_host:              "%{::netpart_trp1}.89:6789,%{::netpart_trp1}.90:6789,%{::netpart_trp1}.94:6789"
ceph::profile::params::mon_initial_members:   '%{::location}-cephmon-object-01,%{::location}-cephmon-object-02,%{::location}-cephmon-object-03'
ceph::profile::params::cluster_network:       "%{::network_ceph1}/%{::cidr_ceph1}"
ceph::profile::params::public_network:        "%{::network_trp1}/%{::cidr_trp1}"

profile::base::lvm::physical_volume:
  '/dev/sda':
    ensure: present
    force:  true

profile::base::lvm::volume_group:
  'vg_cache':
    physical_volumes:
      - /dev/sda

profile::base::lvm::logical_volume:
  'lv_walc':
    volume_group: 'vg_cache'
    createfs:     false
    size:         2G
  'lv_dbc':
    volume_group: 'vg_cache'
    createfs:     false
    size:         10G
  'lv_wald':
    volume_group: 'vg_cache'
    createfs:     false
    size:         2G
  'lv_dbd':
    volume_group: 'vg_cache'
    createfs:     false
    size:         10G
  'lv_wale':
    volume_group: 'vg_cache'
    createfs:     false
    size:         2G
  'lv_dbe':
    volume_group: 'vg_cache'
    createfs:     false
    size:         10G
  'lv_walf':
    volume_group: 'vg_cache'
    createfs:     false
    size:         2G
  'lv_dbf':
    volume_group: 'vg_cache'
    createfs:     false
    size:         10G
  'lv_walg':
    volume_group: 'vg_cache'
    createfs:     false
    size:         2G
  'lv_dbg':
    volume_group: 'vg_cache'
    createfs:     false
    size:         10G

profile::storage::cephosd::osds:
  '/dev/sdb': {} # SSD
  '/dev/sdc': # HDD
    db_device:  'vg_cache/lv_dbc'
    wal_device: 'vg_cache/lv_walc'
  '/dev/sdd': # HDD
    db_device:  'vg_cache/lv_dbd'
    wal_device: 'vg_cache/lv_wald'
  '/dev/sde': # HDD
    db_device:  'vg_cache/lv_dbe'
    wal_device: 'vg_cache/lv_wale'
  '/dev/sdf': # HDD
    db_device:  'vg_cache/lv_dbf'
    wal_device: 'vg_cache/lv_walf'
  '/dev/sdg': # HDD
    db_device:  'vg_cache/lv_dbg'
    wal_device: 'vg_cache/lv_walg'
