---
named_interfaces::config:
  mgmt:
    - p4p4
  transport:
    - team1
  trp:
    - team1
  ceph:
    - team1.110

ceph_version: 'quincy' # FIXME

profile::base::common::manage_lvm:                  true
profile::base::lvm::create_lvm:                     true
profile::storage::cephpool::manage_ec_pools:        true
profile::storage::cephpool::manage_cephpool_params: true

profile::storage::cephosd::crush_parent:      'dcache'
profile::storage::cephosd::crush_parent_type: 'pod'

# Ensure that the BOSS device is the first device
profile::base::physical::load_ahci_first: true
profile::base::physical::load_ahci_first_scsidrv: 'mpt3sas'

profile::storage::cephclient::create_extraconf: true
profile::storage::ceph_extraconf::config:
  osd_memory_target:
    'config_key'  : "osd/osd_memory_target"
    'config_value': "10200547328" # 9.5GB pr OSD
  osd_deep_scrub_interval:
    'config_key'  : "osd/osd_deep_scrub_interval"
    'config_value': "2419200.000000"
  osd scrub max interval:
    'config_key'  : "osd/osd_scrub_max_interval"
    'config_value': "2419200.000000"
  osd_scrub_priority:
    'config_key'  : "osd/osd_scrub_priority"
    'config_value': "1"
  osd_scrub_sleep:
    'config_key'  : "osd/osd_scrub_sleep"
    'config_value': "0.5"
  osd_scrub_chunk_min:
    'config_key'  : "osd/osd_scrub_chunk_min"
    'config_value': "1"
  osd_scrub_chunk_max:
    'config_key'  : "osd/osd_scrub_chunk_max"
    'config_value': "5"

ceph::profile::params::osd_max_scrubs: '2'
ceph::profile::params::osd_recovery_max_active: '3'
ceph::profile::params::osd_max_backfills: '1'

profile::storage::ceph_ecpool::ec_pools:
  'dcache_hdd_ec82_data':
    pg_num:              "8192"
    manage:              true
    allow_ec_overwrites: true
    k_data:              "8"
    m_code:              "2"
    crush_root:          "dcache"
    plugin:              "jerasure"
    technique:           "reed_sol_r6_op"

profile::storage::ceph::pool::pools:
  'rbd':
    ensure: absent
  'dcache_hdd_ec82_meta':
    size:    3
    pg_num:  64
    tag:    'rbd'
    custom:
      crush_rule: 'ssd-storage'
      nodelete:   'true'
      min_size:   '2'
  'dcache_hdd_ec82_data':
    custom:
      deep_scrub_interval: '1.93536e+07' # every 32 weeks - overrides osd setting
      scrub_max_interval:  '2.4192e+06'  # normal scrub at least every 4 weeks - overrides osd setting
      scrub_min_interval:  '604800'      # minimum one week between each scrub
      fast_read:           '1'           # read all k+m for read, trade bandwith for lower latency
profile::storage::ceph::pool::ec_pools:
  'placeholder':
    manage: false

profile::storage::cephpool_params::pools:
  'dcache_hdd_ec82_data':
    application_enable: 'rbd'
    replicas_min_size:  '9'

profile::base::common::extraswap:         true
profile::base::common::extraswap_sizegb:  20
profile::base::common::extraswap_fileloc: '/var/lib/swap/swapfile'

# Disable write cache on osd cache disks
profile::base::disk::manage_hdparm: true
profile::base::disk::disk_hdparams:
  '/dev/sdn': { hdparams: '-W0', }
  '/dev/sdo': { hdparams: '-W0', }

profile::base::lvm::volume_group:
  'vg_swap':
    physical_volumes:
      - /dev/sda4
  'vg_ssd1':
    physical_volumes:
      - /dev/sdn
  'vg_ssd2':
    physical_volumes:
      - /dev/sdo
profile::base::lvm::logical_volume:
  'lv_swap2':
    volume_group: 'vg_swap'
    fs_type:      xfs
    size:         40G
    mountpath:    "/var/lib/swap"
  'lv_ssd_osd1':
    volume_group: 'vg_ssd1'
    createfs:     false
    size:         192G
  'lv_dbb':
    volume_group: 'vg_ssd1'
    createfs:     false
    size:         31G
  'lv_dbc':
    volume_group: 'vg_ssd1'
    createfs:     false
    size:         31G
  'lv_dbd':
    volume_group: 'vg_ssd1'
    createfs:     false
    size:         31G
  'lv_dbe':
    volume_group: 'vg_ssd1'
    createfs:     false
    size:         31G
  'lv_dbf':
    volume_group: 'vg_ssd1'
    createfs:     false
    size:         31G
  'lv_dbg':
    volume_group: 'vg_ssd1'
    createfs:     false
    size:         31G
  'lv_dbh':
    volume_group: 'vg_ssd1'
    createfs:     false
    size:         31G
  'lv_dbi':
    volume_group: 'vg_ssd1'
    createfs:     false
    size:         31G
  'lv_ssd_osd2':
    volume_group: 'vg_ssd2'
    createfs:     false
    size:         192G
  'lv_dbj':
    volume_group: 'vg_ssd2'
    createfs:     false
    size:         31G
  'lv_dbk':
    volume_group: 'vg_ssd2'
    createfs:     false
    size:         31G
  'lv_dbl':
    volume_group: 'vg_ssd2'
    createfs:     false
    size:         31G
  'lv_dbm':
    volume_group: 'vg_ssd2'
    createfs:     false
    size:         31G
  'lv_dbp':
    volume_group: 'vg_ssd2'
    createfs:     false
    size:         31G
  'lv_dbq':
    volume_group: 'vg_ssd2'
    createfs:     false
    size:         31G
  'lv_dbr':
    volume_group: 'vg_ssd2'
    createfs:     false
    size:         31G
  'lv_dbs':
    volume_group: 'vg_ssd2'
    createfs:     false
    size:         31G
profile::base::lvm::physical_volume:
  '/dev/sdn':
    ensure: present
    force:  true
  '/dev/sdo':
    ensure: present
    force:  true

profile::storage::cephosd::osds:
  '/dev/sdb':
    wal_device: false
    db_device:  'vg_ssd1/lv_dbb'
  '/dev/sdc':
    wal_device: false
    db_device:  'vg_ssd1/lv_dbc'
  '/dev/sdd':
    wal_device: false
    db_device:  'vg_ssd1/lv_dbd'
  '/dev/sde':
    wal_device: false
    db_device:  'vg_ssd1/lv_dbe'
  '/dev/sdf':
    wal_device: false
    db_device:  'vg_ssd1/lv_dbf'
  '/dev/sdg':
    wal_device: false
    db_device:  'vg_ssd1/lv_dbg'
  '/dev/sdh':
    wal_device: false
    db_device:  'vg_ssd1/lv_dbh'
  '/dev/sdi':
    wal_device: false
    db_device:  'vg_ssd1/lv_dbi'
  '/dev/sdj':
    wal_device: false
    db_device:  'vg_ssd2/lv_dbj'
  '/dev/sdk':
    wal_device: false
    db_device:  'vg_ssd2/lv_dbk'
  '/dev/sdl':
    wal_device: false
    db_device:  'vg_ssd2/lv_dbl'
  '/dev/sdm':
    wal_device: false
    db_device:  'vg_ssd2/lv_dbm'
  '/dev/sdp':
    wal_device: false
    db_device:  'vg_ssd2/lv_dbp'
  '/dev/sdq':
    wal_device: false
    db_device:  'vg_ssd2/lv_dbq'
  '/dev/sdr':
    wal_device: false
    db_device:  'vg_ssd2/lv_dbr'
  '/dev/sds':
    wal_device: false
    db_device:  'vg_ssd2/lv_dbs'
  '/dev/vg_ssd1/lv_ssd_osd1':
    wal_device: false
    db_device:  false
  '/dev/vg_ssd2/lv_ssd_osd2':
    wal_device: false
    db_device:  false
