---
named_interfaces::config:
  mgmt:
    - em3
  transport:
    - team1
  trp:
    - team1

ceph::profile::params::osds:
  '/dev/sda':
    db_device:  '/dev/sdk'
    wal_device: '/dev/sdk'
  '/dev/sdb':
    db_device:  '/dev/sdk'
    wal_device: '/dev/sdk'
  '/dev/sdc':
    db_device:  '/dev/sdk'
    wal_device: '/dev/sdk'
  '/dev/sdd':
    db_device:  '/dev/sdk'
    wal_device: '/dev/sdk'
  '/dev/sde':
    db_device:  '/dev/sdk'
    wal_device: '/dev/sdk'
#  '/dev/sdf':
#    db_device:  '/dev/sdk'
#    wal_device: '/dev/sdk'
#  '/dev/sdg':
#    db_device:  '/dev/sdk'
#    wal_device: '/dev/sdk'
#  '/dev/sdh':
#    db_device:  '/dev/sdk'
#    wal_device: '/dev/sdk'
#  '/dev/sdi':
#    db_device:  '/dev/sdk'
#    wal_device: '/dev/sdk'
#  '/dev/sdj':
#    db_device:  '/dev/sdk'
#    wal_device: '/dev/sdk'
