---
named_interfaces::config:
  mgmt:
    - em3
  transport:
    - team1
  trp:
    - team1
  ceph:
    - team1.110

profile::base::network::network_auto_opts:
  trp:
    'defroute': 'no'
    'devicetype': 'Team'
    'mtu': '9000'
    'team_config': >-
                   { "runner" : {  "name" : "lacp",  "active": true, "fast_rate" : true,
                   "tx_hash": ["eth", "ipv4", "ipv6"], "tx_balancer": { "name": "basic" } },
                   "link_watch" : {  "name" : "ethtool" } }
  ceph:
    'defroute': 'no'

profile::base::network::network_auto_bonding:
  trp:
    em1:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'
    em2:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'

profile::storage::ceph_crushrules::rules:
  'hdd-storage':
    rule_device_type: "hdd"
    rule_root:        "storage"
  'ssd-storage':
    rule_device_type: "sdd"
    rule_root:        "storage"
  'hdd-dcache':
    rule_device_type: "hdd"
    rule_root:        "dcache"
  'ssd-dcache':
    rule_device_type: "ssd"
    rule_root:        "dcache"

# Disable intel c states for performance
profile::base::physical::disable_intel_cstates: true

profile::base::physical::configure_bmc_nic:          true
profile::base::physical::enable_redfish_sensu_check: true
profile::monitoring::sensu::agent::checks:
  'redfish-check':
    command:      '/usr/local/bin/redfish_check.sh'
    interval:     1800
    subscribers:  ['checks']

# Cron tabs for power metric
profile::base::common::manage_cron: true
profile::base::cron::crontabs:
  power_metric:
    hour:     '*'
    minute:   '*/5'
    weekday:  '*'
    command:  "/usr/local/bin/power_metric.sh >/dev/null"

profile::storage::ceph::pool::pools:
  'rbd':
    ensure: absent
profile::storage::ceph::pool::ec_pools:
  'placeholder':
    manage: false

profile::base::lvm::physical_volume:
  '/dev/sdk':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_cache':
    physical_volumes:
      - /dev/sdk
profile::base::lvm::logical_volume:
  'lv_dba':
    volume_group: 'vg_cache'
    createfs:     false
    size:         35G
  'lv_dbb':
    volume_group: 'vg_cache'
    createfs:     false
    size:         35G
  'lv_dbc':
    volume_group: 'vg_cache'
    createfs:     false
    size:         35G
  'lv_dbd':
    volume_group: 'vg_cache'
    createfs:     false
    size:         35G
  'lv_dbe':
    volume_group: 'vg_cache'
    createfs:     false
    size:         35G

profile::storage::cephosd::osds:
  '/dev/sda':
    db_device:  'vg_cache/lv_dba'
    wal_device: false
  '/dev/sdb':
    db_device:  'vg_cache/lv_dbb'
    wal_device: false
  '/dev/sdc':
    db_device:  'vg_cache/lv_dbc'
    wal_device: false
  '/dev/sdd':
    db_device:  'vg_cache/lv_dbd'
    wal_device: false
  '/dev/sde':
    db_device:  'vg_cache/lv_dbe'
    wal_device: false
  '/dev/sdf':
    disable_writecache: true
  '/dev/sdg':
    disable_writecache: true
  '/dev/sdh':
    disable_writecache: true
  '/dev/sdi':
    disable_writecache: true
  '/dev/sdj':
    disable_writecache: true
